OSOE-93: Add a UI test to Lombiq.Privacy
Lombiq/Open-Source-Orchard-Core-Extensions pull request #105
Opened 2022-05-12 20:25 UTC by dministro

OSOE-93

2022-05-24 14:07 UTC, sarahelsaig commented
You have a merge conflict

2022-05-24 16:44 UTC, DAud-IcI requested changes

2022-05-24 16:44 UTC, sarahelsaig commented on test/Lombiq.OSOCE.Tests.UI/Tests/BehaviorPrivacyTests.cs
> +            );
These two are running in parallel. Is that safe? Also the code is identical besides the theme name, so please extract into a method.

2022-05-26 11:02 UTC, DAud-IcI requested changes
Add Lombiq.ChartJs.Samples and Lombiq.Privacy.Samples to the [NuGet csproj](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/issue/OSOE-93/NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj) and invoke the tests for both project from [BehaviorModuleTests.cs](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/issue/OSOE-93/NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorModuleTests.cs) as well. 
(But first push a new tag for Lombiq.Privacy.)

2022-05-26 11:56 UTC, dministro commented
> Add Lombiq.ChartJs.Samples and Lombiq.Privacy.Samples to the [NuGet csproj](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/issue/OSOE-93/NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj) and invoke the tests for both project from [BehaviorModuleTests.cs](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/issue/OSOE-93/NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorModuleTests.cs) as well. (But first push a new tag for Lombiq.Privacy.)

I did this [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/105/commits/075218320ae89e3fe31c5a4e627a8c7bd5df83e0) but CI `Build and Test (NuGet solution) (Developer)` failed because of the prerelease package versions.

What is the correct process to make this?

2022-05-26 12:23 UTC, DAud-IcI commented
I have checked out the commit you linked, run the command in the failed CI's log and it worked fine for me with no errors. In principle the errors make no sense, because you have the correct versions in your project files. Could be that you committed too soon and the NuGet cache wasn't updated yet, but normally that results in a "version not found" type of message so I'm just speculating.

Give it another try, but before you push to origin make sure it works for you locally by running
```powershell
dotnet build Lombiq.OSOCE.NuGet.sln --configuration Release --version-suffix 615 /p:Version="1.0.615.0" /p:RunAnalyzersDuringBuild=true /p:TreatWarningsAsErrors=true -warnaserror /nodeReuse:false /p:Retries=4 /p:RetryDelayMilliseconds=1000 /p:NoWarn=AD0001%3BNETSDK1179 -warnAsMessage:MSB3026
```
inside the solution's NuGetTest directory. If it works for you locally and still fails on the server, then open a thread in Teams in the infrastructure channel.

2022-05-29 20:10 UTC, DAud-IcI requested changes

2022-05-29 20:10 UTC, DAud-IcI commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/.htmlvalidate.json
> +  ]
Do you still need these? The `dev` of Lombiq.Tests.UI [already uses html-validation v.7.1.1](https://github.com/Lombiq/UI-Testing-Toolbox/blob/beebd4b322cf520c060fe409955b33ac6681a7c8/Lombiq.Tests.UI/Services/HtmlValidationConfiguration.cs#L36).

2022-05-30 14:09 UTC, merged