OSOE-110: ⭐ Fix that the NuGet version of Lombiq Analyzer doesn't detect any analyzer violations
Lombiq/Open-Source-Orchard-Core-Extensions pull request #109
Opened 2022-05-16 18:34 UTC by DAud-IcI

OSOE-110

2022-05-16 19:12 UTC, DAud-IcI commented
At this point the test _should_ fail. Specifically I expect that one of the two cases of `AnalyzerViolationShouldBeReported` passes and the other fails, since the current state is that submodule works but NuGet does not.

This actually happens on the GitHub workflow, but the TC doesn't include the new _Lombiq.Analyzers.Tests_ project at all, so it passes. Any idea what I'm missing?

2022-05-16 19:57 UTC, Piedone commented
It only looks under the src folder for test projects. I've changed the config to look under _tools_ too, and restarted the build. Now it should fail.

2022-05-16 20:10 UTC, DAud-IcI commented
Thanks, now everything is as it should be.
![image](https://user-images.githubusercontent.com/4007293/168674242-966a423c-ef08-4d0f-81e5-d1c3f9956b29.png)

2022-05-16 20:20 UTC, Piedone commented
I've reset the config to the original now.

2022-07-02 21:21 UTC, DAud-IcI commented on NuGetTest/src/Themes/Lombiq.OSOCE.NuGet.TestTheme/Lombiq.OSOCE.NuGet.TestTheme.csproj
> -    <Content Include="package.json" />
This was somehow a duplicate. Not sure which one should be kept or if it matters.

2022-08-02 13:28 UTC, 0liver requested changes

2022-08-02 13:28 UTC, 0liver commented on Directory.Build.props
> +          Condition="'$(NuGetTestbed)' != 'true' AND '$(SkipRootBuildProps)' != 'true'"/>
Both of these conditions should turn out unnecessary, since it's the existence of a _Directory.Build.props_ further down the folder hierarchy that stops importing those further up ([docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022#search-scope)).

2022-08-02 13:28 UTC, 0liver commented on NuGetTest/src/Themes/Lombiq.OSOCE.NuGet.TestTheme/Lombiq.OSOCE.NuGet.TestTheme.csproj
> -    <Content Include="package.json" />
I don't know either right now.

2022-08-02 14:23 UTC, DAud-IcI commented on Directory.Build.props
> +          Condition="'$(NuGetTestbed)' != 'true' AND '$(SkipRootBuildProps)' != 'true'"/>
It's also used for something infrastructure-related. ([see issue description](https://lombiq.atlassian.net/browse/OSOE-110#:~:text=ask%20the%20infrastructure%20team%20to%20replace%20-p%3Anugettestbed%3Dtrue%20with%20-p%3Askiprootbuildprops%3Dtrue%20in%20the%20gulp%20extension%20build%20of%20the%20build%20and%20test%20(developer)%20configuration.%20see%20this%20teams%20thread.))

2022-08-03 22:39 UTC, 0liver approved these changes

2022-08-04 21:52 UTC, merged