OSOE-44: Open-source UI Testing Toolbox
Lombiq/Open-Source-Orchard-Core-Extensions pull request #11
Opened 2021-09-05 21:45 UTC by Piedone

OSOE-44

2021-09-07 02:00 UTC, DAud-IcI requested changes

2021-09-07 02:00 UTC, DAud-IcI commented on Readme.md
> +[![TeamCity build status](https://ci.lombiq.com/app/rest/builds/buildType:id:OrchardExtensions_OSOCE_Developer_PullAndBuild/statusIcon.svg)](https://ci.lombiq.com/buildConfiguration/OrchardExtensions
Az oké nyilvános projektnél, hogy ez a link csak login után érhető el?

2021-09-07 02:00 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Recipes/JsonEditor.recipe.json
> +  "issetuprecipe": true,
Miért true? Setupnak ez kevés így magában. (csak a JSON editor specifikus példa tartalom)
Lehet setup, de akkor kéne az elejére egy recipe lépés pl a "Lombiq.TrainingDemo"-ra.

2021-09-07 15:54 UTC, Piedone commented on Readme.md
> +[![TeamCity build status](https://ci.lombiq.com/app/rest/builds/buildType:id:OrchardExtensions_OSOCE_Developer_PullAndBuild/statusIcon.svg)](https://ci.lombiq.com/buildConfiguration/OrchardExtensions
Elérhető: 
![image](https://user-images.githubusercontent.com/1976647/132375059-94cfb7dc-fb74-4f26-9649-5b363e9e1a7e.png)

2021-09-07 17:49 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/JsonEditor.recipe.json
> +  "issetuprecipe": true,
Ja igen, ez véletlen.

2021-09-08 00:44 UTC, DAud-IcI approved these changes

2021-09-08 13:51 UTC, merged