OSOE-111: Detect visual errors (visual verification testing) in the UI Testing Toolbox
Lombiq/Open-Source-Orchard-Core-Extensions pull request #115
Opened 2022-05-24 20:16 UTC by dministro

OSOE-111

2022-06-02 21:04 UTC, Piedone requested changes
Merge from dev, please.

2022-06-02 21:04 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +            powershell Set-DisplayResolution -Width 1920 -Height 1080 -Force
This shouldn't be necessary as UI testing shouldn't rely on the screen resolution. That's why we also have `SetBrowserSize()`.

2022-06-04 17:35 UTC, dministro commented on .github/workflows/build-and-test.yml
> +            powershell Set-DisplayResolution -Width 1920 -Height 1080 -Force
Unfortunately, this or something similar is necessary, because, without this, the browser window size is smaller than expected on windows-latest.
Below you can find screenshots and sizes before and after setting screen resolution on windows-latest.

**ubuntu-latest:**
size: 1600 ×900
![ubuntu-latest_navbar_full_screen](https://user-images.githubusercontent.com/15349881/172018490-c2d57bcb-0416-4297-93b3-4bdd5e6d673c.png)

**windows-latest**-before setting screen resolution
size: 1028 × 655
![windows-latest_navbar_full_screen](https://user-images.githubusercontent.com/15349881/172018492-7a1d504c-37e9-4490-8b6e-9440cc4b2fd8.png)

**windows-latest**-after setting screen resolution
size: 1600 ×900
![windows-latest_after_set_screen_size_navbar_full_screen](https://user-images.githubusercontent.com/15349881/172018491-c723841a-847f-4523-b9ec-ee0150400a9d.png)

2022-06-08 21:53 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +            powershell Set-DisplayResolution -Width 1920 -Height 1080 -Force
Please look into how this works with GitHub Actions, and why this difference between platforms is there.

2022-06-09 07:22 UTC, dministro commented on .github/workflows/build-and-test.yml
> +            powershell Set-DisplayResolution -Width 1920 -Height 1080 -Force
**Maximum window size on windows-latest:**
If I remember well, the maximum window size can't be larger than the desktop size(plus some pixels) on windows.
I didn't find official documentation about this, but I tested it in non-headless mode:
My desktop size: 3840×1200
Requested window size: context.SetBrowserSize(CommonDisplayResolutions.FiveK)
The resulted window size: 3860×1220
![image](https://user-images.githubusercontent.com/15349881/172785146-b2f6e5ed-1c7b-4f73-b283-cd10889489a4.png)

**GH windows-latest default screen resolution:**
I didn't find official documentation about this, but here is an issue(related to Windows 2019 and screen size): https://github.com/actions/virtual-environments/issues/2935

I'll give it a try to run UI tests in headless mode on windows-latest. As I see in the workflow and configuration they are started in non-headless mode.

2022-06-09 08:32 UTC, dministro commented on .github/workflows/build-and-test.yml
> +            powershell Set-DisplayResolution -Width 1920 -Height 1080 -Force
It's not surprising, but all tests passed on windows-latest in headless mode without setting screen resolution.

So, which mode is preferred on windows-latest? headless or non-headless?

2022-06-09 13:19 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +            powershell Set-DisplayResolution -Width 1920 -Height 1080 -Force
Great then! Headless all the way. However, how was it not headless before? Hmm, `UITestBase` makes it default to `false` in both test projects (due to the global default being `true`). I think we did that to aid in inspecting them locally, due to the demonstration purpose the two test projects serve. So, you can just set that config as `true` in the GitHub build's `Tests` step. (In TeamCity it's set as such from its config.)

2022-06-09 20:52 UTC, Piedone requested changes

2022-06-09 20:52 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Lombiq.OSOCE.NuGet.Tests.UI.csproj
> -      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
Why is this necessary?

2022-06-09 20:52 UTC, Piedone commented on NuGetTest/src/Themes/Lombiq.OSOCE.NuGet.TestTheme/Lombiq.OSOCE.NuGet.TestTheme.csproj
> +    <PackageReference Include="OrchardCore.Theme.Targets" Version="1.4.0" />
Thanks for noticing these!

2022-06-14 21:10 UTC, dministro commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Lombiq.OSOCE.NuGet.Tests.UI.csproj
> -      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
This was an accident.

This change was because there are 3 .htmlvalidate.json under OSOCE and all of it is set to `PreserveNewest`. One of them is in Lombiq.Tests.UI NuGet package, is a dependency of Lombiq.OSOCE.NuGet.Tests.UI project, which contains .htmlvalidate.json too. After I created a new prerelease from Lombiq.Tests.UI project, it become newer, and this caused problems on the local run of NuGet tests.

2022-06-15 00:05 UTC, Piedone commented
Merge from dev, please.

2022-06-16 17:44 UTC, Piedone approved these changes

2022-06-19 14:33 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +        }
You'll need to add this to https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/test-dotnet/run-tests.ps1 after merging from dev. And there it would be simpler to just write `$Env:Lombiq_Tests_UI__BrowserConfiguration__Headless = "true"` instead, and changing the existing `Configure-Environment`s to that too.

2022-06-19 16:02 UTC, dministro commented on .github/workflows/build-and-test.yml
> +        }
Thank you for the info.

2022-06-21 19:10 UTC, Piedone approved these changes

2022-06-26 23:13 UTC, Piedone approved these changes

2022-06-29 20:50 UTC, Piedone requested changes
Merge from dev, please.

2022-06-30 19:09 UTC, merged