FINI-854: Using pnpm to restore packages
Lombiq/Open-Source-Orchard-Core-Extensions pull request #12
Opened 2021-09-08 12:19 UTC by barthamark

FINI-854

2021-09-08 14:51 UTC, Piedone commented
Mergelj devből.

2021-09-16 01:19 UTC, Piedone requested changes
Továbbra is mergelj devből.

2021-09-16 01:19 UTC, Piedone commented on .gitignore
> +/.idea
Ez mire van?

2021-09-16 01:28 UTC, Piedone commented on Lombiq.OSOCE.sln
> +		.gitignore = .gitignore
A UI Kit-et is frissíteni kell.

2021-09-16 13:54 UTC, barthamark commented on .gitignore
> +/.idea
Rider miatt. :D

2021-09-17 15:07 UTC, barthamark commented on Lombiq.OSOCE.sln
> +		.gitignore = .gitignore
Nem jött létre lock fájl pnpm-től, gondolom mert üres a package.json (nincs benne package), szal így ott nincs teendő.

2021-09-17 21:34 UTC, Piedone approved these changes

2021-09-17 22:00 UTC, merged