OSOE-113: Annotate GitHub repo files with warnings in GitHub workflows
Lombiq/Open-Source-Orchard-Core-Extensions pull request #121
Opened 2022-05-28 21:05 UTC by DAud-IcI

OSOE-113

2022-06-02 22:49 UTC, 0liver commented on .github/workflows/build-and-test.yml
> +          -consoleLoggerParameters:NoSummary `
Trailing whitespace is a backtick killer and may be extremely hard to find.

Here's a long post about the why-s and how-s of avoiding using backticks in the first place. I think [splatting](https://get-powershellblog.blogspot.com/2017/07/bye-bye-backtick-natural-line.html#splattingnote) would be a safe and readable option. What do you think @DAud-IcI and @Piedone?

2022-06-02 22:58 UTC, DAud-IcI commented on .github/workflows/build-and-test.yml
> +          -consoleLoggerParameters:NoSummary `
Most (if not all) modern IDEs eliminate trailing whitespace by default so I'm not concerned about that. However escaping newlines (or any non-printing character) is distasteful and makes me throw up a little every time I'm forced to do it I'll give this splatting a try.

2022-06-02 23:02 UTC, 0liver commented on .github/workflows/build-and-test.yml
> +          -consoleLoggerParameters:NoSummary `
I like the terseness of just using some special character at the end of the line to break commands into many lines, but given the potential problems and thinking about that we want all devs on board with these workflow files, I think that splatting would be a safe approach.

It does make the script look more like code than like a script, but since we're used to reading code all day long anyways, I feel that shouldn't be much of a problem.

2022-06-02 23:15 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +          -consoleLoggerParameters:NoSummary `
I don't have an opinion on this.

2022-06-09 21:32 UTC, Piedone requested changes

2022-06-09 21:32 UTC, Piedone commented on .github/workflows/build-and-test.yml
>          }
Why the swap here and below?

2022-06-09 21:32 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    # wrapping the output to the default buffer width.
May need some line length formatting:

```suggestion
    # First, we globally set test configurations using environment variables. Then acquire the list of all test projects
    # (excluding the two test libraries) and then run each until one fails or all concludes. If a test fails, the output
    # is sanitized from unnecessary diagnostics messages from chromedriver if the output doesn't already contain
    # groupings, then it wraps them in '::group::<project name>'. If there are already groupings, then it is not
    # possible to nest them (https://github.com/actions/runner/issues/802) so that's omitted. The groupings make the
    # output collapsible region on the Actions web UI. Note that we use bash to output the log using bash to avoid pwsh
    # wrapping the output to the default buffer width.
```

2022-06-09 23:02 UTC, DAud-IcI commented on .github/workflows/build-and-test.yml
>          }
Because Windows is the weird one. If we need to add any other OS likely the Linux commands should work.

2022-06-10 20:14 UTC, merged