OSOE-125: Add JavaScript processing functionality to Node Extensions
Lombiq/Open-Source-Orchard-Core-Extensions pull request #124
Opened 2022-05-31 01:50 UTC by 0liver

OSOE-125

2022-05-31 21:13 UTC, Piedone requested changes
The NuGet build shouldn't be affected by this work and thus shouldn't fail (previously under OSOE-92 it didn't fail either). In TC it fails with a build error, and in GitHub Actions with a test (note that it's the Ubuntu build, the Windows one most possibly would fail in the same way as in TC, you can temporarily set `fail-fast: false` to get all builds to run and thus see it, even if one of them fail, see [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast)).

Under [the diff of this branch to dev](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/compare/dev...issue/OSOE-125) you can see the affected NuGet solution changes; apart from adding `Lombiq.NodeJs.Extensions.Samples.NuGet` to the solution, I don't see why any of these are necessary (only talking about the NuGet solution changes, not the root solution).

2022-06-19 14:34 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +        # Map current working directory to drive letter to shorten the absolute path of some deeply nested files.
Note that note yet, but when merging `task/node-extensions` to `dev`, this will need to be added in a DRY was to https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/build-and-test-orchard-core.yml (and other changes in this workflow too).

2022-06-26 18:06 UTC, Piedone requested changes

2022-06-26 18:06 UTC, Piedone commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
I get these diffs here after building a cleaned clone (`lockfileVersion` also changes in UI Testing Toolbox):

![image](https://user-images.githubusercontent.com/1976647/175826194-ca137cca-eaed-4162-84ea-9aab6fbc81aa.png)

2022-06-26 18:06 UTC, Piedone commented on .eslintrc.json
> +{
Why does this needs to be .json?

2022-07-12 11:14 UTC, 0liver commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
This happens when **pnpm@v7** is used. I've refrained from updating to v7 for now, because it brought some breaking changes to how scripts are called, which I'd rather address in a separate issue.

2022-07-12 11:15 UTC, 0liver commented on .eslintrc.json
> +{
It does not need to be .json - I just chose that to aid JSON syntax highlighting in editors. Objections?

2022-07-12 12:36 UTC, Piedone commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Which version should we use, then? Because v7 has been the recommendation under https://lombiq.atlassian.net/wiki/spaces/DEV/pages/1748369460/Setting+up+Node.js+with+Visual+Studio for a while.

2022-07-12 12:40 UTC, Piedone commented on .eslintrc.json
> +{
OK then, but then can't we do the same for stylelintrc?

2022-07-12 12:51 UTC, 0liver commented on .eslintrc.json
> +{
Yes, we will. I will refactor the styles pipeline as part of OSOE-84 to reflect the improvements I was able to make during my work on the JS pipeline. All differences will be addressed there.

2022-07-12 13:02 UTC, 0liver commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Well, pnpm 7.0.0 has only been released [2 months ago](https://github.com/pnpm/pnpm/releases/tag/v7.0.0), so I would not expect us to jump on it right away. Our docs don't mention a version number for **pnpm**, but I can add one for now, until an upgrade from v6 to v7 has been successfully implemented for Node.js Extensions.

2022-07-12 14:08 UTC, Piedone commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Yeah, it was the npm, not pnpm version. However, then please add a pnpm version to the wiki.

2022-07-12 18:10 UTC, 0liver commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Done.

2022-07-12 23:32 UTC, Piedone commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Shouldn't it be a specific version, just to be sure?

2022-07-13 08:02 UTC, 0liver commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
The latest v6 will be fine. There shouldn't be any breaking changes, and I don't mean the semantics that the .NET SDK has introduces for patch version updates 😁

2022-07-13 17:01 UTC, Piedone approved these changes

2022-07-14 22:39 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/Open-Source-Orchard-Core-Extensions/.github/workflows/build-dotnet-with-pnpm.yml@issue/OSOE-125
Keep in mind to change these once you start OSOE-84 again. BTW I think for references within the same caller repo you don't need such branch references, you can just reference the file like we do in the GHA repo (those only need branch references because they're called from other repos).

2022-07-14 22:51 UTC, merged