OSOE-127: Upgrade OSOCE to Orchard Core 1.4
Lombiq/Open-Source-Orchard-Core-Extensions pull request #129
Opened 2022-06-03 13:28 UTC by DemeSzabolcs

2022-06-03 13:53 UTC, DemeSzabolcs commented on src/Lombiq.OSOCE.Web/HostBuilderExtensions.cs
> -using Microsoft.Extensions.Hosting;
This (HostBuilderExtensions.cs) is now in OC: https://github.com/OrchardCMS/OrchardCore/pull/11604/files

2022-06-06 20:31 UTC, DAud-IcI requested changes

2022-06-06 20:31 UTC, sarahelsaig commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +    {
Could you include a comment on why this is necessary?

2022-06-07 00:00 UTC, DemeSzabolcs commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +    {
Sure. So for some reason, after updating the packages, these roles (that I added) were not created during testing by default thus, some tests failed because the homepage was not displaying (instead of it, it displayed a login page, because an anonymous user couldn't view the homepage), so I needed to add them. This same thing already happened to me in another project a while ago.

Should I add a comment about this to the code too?

2022-06-07 00:56 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +    {
Is this a problem during normal setup too or just during testing? 

> Should I add a comment about this to the code too?

Yes, please.

2022-06-07 02:01 UTC, DemeSzabolcs commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +    {
> Is this a problem during normal setup too or just during testing?
It's only present during testing.

2022-06-07 12:04 UTC, merged