OSOE-131: Detect in submodules if there's no PR here
Lombiq/Open-Source-Orchard-Core-Extensions pull request #130
Opened 2022-06-06 09:57 UTC by DAud-IcI

2022-06-07 17:13 UTC, DAud-IcI commented
To reviewer: if "Build and Test / Build and Test (., windows-latest)" is still failing at the "Upload artifacts" step please ignore that. It's a known intermittent problem and it has already been mitigated in #123 so we don't have to worry about it here.

2022-06-07 22:52 UTC, 0liver requested changes

2022-06-07 22:52 UTC, 0liver commented on Readme.md
> +- Open a pull request in this repository for every submodule pull request. That way, static code analysis and complex tests can run. If you forget this a check in the submodule will fail. Once you cr
```suggestion
- Open a pull request in this repository for every submodule pull request. That way, static code analysis and complex tests can run. If you forget to do so, a check in the submodule will fail. Once you've created the PR here, just click "Re-run jobs" in your submodule.
```

2022-06-08 10:37 UTC, 0liver approved these changes

2022-06-08 15:16 UTC, 0liver approved these changes

2022-06-08 18:02 UTC, merged