OSOE-126: Present a nicer test report for GitHub Actions builds
Lombiq/Open-Source-Orchard-Core-Extensions pull request #131
Opened 2022-06-07 14:52 UTC by Luko6

OSOE-126

2022-06-08 14:59 UTC, sarahelsaig commented on .github/workflows/test-report.yml
> +    workflows: ['Build and Test']
```suggestion
    workflows: [Build and Test]
```

[Based on the samples](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) you don't need the apostrophes. Could it be that this workflow is now waiting for a workflow called "'Build and Test'"?

2022-06-08 18:32 UTC, Luko6 commented on .github/workflows/test-report.yml
> +    workflows: ['Build and Test']
It's waiting for the workflow already present yes.

2022-06-08 18:33 UTC, Luko6 commented on .github/workflows/test-report.yml
> +    workflows: ['Build and Test']
It's strating after the whole workflow is done, so after all 4 have either failed or succeeded.

2022-06-09 14:53 UTC, Piedone commented on .github/workflows/test-report.yml
> +      - uses: phoenix-actions/test-reporting@v8
You don't need to put this into a separate workflow. This should rather be a step in build-and-test.

2022-06-09 15:31 UTC, Luko6 commented on .github/workflows/test-report.yml
> +      - uses: phoenix-actions/test-reporting@v8
This documentation should answer why it's seperate.
https://github.com/marketplace/actions/test-reporting#recommended-setup-for-public-repositories

2022-06-09 15:40 UTC, Piedone commented on .github/workflows/test-report.yml
> +      - uses: phoenix-actions/test-reporting@v8
Then add this as a comment there as well.

2022-06-10 09:59 UTC, Piedone commented on .github/workflows/test-report.yml
> +      - uses: phoenix-actions/test-reporting@v8
On a second thought we should rather keep this in the original workflow still. We'll use this in all GitHub Actions solution builds of ours, and it'll be an issue to maintain multiple workflow files instead of one. "Workflows triggered by pull requests from forked repositories are executed with read-only token and therefore can't create check runs." is not really true like this, since workflows do run from forks under PRs to the original repository, you just need to approve it.

2022-06-10 10:01 UTC, Luko6 commented on .github/workflows/test-report.yml
> +      - uses: phoenix-actions/test-reporting@v8
Allright.

2022-06-10 20:41 UTC, Piedone requested changes

2022-06-10 20:41 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    # Test Report
This is redundant with the step name.

2022-06-10 20:41 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    - name: Test Report
Check out whether this runs when tests fail. [See the `if`](https://github.com/marketplace/actions/test-reporting#example).

2022-06-10 20:41 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    - name: Test Report
Add docs about what these Test Results builds are under https://lombiq.atlassian.net/wiki/spaces/DEV/pages/2455732262/Continuous+Integration#GitHub-Actions-overview.

2022-06-10 20:41 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    - name: Test Report
Can we do something about the horizontal scrolling in the tables here, even if there's enough space? 
![image](https://user-images.githubusercontent.com/1976647/173146825-a97ac54b-a384-4408-bcae-b7d2cf9a2c73.png)

2022-06-10 20:41 UTC, Piedone commented
You need to merge from dev.

2022-06-13 08:45 UTC, Luko6 commented on .github/workflows/build-and-test.yml
> +    - name: Test Report
Shouldn't this be a part of the "After Resolve" section? I'll write the text for it though

2022-06-13 10:07 UTC, Luko6 commented on .github/workflows/build-and-test.yml
> +    - name: Test Report
Not really, the container has a max width of 768px (coming from `container-md`), and there is no setting to modify this.

2022-06-13 13:31 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    - name: Test Report
Yeah, good point.

2022-06-13 13:35 UTC, merged