OSOE-150: ⭐ Add PowerShell static code analysis
Lombiq/Open-Source-Orchard-Core-Extensions pull request #149
Opened 2022-07-05 08:10 UTC by DAud-IcI

OSOE-150
- https://github.com/Lombiq/GitHub-Actions/pull/23
- https://github.com/Lombiq/PowerShell-Analyzers/pull/1

2022-07-06 18:46 UTC, Piedone requested changes

2022-07-06 18:46 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-150
Demonstrate an analyzer violation during the GHA build, please.

2022-07-06 18:46 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" Condition="'$(GITHUB_ENV)' == ''" />
Why do we need this, and why the distinction with `GITHUB_ENV`?

2022-07-06 19:14 UTC, DAud-IcI commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-150
I have already linked it in the issue description.

2022-07-06 19:15 UTC, sarahelsaig commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" Condition="'$(GITHUB_ENV)' == ''" />
When you run the build in GitHub Actions, it should use the workflow command output format, whereas this uses the MSBuild output format. Unfortunately GH doesn't automatically convert those into error annotations.

2022-07-06 20:06 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-150
In the PR description, but I see, thanks.

2022-07-06 20:09 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" Condition="'$(GITHUB_ENV)' == ''" />
Do we actually need a separate PS analyzer step in the GH workflow if we have MSBuild integration?

2022-07-10 20:40 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" Condition="'$(GITHUB_ENV)' == ''" />
If you suppress the logs like we do in the GH workflow (with `-verbosity:quiet`) then also suppresses any stdout and stderr outputs from the script called by `<Exec>`. This means we can only emit MSBuild errors, because MSBuild treats those differently, but we can't emit GH workflow commands such as `::error::My message.`. When I try to use the MSBuild commands in the GH actions, they display on the console output but aren't interpreted as errors so not great.

2022-07-10 21:13 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" Condition="'$(GITHUB_ENV)' == ''" />
Shouldn't we emit MSBuild errors, then? Since this targets file integrates PS analysis with the build, it could also integrate with the output there, like ESLint and Stylelint. I.e. use warnings by default, which will be turned into errors when we build in CI.

2022-07-10 21:38 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" Condition="'$(GITHUB_ENV)' == ''" />
Yeah, I was also considering that. I will look into a way to turn MSBuild errors into GH errors in `dotnet-build`. Then we can stick with just one error type per tooling.

2022-07-11 00:13 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" Condition="'$(GITHUB_ENV)' == ''" />
Works:
![image](https://user-images.githubusercontent.com/4007293/178167729-1318e6a4-86b2-456b-aaa7-cb24435df01e.png)
![image](https://user-images.githubusercontent.com/4007293/178167712-a92cb5c0-b1a4-4880-96e9-26f62e6001cd.png)

2022-07-11 20:32 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" Condition="'$(GITHUB_ENV)' == ''" />
Looks awesome!

2022-07-12 12:28 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-150
I get these errors locally but the GHA build passes:

![image](https://user-images.githubusercontent.com/1976647/178489687-8322d5a1-c1b3-4238-8706-d234f4f5aabe.png)

BTW shouldn't these be warnings locally instead?

2022-07-12 14:12 UTC, DAud-IcI commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-150
No, becuase if you return warnings for the items, but still emit a nonzero exit code that's pointless. But if the analyzer returns zero then it won't emit the warnings a second time on incremental build (because the timestamp would be updated) which would be confusing.

2022-07-19 22:17 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-150
These errors are still there. And again, shouldn't this cause the GHA build to fail too?

2022-07-19 22:41 UTC, DAud-IcI commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-150
I'm not getting any of these locally. I'm pretty sure these hint to version differences between Windows PowerShell and PowerShell 7. The "in this version" hints to that. Also I remember, that `curl` was an alias in Windows PowerShell (which is dumb, they shouldn't have done that), but it's not an alias in PS7. GHA is only using `pwsh`, becuase it's available, that's why the builds don't fail.

Both of the affected files are in the _Lombiq.GitHub.Actions_ repo, where all scripts are only invoked with `pwsh`. (and `curl` is the actual cURL program) I don't think we need to worry about how those scripts behave in older versions since we won't ever use those.

2022-07-19 23:20 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-150
Hmm, it should have been a version issue. I installed the latest PS 7 and it works now.

2022-07-19 23:20 UTC, Piedone approved these changes

2022-07-20 15:33 UTC, Piedone approved these changes

2022-07-21 14:56 UTC, Piedone approved these changes

2022-07-21 22:21 UTC, Piedone approved these changes

2022-07-21 23:53 UTC, merged