OSOE-46: Use WebApplicationFactory directly instead of running the tested app with the dotnet CLI
Lombiq/Open-Source-Orchard-Core-Extensions pull request #156
Opened 2022-07-18 20:07 UTC by dministro

OSOE-46

2022-09-27 22:03 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <InternalsVisibleTo Include="Lombiq.OSOCE.NuGet.Tests.UI" />
Do we actually need this in OSOCE? Since no non-public type will be accessed by the tests.

2022-09-27 22:18 UTC, DAud-IcI requested changes

2022-09-27 22:18 UTC, DAud-IcI commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Program.cs
> +builder.Services.Add(new ServiceDescriptor(configuration.GetType(), configuration));
Isn't this the same as `builder.Services.AddSingleton(configuration);`? Same [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/050499fc48c31b04e0d4b70e676e8edd8860e640/src/Lombiq.OSOCE.Web/Program.cs#L14).

2022-09-27 22:18 UTC, DAud-IcI commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Program.cs
> +#pragma warning restore CA1050
I think using `[SuppressMessage]` would be cleaner for suppressing. Same [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/050499fc48c31b04e0d4b70e676e8edd8860e640/src/Lombiq.OSOCE.Web/Program.cs#L24-L27).

2022-09-27 22:18 UTC, DAud-IcI commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Lombiq.OSOCE.NuGet.Tests.UI.csproj
> +    <PackageReference Include="Lombiq.Tests.UI" Version="3.5.1-alpha.osoe-46.5" />
Are these actually necessary? I think these packages are already referenced indirectly through `..\..\src\Lombiq.OSOCE.NuGet.Web\Lombiq.OSOCE.NuGet.Web.csproj`.

2022-09-29 16:32 UTC, dministro commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Lombiq.OSOCE.NuGet.Tests.UI.csproj
> +    <PackageReference Include="Lombiq.Tests.UI" Version="3.5.1-alpha.osoe-46.5" />
Only the `*.Tests.UI` packages are added here. Module and module sample packages are added to `Lombiq.OSOCE.NuGet.Web.csproj`. So yes, these are neccessary.

2022-10-14 09:13 UTC, merged