OSOE-158: Evaluate using the Check Spelling action
Lombiq/Open-Source-Orchard-Core-Extensions pull request #157
Opened 2022-07-19 12:49 UTC by Luko6

OSOE-158

2022-09-14 16:07 UTC, Piedone requested changes

2022-09-14 16:07 UTC, Piedone commented on .github/actions/spelling/excludes.txt
> +.jpg$
As mentioned under the issues, common configuration should come from the action in the GitHub Actions repo. This and patterns.txt is the same here and there, as well as they seem that they can centrally incorporate what Utility Scripts uses. Perhaps expect.txt too?

2022-09-14 16:07 UTC, Piedone commented on .github/workflows/check-spelling.yml
> +name: Check Spelling
The issue requests running this from an existing workflow. Is that not feasible for some reason?

2022-09-14 16:07 UTC, Piedone commented on Readme.md
> +- If the feature is user-facing, also add UI test extension method(s) with the [Lombiq UI Testing Toolbox for Orchard Core](https://github.com/Lombiq/UI-Testing-Toolbox/) that assert on some importan
Did it really not find any issues in submodules?

2022-09-14 16:07 UTC, Piedone commented on .github/workflows/check-spelling.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/check-spelling.yml@issue/OSOE-158
Test Results now show up under this workflow, despite being connected to the build workflow: 
![image](https://user-images.githubusercontent.com/1976647/190200114-16503e34-fb58-45e3-af68-01e20cae8908.png)

2022-09-15 09:32 UTC, Luko6 commented on .github/workflows/check-spelling.yml
> +name: Check Spelling
It is. Somehow I can't read, misunderstood and separated them at the end.

2022-09-25 23:02 UTC, Piedone requested changes
See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/157#discussion_r970990337.

2022-09-26 18:26 UTC, Piedone requested changes
Merge, please.

2022-09-27 10:52 UTC, Piedone commented on Readme.md
> +- If the feature is user-facing, also add UI test extension method(s) with the [Lombiq UI Testing Toolbox for Orchard Core](https://github.com/Lombiq/UI-Testing-Toolbox/) that assert on some importan
Please reply.

2022-10-04 22:45 UTC, Piedone commented on Readme.md
> +- If the feature is user-facing, also add UI test extension method(s) with the [Lombiq UI Testing Toolbox for Orchard Core](https://github.com/Lombiq/UI-Testing-Toolbox/) that assert on some importan
@Luko6 This is still unanswered.

2022-10-04 22:49 UTC, Piedone requested changes
Again: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/157#discussion_r970990337

2022-10-05 09:45 UTC, Luko6 commented on Readme.md
> +- If the feature is user-facing, also add UI test extension method(s) with the [Lombiq UI Testing Toolbox for Orchard Core](https://github.com/Lombiq/UI-Testing-Toolbox/) that assert on some importan
It didn't.

2022-10-05 14:04 UTC, Piedone commented on Readme.md
> +- If the feature is user-facing, also add UI test extension method(s) with the [Lombiq UI Testing Toolbox for Orchard Core](https://github.com/Lombiq/UI-Testing-Toolbox/) that assert on some importan
And because there aren't any, what I'd find improbable, or it's not working?

2022-10-20 14:20 UTC, Piedone approved these changes

2022-10-20 14:52 UTC, Piedone requested changes

2022-10-20 14:52 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +
Something you introduced under https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/220 and affects this too: The Test Results checks are now not under the build but validate PR. See here https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3289830410/jobs/5421850530 and here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3289830260/jobs/5421850207.

2022-10-21 14:59 UTC, Piedone approved these changes

2022-10-24 13:40 UTC, Piedone approved these changes

2022-10-24 21:34 UTC, Piedone approved these changes

2022-10-24 22:06 UTC, merged