OSOE-128: ⭐ Add Markdown linting
Lombiq/Open-Source-Orchard-Core-Extensions pull request #158
Opened 2022-07-19 15:22 UTC by DAud-IcI

OSOE-128

2022-07-21 22:14 UTC, Piedone requested changes
TC build is failing.

2022-07-21 22:14 UTC, Piedone commented on Lombiq.OSOCE.sln
> -		{9DFD40DB-217C-4012-83FB-18F3AEBC3DD6} = {6ED7E28F-0556-471C-8AD1-5BB0941411DD}
What's this change?

2022-07-21 22:14 UTC, Piedone commented on NuGetTest/Readme.md
> -
This is coming from https://orcharddojo.net/orchard-resources/CoreLibrary/ContributionGuideLines. I don't mind changing the convention but the docs should be updated too, and then the Dojo Library as well (keep in mind that that's not GitHub-compatible Markdown but the basic one).

2022-07-21 22:14 UTC, Piedone commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
Why is `*` better?

2022-07-21 22:14 UTC, Piedone commented on License.md
> +THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
Change this in the template repo too.

2022-07-22 00:49 UTC, DAud-IcI commented on Lombiq.OSOCE.sln
> -		{9DFD40DB-217C-4012-83FB-18F3AEBC3DD6} = {6ED7E28F-0556-471C-8AD1-5BB0941411DD}
probably merge problem

2022-07-22 00:52 UTC, DAud-IcI commented
> TC build is failing.

It seemed to me that TC build was failing on previous `task/node-extensions` issues as well so I thought it's a known quantity. If you check the build log, it's complaining about Lombiq.Gulp.Extensions which is removed in this branch.

>Step 2/9: Restore NodeJS Packages (.NET)
>  Target files not found for pattern "\src\Utilities\Lombiq.*.Extensions\Lombiq.Gulp.Extensions.csproj"
>  Step Restore NodeJS Packages (.NET) failed with unexpected error
>  Error message: Step Restore NodeJS Packages (.NET) failed with unexpected error

2022-07-22 00:54 UTC, DAud-IcI commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
It isn't better or worse. The linter only cares about consistent symbol usage within the document.

2022-07-22 12:15 UTC, Piedone commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
I think using asterisk for em is more common in the Markdown world but please do check and let's settle on the one indeed more common.

2022-07-22 12:16 UTC, Piedone commented
Indeed.

2022-07-22 12:22 UTC, 0liver commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
But then, just maybe, let's not use asterisk as the list item prefix.

2022-07-22 21:50 UTC, DAud-IcI commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
This makes me said because I exclusively use underscore, but so be it.
At least markdownlint-cli can autofix it using `markdownlint --fix FileName.md`...

2022-07-22 21:54 UTC, Piedone commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
Did you want to write "This makes me sad" or "This makes me Saig"? Please be specific.

2022-07-22 21:57 UTC, 0liver commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
Where is the source for `*` being the preferred character for emphasis in the Markdown world? I also like underscore more for that - I even recall **fixing** some MD files from `*` to `_` in the past!

2022-07-22 21:59 UTC, DAud-IcI commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
Apparently it makes me tired.   😂ᶻᶻᶻᶻᶻᶻ

2022-07-22 22:20 UTC, DAud-IcI commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
If it's up for debate, then I'd go for `_em_` and `**bold**`, because plenty of apps use `_em_` and `*bold*` (including Teams, Slack, YouTube, etc) so at least it would be familiar.

2022-07-22 22:27 UTC, Piedone commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
I'm OK with that, however, did you check what's common in the Markdown world as I asked?

2022-07-22 22:43 UTC, DAud-IcI commented on NuGetTest/Readme.md
> -
> but we recommend [Notepad++](https://notepad-plus-plus.org/)

People still use Notepad++ ? 😱

2022-07-22 22:54 UTC, DAud-IcI commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
I didn't find any consensus. If it helps, the first result when you search `markdown style guide emphasis` in Google is this style guide that agrees with me.

2022-07-22 23:05 UTC, DAud-IcI commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
I found no consensus. Different style MD guides offer wildly different suggestions on the topic, or not cover it at all (e.g. Google's Markdown style guide is silent on the topic of emphasis formatting, while GitHub's just list both options).

Apparently a justification for using asterisk for both, is that different markdown parsers handle underscores inside the word (like `A_cat_meow`) inconsistently. I don't consider this a very valid concern though, because you shouldn't do that in the first place. Without a community consensus, I think we should just poll internally.

2022-07-23 08:56 UTC, Piedone commented on NuGetTest/Readme.md
> -
Yes, because of the money back guarantee.

2022-07-23 08:58 UTC, Piedone commented on Readme.md
> +  - [Lombiq.Npm.Targets](https://github.com/Lombiq/NPM-Targets): Provides automatic NPM package installation and a custom NPM command execution before building a .NET project. This way it is possible
Sounds good. While we're at it you can also include bullet points.

2022-07-23 17:50 UTC, DAud-IcI commented on NuGetTest/Readme.md
> -
I thought Code has the same? Also grow a pair (of extra arms) and start using nvim!

2022-07-24 23:37 UTC, Piedone requested changes

2022-07-24 23:37 UTC, Piedone commented on NuGetTest/Lombiq.OSOCE.NuGet.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lombiq.Analyzers.PowerShell.PackageReference", "..\tools\Lombiq.Analyzers.PowerShell\TestSolutions\Lombiq.Analyzers.PowerShell.PackageReference\Lo
![image](https://user-images.githubusercontent.com/1976647/180669703-818e8bf2-9f0b-4763-a17e-f36d6b04d150.png)

2022-07-24 23:37 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
![image](https://user-images.githubusercontent.com/1976647/180670088-42bb799e-4738-42c0-b2f8-709be2258981.png)

2022-07-24 23:37 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +  <Import Project="..\..\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets" />
Merge `dev` to `task/node-extensions` first so these don't show up as diffs.

2022-07-24 23:37 UTC, Piedone commented on Lombiq.OSOCE.sln
> +EndProject
Previously we had this:

![image](https://user-images.githubusercontent.com/1976647/180670492-a9be99c6-af96-4526-a8cd-4363e276a8a4.png)

But now:

![image](https://user-images.githubusercontent.com/1976647/180670512-b88f9430-4eb8-4471-a062-8e8c6e8db6d4.png)

I guess it's a bad merge also causing the above error.

2022-07-25 01:09 UTC, DAud-IcI commented on NuGetTest/Lombiq.OSOCE.NuGet.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lombiq.Analyzers.PowerShell.PackageReference", "..\tools\Lombiq.Analyzers.PowerShell\TestSolutions\Lombiq.Analyzers.PowerShell.PackageReference\Lo
I don't see how, `Lombiq.Analyzers.PowerShell` is not part of _Lombiq.OSOCE.NuGet.sln_.

2022-07-25 12:05 UTC, Piedone commented on NuGetTest/Lombiq.OSOCE.NuGet.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lombiq.Analyzers.PowerShell.PackageReference", "..\tools\Lombiq.Analyzers.PowerShell\TestSolutions\Lombiq.Analyzers.PowerShell.PackageReference\Lo
Sorry, this is only for the root solution. I forgot to remove this comment.

2022-07-26 21:12 UTC, Piedone requested changes

2022-07-26 21:12 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
`Lombiq.HelpfulExtensions.Tests.UI` and `Lombiq.HelpfulLibraries.Cli` are in the root of the solution now, and there's an empty Modules folder.

2022-07-26 21:17 UTC, 0liver commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
Merging the solution files is a nightmare.

I'm close to the point where I'll write a solution file clean-up tool that will enforce a strict order of all projects, folders, and what not so that they'll become more easily mergable!

2022-07-26 21:20 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
Good, frustration is a good inspiration :).

2022-07-26 21:24 UTC, DAud-IcI commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
Yes. please do. Maybe something that parses two sln files so git can use it as a diff tool.

2022-07-26 21:28 UTC, Piedone commented on License.md
> +- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
With a fresh clone (but interestingly, not with a cleaned repo) I see these warnings:

```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Warning	MD049	emphasis-style: Emphasis style should be consistent. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md049	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\ScssTargets.md	38		
Warning	(ESLint) import/no-unresolved	Unable to resolve path to module 'markdownlint'.	Lombiq.NodeJs.Extensions JavaScript Content Files	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions\scripts\markdown-to-msbuild.js	2	Web Code Analysis	Active
Warning	(ESLint) import/no-unresolved	Unable to resolve path to module 'textlint'.	Lombiq.NodeJs.Extensions JavaScript Content Files	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions\scripts\markdown-to-msbuild.js	5	Web Code Analysis	Active
Warning	max-comma	This sentence exceeds the maximum count of comma. Maximum is 4.	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Readme.md	111		
Warning	MD004	ul-style: Unordered list style. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md004	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\License.md	9		
Warning	MD004	ul-style: Unordered list style. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md004	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\License.md	11		
Warning	MD004	ul-style: Unordered list style. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md004	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\License.md	13		
Warning	MD009	no-trailing-spaces: Trailing spaces. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md009	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\CopyAssets.md	5		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\Browsersync.md	3		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\Browsersync.md	4		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\CopyAssets.md	3		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\CopyAssets.md	4		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\JsTargets.md	3		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\JsTargets.md	4		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\JsTargets.md	19		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\JsTargets.md	47		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\JsTargets.md	60		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\ScssTargets.md	3		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\ScssTargets.md	4		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Docs\ScssTargets.md	34		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Readme.md	3		
Warning	MD012	no-multiple-blanks: Multiple consecutive blank lines. An automatic fix is available with markdownlint-cli. Rule information: https://github.com/DavidAnson/markdownlint/blob/v0.26.1/doc/Rules.md#md012	Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis	E:\ShortPath\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.Gulp.Extensions\Readme.md	4		
Warning	MD012	no-multip [...]

2022-07-26 21:57 UTC, DAud-IcI commented on License.md
> +- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
This was supposed to be an easy, relaxing issue 😭😭😭😭😭

2022-07-26 21:59 UTC, 0liver commented on License.md
> +- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Sending you a rocket!

2022-07-26 22:19 UTC, DAud-IcI commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
I've moved those to where they should be. But I see a lot of other projects are missing (eg everything else from _tests/Modules_). Is that because Lombiq.Gulp.Extensions got removed?

2022-07-26 22:23 UTC, 0liver commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
That's because they directly or indirectly reference Gulp.Extensions - so I removed them from the solution for now. I'm working on reverting this in OSOE-84 right now 😃

2022-07-26 22:54 UTC, DAud-IcI commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
Cool, thanks for the clarification!

2022-07-26 22:58 UTC, 0liver commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
I'm really sorry for the hassle.

2022-07-26 23:01 UTC, Piedone commented on License.md
> +- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
These are simple issues in Gulp Extensions. Perhaps the real problem is actually that the solution contains that project still?

2022-07-26 23:03 UTC, 0liver commented on License.md
> +- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
The solution should not contain it anymore, but your file system still might.

2022-07-26 23:04 UTC, 0liver commented on License.md
> +- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Although I thought I removed the GE submodule in OSOE-125 😕

2022-07-26 23:05 UTC, Piedone commented on License.md
> +- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Argh, yes, the folder is indeed there (since git checkout doesn't remove folders of removed submodules). This is not an issue, then.

2022-07-26 23:58 UTC, DAud-IcI commented on License.md
> +- Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Yeah, that keeps happening whenever you switch between branches using different submodules. I wish the client would automatically remove the difference instead of just leaving them there as an unstaged directory...

2022-07-27 00:20 UTC, Piedone approved these changes

2022-07-27 12:41 UTC, 0liver requested changes

2022-07-27 12:41 UTC, 0liver commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.Analyzers.PowerShell", "tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.csproj", "{D00D1636-6898-
For reference, this change of the project type GUID is an update done automatically by VS - from an "old" one to the "new" and current one. See [this issue](https://github.com/dotnet/project-system/issues/3079) for more details on the topic.

2022-07-27 12:41 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/package.json
> +}
Since this was a painful experience for you, do you think it'd make sense to have NE generate such a _package.json_ file in case one does not exist? You know, automate all things™. Or would that be too invasive?

2022-07-27 12:41 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Readme.md
> +This project and its containing solution is used to test the NuGet packages of our Open-Source Orchard Core Extensions. To learn about each extension and library involved, check out the [root readme]
Our .NET documentation analyzer recently advised me not to end a sentence with a `!`. At first I thought that's stupid, but now I feel that there's something to it - the `!` does give an urge to the sentence that is not really necessary:
```suggestion
This project and its containing solution are used to test the NuGet packages of our Open-Source Orchard Core Extensions. To learn about each extension and library involved, check out the [root readme](../../../Readme.md).
```

2022-07-27 12:41 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <MarkdownAnalysis>solution</MarkdownAnalysis>
I feel that this should be named more clearly; maybe:

```suggestion
    <MarkdownAnalysisMode>solution</MarkdownAnalysisMode>
```

I'm also missing a connection to the Node.js Extensions package this is coming from - would you agree to add a prefix to it as I've done for other configuration options like `NodeJsExtensionsScriptsSourceFolder` or `NodeJsExtensionsGlobalESLintConfigurationDirectory` (see [docs](https://github.com/Lombiq/NodeJs-Extensions/blob/dev/Lombiq.NodeJs.Extensions/Docs/JavaScript.md))?

2022-07-27 12:41 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <ExecDotnetPrebuildCommand>false</ExecDotnetPrebuildCommand>
This does feel hacky. The only reason we need this is because otherwise the NE build will fail, right?

Seems like we should fall back to a no-op where a part of the pipeline is not applicable.

If you agree, please add a todo to OSOE-84 to remove this hack once fixed.

2022-07-27 14:25 UTC, DAud-IcI commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/package.json
> +}
I think it's a good idea. Should I create an issue for it?

2022-07-27 14:29 UTC, DAud-IcI commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Readme.md
> +This project and its containing solution is used to test the NuGet packages of our Open-Source Orchard Core Extensions. To learn about each extension and library involved, check out the [root readme]
This is a call-to-action type sentence, so an exclamation point seems appropriate. What .NET documentation analyzer are you referring to? Do you have some link to the specific advice against exclamations?

2022-07-27 14:30 UTC, sarahelsaig commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <MarkdownAnalysis>solution</MarkdownAnalysis>
I agree, no property name should be short enough to fit in a single line! xD

2022-07-27 15:28 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/package.json
> +}
No, I'll add it to OSOE-84 (for now).

2022-07-27 15:34 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Readme.md
> +This project and its containing solution is used to test the NuGet packages of our Open-Source Orchard Core Extensions. To learn about each extension and library involved, check out the [root readme]
Turns out the rule is a bit more relaxed: [Documentation text should end with a period](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1629.md).

Also, even this is a kind of call to action, it's also a suggestion, as in "See https://bla.bla for more details." No exclamation mark there, either.

2022-07-27 15:35 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <MarkdownAnalysis>solution</MarkdownAnalysis>
I feel bad now:

![image](https://user-images.githubusercontent.com/164360/181288890-fe317f10-5266-4eb5-a961-362dd7e4b11c.png)

Do you think my suggestion is inappropriate?

2022-07-27 15:55 UTC, DAud-IcI commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <MarkdownAnalysis>solution</MarkdownAnalysis>
Nah, I'm being facetious.

2022-07-27 18:41 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <MarkdownAnalysis>solution</MarkdownAnalysis>
You keep using words that I've either barely or never heard of before. I'm impressed. Where did you learn English?

2022-07-27 19:38 UTC, DAud-IcI commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <MarkdownAnalysis>solution</MarkdownAnalysis>
In high school so that's not where the credit goes. :D I just pick stuff up because I mostly read in English.

2022-07-27 20:28 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <MarkdownAnalysis>solution</MarkdownAnalysis>
Oh, reading! 😁 Unfortunately, that's one of the things I cannot seem to find time for at the current stage of my life.

2022-07-27 22:42 UTC, 0liver approved these changes

2022-07-28 22:45 UTC, merged