WALMA-19: Extend UI Testing Toolbox to support custom admin url prefixes
Lombiq/Open-Source-Orchard-Core-Extensions pull request #185
Opened 2022-08-21 17:30 UTC by Psichorex

WALMA-19

2022-08-22 11:25 UTC, Luko6 approved these changes

2022-08-22 16:54 UTC, Piedone approved these changes

2022-08-23 23:05 UTC, Piedone approved these changes

2022-08-25 20:49 UTC, Piedone requested changes

2022-08-25 20:49 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/CustomAdminPrefixTests.cs
> +public class CustomAdminPrefixTests : UITestBase
Awesome that you added this!

2022-08-25 20:49 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/CustomAdminPrefixTests.cs
> +                configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false;
Open [an Orchard bug report](https://github.com/OrchardCMS/OrchardCore/issues/new?assignees=&labels=bug&template=bug_report.md&title=) about this and link it here.

2022-08-26 09:43 UTC, Psichorex commented on test/Lombiq.OSOCE.Tests.UI/Tests/CustomAdminPrefixTests.cs
> +                configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false;
https://github.com/OrchardCMS/OrchardCore/issues/12271

2022-08-29 06:57 UTC, Piedone approved these changes

2022-08-29 11:59 UTC, Piedone approved these changes

2022-08-29 16:16 UTC, Piedone approved these changes

2022-08-29 17:57 UTC, merged