NEST-302: Idle tenant shutdown
Lombiq/Open-Source-Orchard-Core-Extensions pull request #189
Opened 2022-08-24 19:41 UTC by Psichorex

NEST-302

2022-08-25 16:12 UTC, wAsnk requested changes

2022-08-25 16:12 UTC, wAsnk commented on src/Lombiq.OSOCE.Web/appsettings.Development.json
> +   }
Is this really needed?

2022-08-25 16:12 UTC, wAsnk commented on test/Lombiq.OSOCE.Tests.UI/Tests/IdleTenantsTests.cs
> +                System.Threading.Thread.Sleep(71000);
Please put a comment here explaining why is this needed exactly.

2022-08-25 21:05 UTC, Psichorex commented on src/Lombiq.OSOCE.Web/appsettings.Development.json
> +   }
Not needed.

2022-08-27 23:25 UTC, wAsnk commented
Some of the build and tests are failing :(

2022-08-30 20:48 UTC, wAsnk approved these changes

2022-08-30 20:49 UTC, merged