NEST-282: FeaturesGuard
Lombiq/Open-Source-Orchard-Core-Extensions pull request #200
Opened 2022-09-09 14:31 UTC by porgabi

NEST-282

2022-09-20 14:39 UTC, wAsnk requested changes
Please read the [OSOE readme.](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions#adding-a-new-extension-or-significant-new-features). Especially the "If the feature is user-facing, also add UI test extension method(s)..." part and "If the project is published on NuGet" part.

2022-09-28 15:44 UTC, wAsnk requested changes

2022-09-28 15:44 UTC, wAsnk commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
What's the problem with Html validation?

2022-09-28 15:56 UTC, porgabi commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
OC's login page contains an error.

2022-09-28 15:58 UTC, wAsnk commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
Is that a known error? If so link that here please or make a comment explaining why is this needed, and on the other test as well.

2022-09-28 16:26 UTC, porgabi commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
The password visibility toggle button has no text inside it, which is invalid:
![image](https://user-images.githubusercontent.com/51411356/192834177-530dea7c-4702-45f0-8cbc-99eb03eff74a.png)

I'll add a comment to explain why it's disabled.

Also, there's a seemingly relevant OC issue already: https://github.com/OrchardCMS/OrchardCore/issues/12271

2022-09-28 17:01 UTC, wAsnk commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
But it is just weird because other tests have HTML validation enabled.

2022-09-28 17:27 UTC, porgabi commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
I think none of the other tests in the solution/s log in manually. In this case, it's manual because it's logging into a tenant, which I think is not possible with `SignInDirectlyAsync()` and its variants. I tried it just now and it's only logging into the default tenant.

2022-09-28 17:29 UTC, wAsnk commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
If it's only this page and this error then you can omit checking this error similar to the one in BehaviorUIKitShowcaseTests.cs:

```csharp
configuration => configuration.HtmlValidationConfiguration.AssertHtmlValidationResultAsync =
                async validationResult =>
                {
                    var errors = (await validationResult.GetErrorsAsync())
                        .Where(error => !error.ContainsOrdinalIgnoreCase("Prefer to use the native <button> element"));
                    errors.ShouldBeEmpty();
                });
```

2022-09-28 17:39 UTC, porgabi commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
Turns out there are a few more 😃
![image](https://user-images.githubusercontent.com/51411356/192851334-b15f41e5-1b1e-49a7-b55f-532d920d3159.png)

2022-09-28 17:56 UTC, wAsnk commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
What, this many errors on that login page?

2022-09-28 17:57 UTC, wAsnk commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
Okay, then link that issue in the comment and let's go :D

2022-09-28 18:00 UTC, porgabi commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorMultiTenancyTests.cs
> +            configuration.HtmlValidationConfiguration.RunHtmlValidationAssertionOnAllPageChanges = false);
This many on the dashboard page, I think the login page only has the toggle button that's problematic.

2022-09-28 18:52 UTC, wAsnk approved these changes

2022-09-28 19:56 UTC, merged