OSOE-92: Publish Lombiq.VueJs on NuGet
Lombiq/Open-Source-Orchard-Core-Extensions pull request #203
Opened 2022-09-18 18:48 UTC by DAud-IcI

OSOE-92

2022-10-20 09:15 UTC, 0liver requested changes

2022-10-20 09:15 UTC, 0liver commented on Lombiq.OSOCE.sln
> +EndProject
While I would love our solution file to be ordered (in whatever way), it currently is not, and merging this with OSOE-84 will be a right-out pain.

Please use the same locations for the project and build configuration blocks as does the `dev` solution. I've already done that in [this commit](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/225/commits/de4512a655c5c64b2c7f028daa85160d4dcd2dec) - so you might just re-use that.

2022-10-20 12:48 UTC, DAud-IcI commented on Lombiq.OSOCE.sln
> +EndProject
I've reset this file to its state in `issue/OSOE-84` (excluding the changes in the solution items).

2022-10-20 12:54 UTC, 0liver commented on Lombiq.OSOCE.sln
> +EndProject
I'm not sure your build will pass with that, since the other projects that aren't part of the solution in `task/node-extensions` still reference Gulp Extensions. Which is **not** part of the repo anymore.

2022-10-20 12:57 UTC, DAud-IcI commented on Lombiq.OSOCE.sln
> +EndProject
In this case, can we just stick what I had here for this PR?
During merge you can simply choose yours, because it's a superset of mine. No merge needed.

2022-10-20 13:00 UTC, 0liver commented on Lombiq.OSOCE.sln
> +EndProject
If we merge it into OSOE-84, you're correct. OK then.

2022-10-28 08:25 UTC, 0liver requested changes

2022-10-28 08:25 UTC, 0liver commented on .eslintrc.json
> +{
Delete this file, please.

2022-10-29 21:46 UTC, DAud-IcI commented on .eslintrc.json
> +{
yes
![image](https://user-images.githubusercontent.com/4007293/198853592-297ebfa2-307e-4436-99fc-c9dbaf5e2337.png)

2022-10-31 11:49 UTC, 0liver requested changes

2022-10-31 11:49 UTC, 0liver commented on .eslintrc.json
> +{
No:

![image](https://user-images.githubusercontent.com/164360/199001126-ed84969b-e836-4902-9c3b-85d633bd4706.png)

2022-10-31 11:55 UTC, 0liver approved these changes

2022-10-31 21:26 UTC, merged