OSOE-388: Release all projects
Lombiq/Open-Source-Orchard-Core-Extensions pull request #232
Opened 2022-10-14 15:38 UTC by Piedone

OSOE-388
Fixes #216

2022-10-14 17:17 UTC, dministro requested changes
Lombiq.Tests was not released.
https://github.com/Lombiq/UI-Testing-Toolbox/blob/5773111eac4447090de29c454972ba0d162c1f42/Lombiq.Tests.UI/Lombiq.Tests.UI.csproj#L91

2022-10-14 17:19 UTC, dministro requested changes

2022-10-14 17:19 UTC, dministro commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests/Lombiq.OSOCE.NuGet.Tests.csproj
>      <PackageReference Include="Lombiq.Tests" Version="2.0.1-alpha.osoe-46.1" />
Lombiq.Tests was not released

2022-10-14 19:59 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests/Lombiq.OSOCE.NuGet.Tests.csproj
>      <PackageReference Include="Lombiq.Tests" Version="2.0.1-alpha.osoe-46.1" />
Eh.

2022-10-16 19:58 UTC, dministro approved these changes

2022-10-16 19:58 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.UIKit" Version="2.3.1" />
Note: the latest release was 2.1.0.
https://www.nuget.org/packages/Lombiq.UIKit/2.1.0#versions-body-tab

2022-10-16 19:59 UTC, merged

2022-10-16 21:05 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.UIKit" Version="2.3.1" />
Oops. I perhaps got mixed up with the alpha releases (which BTW shouldn't be 2.2.x).