OSOE-353: Add duplicate SQL query detector in Lombiq.UITestingToolbox
Lombiq/Open-Source-Orchard-Core-Extensions pull request #247
Opened 2022-10-24 06:10 UTC by dministro

OSOE-353

2022-10-25 20:21 UTC, Piedone requested changes

2022-10-25 20:21 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/RetrievalDataTablesTests.cs
> +            browser,
You didn't do it but the file and class names are different. Rename the file.

2022-10-25 20:21 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorChartJsTests.cs
> +                configuration.CounterConfiguration.Running.DbReaderReadPerNavigationThreshold = 70;
This and `BehaviorDataTablesTests` should rather specify thresholds for specific pages, see https://github.com/Lombiq/UI-Testing-Toolbox/pull/216#discussion_r1004911693.

2022-11-02 19:29 UTC, Piedone commented
On the next commit, UI testing will break if you don't merge from `dev` beforehand.

2022-11-02 19:58 UTC, dministro commented
> On the next commit, UI testing will break if you don't merge from `dev` beforehand.

#258 , Thank you.

2023-10-25 00:32 UTC, Piedone approved these changes

2025-07-09 21:31 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
There is a breaking change in Yesql, which is a transient dependency. The `ISession.DetachAll` and `ISession.ResetAsync` were introduced.
Pointless and risky to upgrade to 2.1.7 until the submodules are on 2.1.0.

This reverts the change introduced by 73983ef2e70eec272c92b3016268db8d0e0abacf.

2025-07-09 21:31 UTC, dministro commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
There is a breaking change in Yesql, which is a transient dependency. The `ISession.DetachAll` and `ISession.ResetAsync` were introduced.
Pointless and risky to upgrade to 2.1.7 until the submodules are on 2.1.0.

This reverts the change introduced by 73983ef2e70eec272c92b3016268db8d0e0abacf.

2025-07-09 21:46 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
What is the breaking change that you're referring to? I assume not the introduction of two new methods, since that's not breaking.

We keep the Web projects on the latest OC, and submodules on .0 for a good reason: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions?tab=readme-ov-file#net-and-orchard-core-version-support-policy

2025-07-09 21:57 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
Introducing new methods on an interface which is not implemented in a dependency which is references a different version is a breaking change and results in a `TypeLoadException`.
See: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/16155545840/job/45611756550
![0-AfterPageChange](https://github.com/user-attachments/assets/8df1acfc-1d2e-4bc6-af72-7298d450134e)

I can uprade to 2.1.7 in `Lombiq.Tests.UI`, but it is a big impact, because I have to upgrade OC modules in referenced modules, so ...
What is the expectation? keep `Lombiq.Tests.UI` on 2.1.0 or upgrade to 2.1.7(under a different PR because of the impact)?

2025-07-10 00:07 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
Why do you need to touch anything related to this in the first place? What's at the root of all of this?

2025-07-10 04:30 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
The `TypeLoadException` (see: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/247#discussion_r2196071215).

2025-07-10 12:20 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
I see the comment two comments up :). My question is, what's before that? Link to the code that requires you to change the OC version.

2025-07-10 14:50 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
Here is the `ISession` implementation(`Lombiq.Tests.UI.Services.Counters.SessionProbe`) in UITT: https://github.com/Lombiq/UI-Testing-Toolbox/blob/a547aab779d95de56bd0fe78d3de8658bc25044f/Lombiq.Tests.UI/Services/Counters/SessionProbe.cs#L12

2025-07-10 15:16 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
I see. Keep the Web projects on 2.1.7. Update UITT to 2.1.7 too, but add it as a temporary exception here: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/build-and-test-orchard-core.yml#L211 With a comment that explains why it's there, that includes the phrase "Orchard Core upgrade".

2025-07-10 15:31 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
I've tried it already, and it ends in a version downgrade compile time warning (/warningaserror) because of HL (if I remember correctly, it's on 2.1.0)

I'll give it a try. If the version downgrade warning is still present, should I upgrade OC dependencies in HL(and so on) or keep the web project on 2.1.6?

2025-07-10 15:58 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
Since UITT is used is many projects where the Web project is on 2.1.7, downgrading that to 2.1.6 is not a viable option.

I checked, and only `Lombiq.HelpfulExtensions.Tests.UI` is affected, where the current `OrchardCore.ContentManagement.Abstractions` that breaks this isn't actually needed and can be removed.

2025-07-10 16:01 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
Sorry, the reference is needed but can be changed to 2.1.7 in the same manner.

2025-07-10 21:39 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
After upgrading OC modules to 2.1.7 in HL:
```
Warning As Error: Detected package downgrade: OrchardCore.DisplayManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme.Core -> OrchardCore.Media 2.1.0 -> OrchardCore.ContentManagement.Display 2.1.7 -> OrchardCore.DisplayManagement (>= 2.1.7) 
 Lombiq.BaseTheme.Core -> OrchardCore.DisplayManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.ContentManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme.Core -> OrchardCore.Media 2.1.0 -> OrchardCore.ContentManagement.GraphQL 2.1.7 -> OrchardCore.ContentManagement (>= 2.1.7) 
 Lombiq.BaseTheme.Core -> OrchardCore.ContentManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.ResourceManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme.Core -> Lombiq.HelpfulExtensions -> OrchardCore.Contents 2.1.7 -> OrchardCore.ResourceManagement (>= 2.1.7) 
 Lombiq.BaseTheme.Core -> OrchardCore.ResourceManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.Module.Targets from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.MediaTheme.Bridge -> Lombiq.HelpfulExtensions -> OrchardCore.Module.Targets (>= 2.1.7) 
 Lombiq.Hosting.MediaTheme.Bridge -> OrchardCore.Module.Targets (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.DisplayManagement.Abstractions from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.MediaTheme.Bridge -> OrchardCore.Media 2.1.0 -> OrchardCore.Apis.GraphQL.Abstractions 2.1.7 -> OrchardCore.DisplayManagement.Abstractions (>= 2.1.7) 
 Lombiq.Hosting.MediaTheme.Bridge -> OrchardCore.DisplayManagement.Abstractions (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.ResourceManagement.Abstractions from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.MediaTheme.Bridge -> OrchardCore.Media 2.1.0 -> OrchardCore.DisplayManagement.Liquid 2.1.7 -> OrchardCore.ResourceManagement.Abstractions (>= 2.1.7) 
 Lombiq.Hosting.MediaTheme.Bridge -> OrchardCore.ResourceManagement.Abstractions (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.Deployment.Abstractions from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.MediaTheme.Bridge -> Lombiq.HelpfulExtensions -> OrchardCore.Contents 2.1.7 -> OrchardCore.Deployment.Abstractions (>= 2.1.7) 
 Lombiq.Hosting.MediaTheme.Bridge -> OrchardCore.Deployment.Abstractions (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.Recipes.Abstractions from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.MediaTheme.Bridge -> Lombiq.HelpfulExtensions -> OrchardCore.Contents 2.1.7 -> OrchardCore.Recipes.Abstractions (>= 2.1.7) 
 Lombiq.Hosting.MediaTheme.Bridge -> OrchardCore.Recipes.Abstractions (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.Module.Targets from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.Tenants.EmailQuotaManagement -> Lombiq.HelpfulExtensions -> OrchardCore.Module.Targets (>= 2.1.7) 
 Lombiq.Hosting.Tenants.EmailQuotaManagement -> OrchardCore.Module.Targets (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.Infrastructure.Abstractions from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.Tenants.EmailQuotaManagement -> OrchardCore.Email 2.1.0 -> OrchardCore.Admin.Abstractions 2.1.7 -> OrchardCore.Infrastructure.Abstractions (>= 2.1.7) 
 Lombiq.Hosting.Tenants.EmailQuotaManagement -> OrchardCore.Infrastructure.Abstractions (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.DisplayManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.Tenants.EmailQuotaManagement -> OrchardCore.Email 2.1.0 -> OrchardCore.Navigation.Core 2.1.7 -> OrchardCore.DisplayManagement (>= 2.1.7) 
 Lombiq.Hosting.Tenants.EmailQuotaManagement -> OrchardCore.DisplayManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.ResourceManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Hosting.Tenants.EmailQuotaManagement -> Lombiq.HelpfulLibraries.OrchardCore -> OrchardCore.Markdown 2.1.7 -> OrchardCore.ResourceManagement (>= 2.1.7) 
 Lombiq.Hosting.Tenants.EmailQuotaManagement -> OrchardCore.ResourceManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.Workflows from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Privacy.Samples -> Lombiq.HelpfulExtensions -> OrchardCore.Workflows (>= 2.1.7) 
 Lombiq.Privacy.Samples -> OrchardCore.Workflows (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.Module.Targets from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.Privacy.Samples -> Lombiq.HelpfulExtensions -> OrchardCore.Module.Targets (>= 2.1.7) 
 Lombiq.Privacy.Samples -> OrchardCore.Module.Targets (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.DisplayManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme -> Lombiq.BaseTheme.Core -> OrchardCore.Media 2.1.0 -> OrchardCore.ContentManagement.Display 2.1.7 -> OrchardCore.DisplayManagement (>= 2.1.7) 
 Lombiq.BaseTheme -> Lombiq.BaseTheme.Core -> OrchardCore.DisplayManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.ContentManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme -> Lombiq.BaseTheme.Core -> OrchardCore.Media 2.1.0 -> OrchardCore.ContentManagement.GraphQL 2.1.7 -> OrchardCore.ContentManagement (>= 2.1.7) 
 Lombiq.BaseTheme -> Lombiq.BaseTheme.Core -> OrchardCore.ContentManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.ResourceManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme -> Lombiq.BaseTheme.Core -> Lombiq.HelpfulExtensions -> OrchardCore.Contents 2.1.7 -> OrchardCore.ResourceManagement (>= 2.1.7) 
 Lombiq.BaseTheme -> Lombiq.BaseTheme.Core -> OrchardCore.ResourceManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.DisplayManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme.Native -> Lombiq.BaseTheme.Core -> OrchardCore.Media 2.1.0 -> OrchardCore.ContentManagement.Display 2.1.7 -> OrchardCore.DisplayManagement (>= 2.1.7) 
 Lombiq.BaseTheme.Native -> Lombiq.BaseTheme.Core -> OrchardCore.DisplayManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.ContentManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme.Native -> Lombiq.BaseTheme.Core -> OrchardCore.Media 2.1.0 -> OrchardCore.ContentManagement.GraphQL 2.1.7 -> OrchardCore.ContentManagement (>= 2.1.7) 
 Lombiq.BaseTheme.Native -> Lombiq.BaseTheme.Core -> OrchardCore.ContentManagement (>= 2.1.0)
Warning As Error: Detected package downgrade: OrchardCore.ResourceManagement from 2.1.7 to 2.1.0. Reference the package directly from the project to select a different version. 
 Lombiq.BaseTheme.Native -> Lombiq.BaseTheme.Core -> Lombiq.HelpfulExtensions -> OrchardCore.Conte [...]

2025-07-10 21:53 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
You don't need to update Helpful Libraries. The only other affected project is `Lombiq.HelpfulExtensions.Tests.UI`.

2025-07-10 21:57 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
Adding `OrchardCore.ContentManagement.Abstractions` 2.1.7 as a direct reference to HL looks better, but I can't see the impact.

2025-07-10 21:59 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
Domino effect: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/16206856185/job/45759029743?pr=247

2025-07-10 22:01 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
> You don't need to update Helpful Libraries. The only other affected project is `Lombiq.HelpfulExtensions.Tests.UI`.

Sorry, it was a typo. I mean HE

2025-07-10 22:02 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
But that's not necessary. Why would you do that?

2025-07-10 22:08 UTC, dministro commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
After removing `OrchardCore.ContentManagement.Abstractions` direct reference from `Lombiq.HelpfulExtensions.csproj`, the dotnet consolidation is still failing.

https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/16206960865/job/45759363976?pr=247
```
----------------------------
OrchardCore.ContentFields
----------------------------
Lombiq.ChartJs.Samples - 2.1.0
Lombiq.ContentEditors - 2.1.0
Lombiq.DataTables.Samples - 2.1.0
Lombiq.HelpfulExtensions - 2.1.0
Lombiq.HelpfulLibraries.OrchardCore - 2.1.0
Lombiq.HelpfulLibraries.Samples - 2.1.0
Lombiq.JsonEditor - 2.1.0
Lombiq.TrainingDemo - 2.1.0
Lombiq.VueJs.Samples - 2.1.0
Lombiq.Walkthroughs - 2.1.0
Lombiq.Tests.UI - 2.1.7
----------------------------
OrchardCore.Abstractions
----------------------------
Lombiq.HelpfulLibraries.OrchardCore - 2.1.0
Lombiq.Hosting.Tenants.IdleTenantManagement - 2.1.0
Lombiq.SetupExtensions - 2.1.0
Lombiq.Tests.UI.Shortcuts - 2.1.0
Lombiq.Tests.UI - 2.1.7
----------------------------
OrchardCore.ContentManagement.Abstractions
----------------------------
Lombiq.HelpfulLibraries.OrchardCore - 2.1.0
Lombiq.OrchardCoreApiClient - 2.1.0
Lombiq.HelpfulExtensions.Tests.UI - 2.1.7
```

2025-07-10 22:15 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <OrchardCoreVersion>2.1.6</OrchardCoreVersion>
I elaborated what I suggest doing above, what is not this. Please just try that. (Not remove but change the HE reference, exclude the two projects from the consolidation.)

2025-07-15 20:41 UTC, Piedone approved these changes

2025-07-15 20:46 UTC, Piedone approved these changes

2025-07-16 01:08 UTC, Piedone requested changes
Release a NuGet alpha and update the NuGetTest solution with it: https://lombiq.atlassian.net/wiki/spaces/DEV/pages/786857987/Managing+releases+of+open-source+projects

2025-07-27 15:38 UTC, Piedone commented
Somebody else will do this.

2025-07-27 15:38 UTC, closed without merging