OSOE-53: Followup with Oliver's feedback
Lombiq/Open-Source-Orchard-Core-Extensions pull request #26
Opened 2021-12-07 14:55 UTC by DAud-IcI

OSOE-53
- https://github.com/Lombiq/Helpful-Libraries/pull/96

2021-12-07 16:46 UTC, Piedone approved these changes

2021-12-07 22:10 UTC, 0liver requested changes

2021-12-07 22:10 UTC, 0liver commented on src/Modules/Lombiq.OSOCE.Samples/Controllers/TypedRouteController.cs
> +        public ActionResult TypedRouteSample(string text, int number) => Content($"{text}: {number}");
Why did you drop the other two example parameters? Did you conclude they don't add any value?

2021-12-07 22:10 UTC, 0liver commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +    </EmbeddedResource>
This looks interesting. Why do we embed the `_ViewImports` view here, and not the `Index` view for example? And what does this `EmbeddedResource Update` do? I couldn't find that out in a quick search.

2021-12-07 22:10 UTC, 0liver commented on src/Modules/Lombiq.OSOCE.Samples/Startup.cs
> +    }
I assume this class is here as a placeholder for future configuration? Or is this always needed?

2021-12-07 22:10 UTC, 0liver commented on src/Modules/Lombiq.OSOCE.Samples/Startup.cs
> +            IApplicationBuilder builder,
[Looks like](https://ci.lombiq.com/buildConfiguration/OrchardExtensions_OSOCE_Developer_PullAndBuild/875606?showRootCauses=false&expandBuildProblemsSection=true&expandBuildChangesSection=true) this parameter should be called `app`.

2021-12-07 22:15 UTC, DAud-IcI commented on src/Modules/Lombiq.OSOCE.Samples/Controllers/TypedRouteController.cs
> +        public ActionResult TypedRouteSample(string text, int number) => Content($"{text}: {number}");
I didn't drop it. I think you are confusing this new method with the one in the unit test?

2021-12-07 22:17 UTC, DAud-IcI commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +    </EmbeddedResource>
By mistake. This is not necessary.

2021-12-07 22:18 UTC, 0liver commented on src/Modules/Lombiq.OSOCE.Samples/Controllers/TypedRouteController.cs
> +        public ActionResult TypedRouteSample(string text, int number) => Content($"{text}: {number}");
Yes. I thought you moved it here. OK then.

2021-12-07 22:20 UTC, DAud-IcI commented on src/Modules/Lombiq.OSOCE.Samples/Startup.cs
> +    }
You always need the class, but the overrides are not needed. Removed. I've just added this module five minutes before going to the orchard meeting to do the demo so it was done a bit hastily.

2021-12-07 22:21 UTC, 0liver commented on src/Modules/Lombiq.OSOCE.Samples/Startup.cs
> +    }
Good to know, thanks.

2021-12-08 21:21 UTC, 0liver approved these changes
That was a smooth ride. 🏎

2021-12-08 22:54 UTC, 0liver approved these changes

2021-12-08 23:52 UTC, Piedone requested changes

2021-12-08 23:52 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.BasicOrchardFeaturesTests.recipe.json
> +        "Lombiq.OSOCE.Samples"
This should rather be in Lombiq.OSOCE.Tests.recipe.

2021-12-08 23:52 UTC, Piedone commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +  <Import Project="..\..\Utilities\Lombiq.Gulp.Extensions\Lombiq.Gulp.Extensions.targets" />
Do we really need these?

2021-12-08 23:52 UTC, Piedone commented on src/Modules/Lombiq.OSOCE.Samples/Manifest.cs
> +    Name = "Lombiq.OSOCE.Samples",
This is a great idea! However, let's add it to HL instead. It's already a pretty sizable module so even if we start adding samples just for it, this will be a large module, no need to mix in other things (and it would also help with refactoring). You can just add a fourth project there.

2021-12-08 23:53 UTC, Piedone commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Razor">
Did you follow https://lombiq.atlassian.net/wiki/spaces/DEV/pages/19496967/Creating+a+new+Visual+Studio+project+or+solution?

2021-12-09 00:01 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.BasicOrchardFeaturesTests.recipe.json
> +        "Lombiq.OSOCE.Samples"
Why, isn't that only for UI tests? The content in this module so far is for demonstration and anyway it would be useful to have samples out of the box. Or am I missing some consideration?

2021-12-09 00:06 UTC, DAud-IcI commented on src/Modules/Lombiq.OSOCE.Samples/Manifest.cs
> +    Name = "Lombiq.OSOCE.Samples",
I think I can keep this empty as a placeholder and only move the `TypedRouteController` to the new _Lombiq.HelpfulLibraries.Samples_ module, do you agree?

2021-12-09 00:11 UTC, Piedone commented on src/Modules/Lombiq.OSOCE.Samples/Manifest.cs
> +    Name = "Lombiq.OSOCE.Samples",
Sounds good.

2021-12-09 00:12 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.BasicOrchardFeaturesTests.recipe.json
> +        "Lombiq.OSOCE.Samples"
That's only for UI tests, but this one is also just for a subset of UI tests. We don't have any other central setup recipe.

2021-12-09 00:16 UTC, DAud-IcI commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Razor">
Yeah, excluding the readme because that doesn't seem to be relevant here, or is it?
By the way do we plan on having a custom lombiq codegen template to trim down the boilerplate in the module csproj?

2021-12-09 00:29 UTC, Piedone commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Razor">
Good then, it isn't.

Good idea, seems like one for https://lombiq.atlassian.net/wiki/spaces/DEV/pages/2466480231/Bring+your+own+open-source+idea!

2021-12-09 00:44 UTC, DAud-IcI commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Razor">
Ok, I will do that. Just wanted to check first if there was already an issue for it.

2021-12-09 19:05 UTC, Piedone approved these changes

2021-12-09 19:55 UTC, Piedone approved these changes

2021-12-09 20:10 UTC, merged