NEST-358: Finishing FeaturesGuard
Lombiq/Open-Source-Orchard-Core-Extensions pull request #260
Opened 2022-10-29 14:17 UTC by porgabi

NEST-358

2022-10-30 20:54 UTC, Piedone requested changes

2022-10-30 20:54 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.Hosting.Tenants.Management" Version="2.3.3-alpha.6.nest-358" />
These should've been `2.3.2-alpha.6.nest-358`.

2022-10-30 20:54 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/appsettings.json
> +    "Lombiq_Hosting_Tenants_FeaturesGuard": {
Update the root Readme reference to the non-existing `Lombiq.Hosting.MultiTenancy.Tenants`.

2022-11-02 19:29 UTC, Piedone commented
On the next commit, UI testing will break if you don't merge from `dev` beforehand.

2022-11-02 22:16 UTC, Piedone requested changes
See: https://github.com/Lombiq/Hosting-Tenants/pull/41#discussion_r1012341787

2022-11-03 16:13 UTC, porgabi commented
![image](https://user-images.githubusercontent.com/51411356/199774338-9f802238-fa6e-45ae-8743-ab536cf987f8.png)

2022-11-03 17:31 UTC, Piedone requested changes

2022-11-03 17:31 UTC, Piedone commented on src/Lombiq.OSOCE.Web/appsettings.json
> +            "OrchardCore.Twitter": "Lombiq.UIKit, Lombiq.ChartJs"
This is supposed to enable Twitter when UIKit or ChartJs are enabled, right? Because this isn't happening for me when just running the app normally: I have Features Guard enabled, then enable UIKit, then enable ChartJs. Twitter is still disabled.

2022-11-04 10:31 UTC, porgabi commented on src/Lombiq.OSOCE.Web/appsettings.json
> +            "OrchardCore.Twitter": "Lombiq.UIKit, Lombiq.ChartJs"
Yes. Are you sure you tried doing this on a user tenant? Seems to work for me, I tried the following just now:
1. Set up user tenant with SaaS recipe.
2. Enable Features Guard.
3. Enable ChartJs.
4. Observe Twitter being already enabled when features list reloads.

2022-11-04 16:15 UTC, Piedone commented on src/Lombiq.OSOCE.Web/appsettings.json
> +            "OrchardCore.Twitter": "Lombiq.UIKit, Lombiq.ChartJs"
Oh right, it was the Default tenant, so scratch that. It works properly on user tenants.

2022-11-06 23:28 UTC, Piedone requested changes

2022-11-06 23:28 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +                ["OrchardCore.Twitter"] = new List<string> { "Lombiq.UIKit", "Lombiq.ChartJs" },
Same for the NuGet solution.

```suggestion
                ["OrchardCore.Twitter"] = new[] { "Lombiq.UIKit", "Lombiq.ChartJs" },
```

2022-11-07 17:14 UTC, merged