OSOE-392: Upgrade to Orchard Core 1.5
Lombiq/Open-Source-Orchard-Core-Extensions pull request #264
Opened 2022-11-05 15:43 UTC by MZole

[OSOE-392](https://lombiq.atlassian.net/browse/OSOE-392)

2022-11-05 22:03 UTC, Piedone commented
Use more descriptive commit messages than "Updating Lombiq.UITestingToolbox".

2022-11-08 16:31 UTC, Piedone requested changes

2022-11-08 16:31 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-392
There are no changes in the `build-and-test-orchard-core` workflow, so this and below are not needed.

2022-11-08 16:31 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      spell-check-this: Lombiq/GitHub-Actions@issue/OSOE-392
Isn't just changing the branch reference in `uses` sufficient?

2022-11-08 16:31 UTC, Piedone commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
Why are these necessary?

2022-11-08 21:08 UTC, MZole commented on .github/workflows/build-and-test.yml
> +      spell-check-this: Lombiq/GitHub-Actions@issue/OSOE-392
I remembered correctly, it is not enough, as you can see with this [run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3423154830/jobs/5701423599), here I was using the issue branch.

2022-11-08 21:17 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      spell-check-this: Lombiq/GitHub-Actions@issue/OSOE-392
But after merging the GHA PR, this won't be needed, right?

BTW please document [here](https://github.com/Lombiq/GitHub-Actions/blob/dev/Docs/Workflows.md#spelling-workflow) how you need this during development when updating the dictionary.

2022-11-08 21:23 UTC, MZole commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
With the `Nlog` update (to 5.0) the defaults of `keepFileOpen` from false and `concurrentWrites` from true changed to the opposites and this was the root of the problem with the `IdleTenantTests`, I was getting error messages that the log file is being used by another process. (although it was only a problem on Windows hence why it was a lot more time-consuming then I would like it to be to realise that it was the problem)
The defaults changed due to the improving the performance of logging huge files, but I don't think this would benefit us much since we don't use that deep level of logging.

2022-11-08 21:50 UTC, MZole commented on .github/workflows/build-and-test.yml
> +      spell-check-this: Lombiq/GitHub-Actions@issue/OSOE-392
Yes, after the merge this won't be needed.

This is already 'kind of' there, but I will edit that section of `spell-check-this` to make this clearer.

2022-11-08 21:54 UTC, Piedone commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
Can't we set this from the environment [like this](https://github.com/Lombiq/UI-Testing-Toolbox/blob/dev/Lombiq.Tests.UI.Samples/UITestBase.cs#L73) instead? Related: https://github.com/Lombiq/UI-Testing-Toolbox/issues/206

2022-11-08 21:55 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      spell-check-this: Lombiq/GitHub-Actions@issue/OSOE-392
Thanks!

2022-11-09 00:50 UTC, MZole commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
We could only do this I think if we had our Nlog configuration set up from an `appsettings.json` file but we are using an `NLog.config` one. But also, don't we only use this config file for testing?

2022-11-09 00:54 UTC, Piedone commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
While this app is not deployed, the config is not just used for UI testing but also local development. And we'll need to figure this out now in relation to the UI Testing Toolbox, since it'll be necessary for all other apps using it too.

2022-11-09 00:54 UTC, Piedone commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
If we can move the NLog config to appsettings then let's do that.

2022-11-09 14:11 UTC, MZole commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
Turns out we can't use it from appsettings, because the `OrchardCore.Logging.NLog` requires the `NLog.config` file, and if I delete the file, I get a `FileNotFoundException` because of the line `builder.Host.UseNLogHost();` in _program.cs_ . So `OrchardCore.Logging.NLog` is also configured to use the .config file.

2022-11-09 16:03 UTC, Piedone commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
We could have our own extension method instead of `UseNLogHost()`, but let's just try to address this: How about adding using appsettings as a second, additional config source? So just these two properties are set from there.

2022-11-09 17:53 UTC, snakefoot commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
I recommend not reverting to `keepFileOpen="false" concurrentWrites="true"`. Instead fix the applications / tests that requires exclusive log-file-access to work. Forexample read log-files like this (And not using `File.ReadAllText()`):
```c#
using (var f = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
using (var s = new StreamReader(f))
{
    fileContent = s.ReadToEnd();
}
```
`keepFileOpen="false"` opens the door to lots of bad things. Forexample that Windows Malware Scanner suddenly can take over the file-handle, and suddenly the actual application fails to perform logging (and if not using `async="true"` then get completely stuck). See also: https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#filetarget-keepfileopen--true-by-default

2022-11-09 18:09 UTC, Piedone commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
Thank you for chiming in! Very valuable info. @MZole, please look into these. My suspicion is that we have the issue here: https://github.com/Lombiq/UI-Testing-Toolbox/blob/07885bbadf05a71d9d11c9856b2a7f7d649228b9/Lombiq.Tests.UI/Services/OrchardCoreInstance.cs#L132 We do exactly `File.ReadAllTextAsync()`.

Out of sheer curiosity, how did you find this convo, @snakefoot? I see you're an active contributor of NLog.

2022-11-09 18:19 UTC, snakefoot commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
@Piedone I regularly search github for issues about "NLog" to ensure everyone has a good time :), especially when it comes to bringing people over the major version bump.

2022-11-09 18:25 UTC, Piedone commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    keepFileOpen="false" concurrentWrites="true" />
That's awesome, thank you!

2022-11-09 20:19 UTC, snakefoot commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    layout="${longdate}|${orchard-tenant-name}|${aspnet-traceidentifier}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception:format=ToString,Sta
Notice that NLog.Extensions.Logging changes from `EventId.Id` + `EventId.Name` to `EventId` + `EventName`. So better to use `${event-properties:item=EventId}`. See also https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlogextensionslogging-changes-capture-of-eventid

2022-11-09 22:04 UTC, Piedone commented on src/Lombiq.OSOCE.Web/NLog.config
> +                    layout="${longdate}|${orchard-tenant-name}|${aspnet-traceidentifier}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception:format=ToString,Sta
Thank you for this too! @MZole please also open an Orchard Core issue for this, because this needs to be fixed in OC too.

2022-11-10 01:08 UTC, Piedone requested changes

2022-11-10 01:08 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-457
This and below shouldn't be needed.

2022-11-10 10:42 UTC, MZole commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-457
This is from the latest dev merge, probably not intended [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/.github/workflows/build-and-test.yml#L14).

2022-11-10 13:40 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-457
I see. Oliver fixed them.

2022-11-11 01:01 UTC, Piedone approved these changes

2022-12-06 00:42 UTC, Piedone requested changes

2022-12-06 00:42 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Lombiq.OSOCE.NuGet.Tests.UI.csproj
> +    <PackageReference Include="Lombiq.Tests.UI" Version="4.0.2-alpha.14.osoe-392" />
Publish a new alpha of `Lombiq.Tests.UI` with the updates so we can see it working with NuGetTest.

2022-12-06 18:19 UTC, Piedone approved these changes

2022-12-06 20:44 UTC, merged