FeatureCodeGeneration UI test can be flaky with StaleElementReferenceException in Lombiq.HelpfulExtensions
Lombiq/Open-Source-Orchard-Core-Extensions pull request #356
Opened 2023-01-09 19:51 UTC by Piedone

Also fixing similar flakyness in Privacy.

2023-01-10 09:50 UTC, dministro approved these changes

2023-01-11 21:37 UTC, dministro requested changes

2023-01-11 21:37 UTC, dministro commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Lombiq.OSOCE.NuGet.Tests.UI.csproj
>      <PackageReference Include="Lombiq.Tests.UI" Version="5.0.1-alpha.1.osoe-464" />
I think we need a prerelease of `Lombiq.Tests.UI` because of the changes related to `RetryIfStaleOrFailAsync`. Without this fix the NuGet tests could fail with `StaleElementReferenceException` which can confusing for other developers.

2023-01-11 21:43 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Lombiq.OSOCE.NuGet.Tests.UI.csproj
>      <PackageReference Include="Lombiq.Tests.UI" Version="5.0.1-alpha.1.osoe-464" />
Indeed, but allow me not to do that, since as part of https://lombiq.atlassian.net/browse/OSOE-532 I'll do a release of everything. Releasing an alpha of UITT for this necessitates an update to most of the other projects, which in light of a proper release is a waste of time.

2023-01-11 22:08 UTC, dministro approved these changes

2023-01-11 22:25 UTC, merged