OSOE-47: Open-source Data Tables
Lombiq/Open-Source-Orchard-Core-Extensions pull request #39
Opened 2022-01-19 19:19 UTC by DAud-IcI

OSOE-47

2022-01-24 15:43 UTC, Piedone approved these changes

2022-02-06 20:45 UTC, Piedone approved these changes

2022-02-07 21:07 UTC, Piedone approved these changes

2022-02-09 20:08 UTC, Piedone approved these changes

2022-02-16 23:20 UTC, Piedone requested changes
Test is failing.

2022-02-16 23:20 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Lombiq.OSOCE.Tests.UI.csproj
> +      <TargetFramework>net5.0</TargetFramework>
Let's keep everything 3.1 until we switch to 6.0 (also, 3.1 will remain supported longer than 5.0).

2022-02-16 23:20 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/RetrievalDataTablesTests.cs
> +                    await context.TestDataTableIndexBasedProviderAsync();
While it's good to have granularity, if necessary, all of this should be available as a single method too, and used here.

2022-02-16 23:20 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/UITestBase.cs
> +        protected override Size MobileBrowserSize { get; } = new(414, 736);
Why exactly this resolution?

2022-02-16 23:27 UTC, DAud-IcI commented on test/Lombiq.OSOCE.Tests.UI/UITestBase.cs
> +        protected override Size MobileBrowserSize { get; } = new(414, 736);
I copied it from SNOW. Actually this value doesn't need to be overridden so I can remove it.

2022-02-20 20:00 UTC, Piedone approved these changes

2022-02-21 14:31 UTC, Piedone approved these changes

2022-02-21 18:22 UTC, Piedone approved these changes

2022-02-21 19:24 UTC, Piedone approved these changes

2022-02-21 21:34 UTC, merged