OSOE-523: Optimize spell-checking dictionary files across projects
Lombiq/Open-Source-Orchard-Core-Extensions pull request #397
Opened 2023-02-07 19:44 UTC by BenedekFarkas

Fixes #346

2023-02-19 20:07 UTC, Piedone requested changes

2023-02-19 20:07 UTC, Piedone commented on .github/actions/spelling/excludes.txt
> +test/Lombiq\.UITestingToolbox/Lombiq\.Tests\.UI/Constants/CommonDisplayResolutions\.cs
Can this and the below UploadingTestFileDOCX excludes instead be added to the UI Testing Toolbox?

2023-02-20 18:49 UTC, BenedekFarkas commented on .github/actions/spelling/excludes.txt
> +test/Lombiq\.UITestingToolbox/Lombiq\.Tests\.UI/Constants/CommonDisplayResolutions\.cs
Not with the current feature set. I've built custom functionality for a similar purpose (= the "Merge ..." steps in the spelling action), but that works because the common configuration is in LGHA. In this case the parent project would need to discover that its submodules have some spelling configuration to "merge" and apply like that.

I thought about that, but I don't think it's worth the effort, because there's no built-in mechanism at all for reusing configuration files (other flat dictionary files). The next step would be for UITT to do its own spell checking and just be excluded in OSOCE's, but since our recommendation is that OSOCE submodules should be excluded from spell checking in other projects.

2023-02-20 19:00 UTC, Piedone commented on .github/actions/spelling/excludes.txt
> +test/Lombiq\.UITestingToolbox/Lombiq\.Tests\.UI/Constants/CommonDisplayResolutions\.cs
OK then.

2023-02-22 22:43 UTC, Piedone approved these changes

2023-02-23 14:24 UTC, Piedone approved these changes

2023-02-23 15:58 UTC, merged