OSOE-49: Replace Windows-only code in UI Testing Toolbox and Fix Lombiq.Analyzers on Linux
Lombiq/Open-Source-Orchard-Core-Extensions pull request #41
Opened 2022-01-22 23:19 UTC by DAud-IcI

OSOE-49

2022-05-13 19:46 UTC, Piedone commented
Merge from dev.

2022-05-13 19:58 UTC, DAud-IcI commented
ok, merged

2022-05-13 20:16 UTC, Piedone commented
And fix the build errors too :).

2022-05-13 23:54 UTC, Piedone requested changes

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +    branches: [ dev ]
We sometimes open longer-living feature branches with multiple PRs to them, so we don't need this restriction.

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +name: Pull Request - Code Analysis and Unit Tests
```suggestion
name: Pull Request - Build and Test
```

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +    name: Build & Test
Just to be in line with TC:

```suggestion
    name: Build and Test
```

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        dotnet build src/Utilities/Lombiq.Npm.Targets/Lombiq.Npm.Targets.csproj
Wouldn't project references to NPM Targets, just as to Gulp Extensions, fix this too?

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        dotnet build Lombiq.OSOCE.sln --no-incremental -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
`--no-incremental` shouldn't be needed on a single-use build agent.

Also, better to build like we'd run it in prod: `--configuration Release`. I don't really understand why there's a second Release build after this.

And why quiet?

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +    - name: Set up SQL Server via Docker
Wow, nice!

2022-05-13 23:54 UTC, Piedone commented on .github/TestConfig.json
> +  "Lombiq_Tests_UI": {
It would be a bit nicer to keep these configs in environment variables, see `TestConfigurationManager` (you can make more code configs configurable from the env, just add more `TestConfigurationManager` calls with defaults keeping the current defaults).

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +    - name: Unit Tests
Since these are also UI tests:

```suggestion
    - name: Tests
```

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        grep SUCCESS .ui_test_result
Make failure dumps available as an artifact: https://github.com/OrchardCMS/OrchardCore/pull/11194/files#diff-1153a5676594ad20522a7686e7e94a258891fe87611bafcd10ec0f3943c219b8

2022-05-13 23:54 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
What on earth is happening here? :D Also, you can filter tests from within `dotnet test` too: https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest

2022-05-14 04:19 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +          grep 'error MSB3073: The command "npm run dotnet-postclean --if-present"' analysis.log >/dev/null 2>/dev/null && echo npm retry && continue
We run a Gulp Extensions build first in TC. Might be needed.

2022-05-14 10:06 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        dotnet build src/Utilities/Lombiq.Npm.Targets/Lombiq.Npm.Targets.csproj
Nope, because even this didn't fix it. The affected projects already reference Lombiq.Npm.Targets so I have no idea why it's like this.

2022-05-14 10:11 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        dotnet build Lombiq.OSOCE.sln --no-incremental -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
For some reason I thought it has to be in Debug. If it can be Release, then indeed there is no need for a second build.

It's quiet to eliminate irrelevant outputs. Really, all we care about is if there is some build error and if there isn't then there is no point outputting [this garbage information](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/6430683041?check_suite_focus=true#step:6:12).

2022-05-14 10:19 UTC, 0liver commented on .github/workflows/analyze_and_test.yml
> +        dotnet build Lombiq.OSOCE.sln --no-incremental -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
Good point about the `quiet` verbosity level. We might want to adapt that as the default in [our GitHub publish action](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/publish.yml#L12), as well.

2022-05-14 10:23 UTC, DAud-IcI commented on .github/TestConfig.json
> +  "Lombiq_Tests_UI": {
Could you explain why you think that would be nicer? I think adding some complicated variable like `$Lombiq_Tests_UI__SqlServerDatabaseConfiguration__ConnectionStringTemplate` would be less readable and it would be even worse if we had more settings, though just 2 is borderline.

2022-05-14 10:42 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
That filter is not helpful because of the GitHub specific tricks that go on here. The goal is to place every test into a separate collapsible section within the step. See the generated script when you run the code up to this line in bash:
```sh
$ dotnet sln list |
>         grep '.Tests.' |
>         grep -v 'Lombiq.Tests.UI.csproj' |
>         grep -v 'Lombiq.Tests.csproj' |
>         sed -e 's/\\/\//g' -e '$atrue' -e 's/\(.*\)/echo "::group::\1" \&\&\ndotnet test -c Release --no-restore --no-build '"'\\1'"' \&\&\necho "::endgroup::" \&\&/'

echo "::group::src/Modules/Lombiq.TrainingDemo/Tests/Lombiq.TrainingDemo.Tests/Lombiq.TrainingDemo.Tests.csproj" &&
dotnet test -c Release --no-restore --no-build 'src/Modules/Lombiq.TrainingDemo/Tests/Lombiq.TrainingDemo.Tests/Lombiq.TrainingDemo.Tests.csproj' &&
echo "::endgroup::" &&
echo "::group::test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.Shortcuts/Lombiq.Tests.UI.Shortcuts.csproj" &&
dotnet test -c Release --no-restore --no-build 'test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.Shortcuts/Lombiq.Tests.UI.Shortcuts.csproj' &&
echo "::endgroup::" &&
echo "::group::test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.AppExtensions/Lombiq.Tests.UI.AppExtensions.csproj" &&
dotnet test -c Release --no-restore --no-build 'test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.AppExtensions/Lombiq.Tests.UI.AppExtensions.csproj' &&
echo "::endgroup::" &&
echo "::group::test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.Samples/Lombiq.Tests.UI.Samples.csproj" &&
dotnet test -c Release --no-restore --no-build 'test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.Samples/Lombiq.Tests.UI.Samples.csproj' &&
echo "::endgroup::" &&
echo "::group::src/Libraries/Lombiq.HelpfulLibraries/Lombiq.HelpfulLibraries.Tests/Lombiq.HelpfulLibraries.Tests.csproj" &&
dotnet test -c Release --no-restore --no-build 'src/Libraries/Lombiq.HelpfulLibraries/Lombiq.HelpfulLibraries.Tests/Lombiq.HelpfulLibraries.Tests.csproj' &&
echo "::endgroup::" &&
echo "::group::src/Modules/Lombiq.DataTables/Lombiq.DataTables/Tests/Lombiq.DataTables.Tests/Lombiq.DataTables.Tests.csproj" &&
dotnet test -c Release --no-restore --no-build 'src/Modules/Lombiq.DataTables/Lombiq.DataTables/Tests/Lombiq.DataTables.Tests/Lombiq.DataTables.Tests.csproj' &&
echo "::endgroup::" &&
echo "::group::test/Lombiq.OSOCE.Tests.UI/Lombiq.OSOCE.Tests.UI.csproj" &&
dotnet test -c Release --no-restore --no-build 'test/Lombiq.OSOCE.Tests.UI/Lombiq.OSOCE.Tests.UI.csproj' &&
echo "::endgroup::" &&
echo "::group::src/Modules/Lombiq.DataTables/Lombiq.DataTables/Tests/Lombiq.DataTables.Tests.UI/Lombiq.DataTables.Tests.UI.csproj" &&
dotnet test -c Release --no-restore --no-build 'src/Modules/Lombiq.DataTables/Lombiq.DataTables/Tests/Lombiq.DataTables.Tests.UI/Lombiq.DataTables.Tests.UI.csproj' &&
echo "::endgroup::" &&
echo "::group::src/Modules/Lombiq.VueJs/Lombiq.VueJs.Tests.UI/Lombiq.VueJs.Tests.UI.csproj" &&
dotnet test -c Release --no-restore --no-build 'src/Modules/Lombiq.VueJs/Lombiq.VueJs.Tests.UI/Lombiq.VueJs.Tests.UI.csproj' &&
echo "::endgroup::" &&
echo "::group::src/Themes/Lombiq.BaseTheme/Lombiq.BaseTheme.Tests.UI/Lombiq.BaseTheme.Tests.UI.csproj" &&
dotnet test -c Release --no-restore --no-build 'src/Themes/Lombiq.BaseTheme/Lombiq.BaseTheme.Tests.UI/Lombiq.BaseTheme.Tests.UI.csproj' &&
echo "::endgroup::" &&
echo "::group::src/Modules/Lombiq.ChartJs/Lombiq.ChartJs.Tests.UI/Lombiq.ChartJs.Tests.UI.csproj" &&
dotnet test -c Release --no-restore --no-build 'src/Modules/Lombiq.ChartJs/Lombiq.ChartJs.Tests.UI/Lombiq.ChartJs.Tests.UI.csproj' &&
echo "::endgroup::" &&
true
```

The `echo "::group::name` and echo "::endgroup::" are the magic strings that let you achieve this clean effect:
![image](https://user-images.githubusercontent.com/4007293/168422248-09b35afd-c33b-4de1-8482-e3a7c0adce8e.png)

Also everything is joined with `&&` so if there is a test failure then the step is short cut to save on processing time.

2022-05-14 10:44 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +          grep 'error MSB3073: The command "npm run dotnet-postclean --if-present"' analysis.log >/dev/null 2>/dev/null && echo npm retry && continue
ok I will try

2022-05-14 10:45 UTC, 0liver commented on .github/workflows/analyze_and_test.yml
> +        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
This is quite magical.

2022-05-14 11:32 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        grep SUCCESS .ui_test_result
life is kill 😭 
![image](https://user-images.githubusercontent.com/4007293/168423831-1933a20d-ee45-408a-8e4e-6da3d29c1d27.png)

2022-05-14 11:36 UTC, 0liver commented on .github/workflows/analyze_and_test.yml
> +        grep SUCCESS .ui_test_result
At least the error description is very verbose 😁

2022-05-14 11:38 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        grep SUCCESS .ui_test_result
The last line makes me think it's so verbose because people were opening change request issues against this behavior.

2022-05-14 13:17 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        dotnet build src/Utilities/Lombiq.Npm.Targets/Lombiq.Npm.Targets.csproj
Just needed to pre-build Gulp Extensions. Weird, becuase based on the project dependency trees that should already happen by that point.

2022-05-14 15:21 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        dotnet build Lombiq.OSOCE.sln --no-incremental -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
For Shouldly-using unit tests a Debug publish would be somewhat nicer but this doesn't matter much.

2022-05-14 15:22 UTC, Piedone commented on .github/TestConfig.json
> +  "Lombiq_Tests_UI": {
I learned about the central config file feature in the meantime. So to confirm, this file is used from all test projects and isn't copied around, right?

2022-05-14 15:24 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
I see, interesting. Please document this because just by looking at it I would have a very hard time figuring out what's the point here. Also, try to structure it more for readability.

2022-05-14 15:31 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        grep SUCCESS .ui_test_result
\> when were you when Dávid got upset?
\> i was sat at home, reviewing code, chilling to synthwave when e-mail with Dávid's comment
\> 'contains the following character: colon :'
\> 'no'

2022-05-14 15:42 UTC, DAud-IcI commented on .github/TestConfig.json
> +  "Lombiq_Tests_UI": {
Yes.

2022-05-14 15:51 UTC, Piedone commented on .github/TestConfig.json
> +  "Lombiq_Tests_UI": {
Good then.

2022-05-14 16:03 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
You can't safely put comments inside the script section (because it gets collapsed during parsing) so I had to write a wall of text above it :( . I have also formatted the code as much as possible, but sed and readability are not something you usually say in the same sentence.

2022-05-14 16:04 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
"sed"? :D

Yeah, I was meaning YAML comments anyway.

2022-05-14 16:16 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
[sed](https://en.wikipedia.org/wiki/Sed) = stream editor, a classic Unix program. It does text replacing, splicing, etc and can be piped. Basically vim for shell scripting. You know you are writing sh when your `cat | sed` 😿

2022-05-14 16:25 UTC, Piedone commented on .github/workflows/analyze_and_test.yml
> +        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
Thanks, I hate it! :D

2022-05-14 16:51 UTC, DAud-IcI commented on .github/workflows/analyze_and_test.yml
> +        grep SUCCESS .ui_test_result
> chilling to synthwave

👍 👍 👍 👍

2022-05-16 19:52 UTC, Piedone requested changes

2022-05-16 19:52 UTC, Piedone commented on .github/workflows/build_and_test.yml
> +          path: test/**/FailureDumps
This also runs on unit test failure and causes a warning: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/2333914401 Maybe better run unit and UI tests in separate tests?

2022-05-16 19:55 UTC, Piedone commented on .github/workflows/build_and_test.yml
> +        dotnet build Lombiq.OSOCE.sln --configuration Release -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
We should also build the NuGet solution. That can perhaps be a second job?

2022-05-16 21:13 UTC, DAud-IcI commented on .github/workflows/build_and_test.yml
> +          path: test/**/FailureDumps
That won't help. The `if: failure()` will evaluate true if any preceding tests failed. See this example:
https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/6459542404?check_suite_focus=true

2022-05-16 21:27 UTC, Piedone commented on .github/workflows/build_and_test.yml
> +          path: test/**/FailureDumps
Do you mean if any preceding step failed? This seems the be the case, [see docs](https://docs.github.com/en/actions/learn-github-actions/expressions#failure), but you can make steps depend on each other to make the UI testing and failure dump-creating step connected.

2022-05-16 21:41 UTC, DAud-IcI commented on .github/workflows/build_and_test.yml
> +          path: test/**/FailureDumps
How do you tell UI and unit tests apart anyway?

2022-05-16 21:43 UTC, DAud-IcI commented on .github/workflows/build_and_test.yml
> +          path: test/**/FailureDumps
I have found [this gem](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles) and it seem to work. Doing `if: failure() && hashFiles('test/**/FailureDumps')` means upload-artifact only runs if there is something to dump.

2022-05-16 22:06 UTC, Piedone commented on .github/workflows/build_and_test.yml
> +          path: test/**/FailureDumps
Great then! For the first question, I suppose based on name only.

2022-05-16 22:09 UTC, DAud-IcI commented on .github/workflows/build_and_test.yml
> +          path: test/**/FailureDumps
> based on name only.

[shudder]

2022-05-19 18:13 UTC, Piedone requested changes

2022-05-19 18:13 UTC, Piedone commented on NuGetTest/.editorconfig
> +# WARNING: Only edit this file in the Lombiq .NET Analyzers repository's folder. A copy of this file anywhere else will
Why is this file needed? We shouldn't have to copy it. If Analyzers adds it then it should be gitignored.

2022-05-19 18:13 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorModuleTests.cs
> +    public Task BaseThemeShouldWork(Browser browser) =>
Why did you move this from `BehaviorBaseThemeTests`? It was good there, it's not a module.

2022-05-19 19:40 UTC, Piedone commented
You didn't address my feedback here.

2022-05-19 19:47 UTC, DAud-IcI commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorModuleTests.cs
> +    public Task BaseThemeShouldWork(Browser browser) =>
`BehaviorBaseThemeTests` is too specific. If it's not good here, then I'll move it to `BehaviorThemeTests` (without the "Base").

2022-05-19 19:48 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/BehaviorModuleTests.cs
> +    public Task BaseThemeShouldWork(Browser browser) =>
Yeah, just a rename like that is good.

2022-05-19 21:01 UTC, Piedone approved these changes
Looks good but https://github.com/Lombiq/UI-Testing-Toolbox/pull/119#discussion_r877536815 affects this too.

2022-05-24 20:36 UTC, 0liver requested changes

2022-05-24 20:36 UTC, 0liver commented on .github/workflows/build_and_test.yml
> +        docker pull mcr.microsoft.com/azure-storage/azurite &&
Why do you chain with `&&` here but not in the SQL server setup [above](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/41/files#diff-48c0ee97c53013d18d6bbae44648f7fab9af2e0bf5b0dc1ca761e18ec5c478f2R39)?

2022-05-24 20:36 UTC, 0liver commented on .github/workflows/build_and_test.yml
> +      #   outputs should be placed into a collapsible region on the Actions web UI.
I needed some clarification on this comment, so here's what I came up with:
```suggestion
      # - The test output is wrapped by '::group::<project name>' before and '::endgroup::' after it. This tells GitHub
      #   to place each test's output into a collapsible region on the Actions web UI.
```

2022-05-24 20:36 UTC, 0liver commented on .github/workflows/build_and_test.yml
> +        grep SUCCESS .ui_test_result
I'm seriously impressed.

2022-05-24 20:36 UTC, 0liver commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/.htmlvalidate.json
> +          "method": [ "get", "post", "GET", "POST" ]
Is this now supposed to be unnecessary with the [latest version](https://gitlab.com/html-validate/html-validate/-/releases/v7.1.1)?

2022-05-24 20:46 UTC, DAud-IcI commented on .github/workflows/build_and_test.yml
> +        docker pull mcr.microsoft.com/azure-storage/azurite &&
By accident.

2022-05-24 20:49 UTC, DAud-IcI commented on .github/workflows/build_and_test.yml
> +      #   outputs should be placed into a collapsible region on the Actions web UI.
Hmm, some nuance is lost in translation, but I guess it carries the gist better so I'm in favor of it.

2022-05-25 12:49 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lombiq.HelpfulLibraries.Cli", "src\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.Cli\Lombiq.HelpfulLibraries.Cli.csproj", "{F4B0F77A-4
Add a corresponding line to the Readme under "Included Projects".

2022-05-25 21:04 UTC, 0liver approved these changes

2022-05-26 11:27 UTC, 0liver approved these changes

2022-05-26 12:05 UTC, merged