OSOE-588: Add ContentEditors module upgraded to 1.5.0
Lombiq/Open-Source-Orchard-Core-Extensions pull request #426
Opened 2023-03-10 21:59 UTC by jtkech

OSOE-588

Related https://github.com/Smithsonian/CFCH-folkwaysCore/pull/92, #424

2023-03-13 11:57 UTC, 0liver commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +    <ProjectReference Include="..\Modules\Lombiq.UIKit\Lombiq.UIKit\Lombiq.UIKit.csproj" />
Did you sort the `ProjectReference` entries by hand, or did a tool do that for you?

2023-03-13 16:50 UTC, jtkech commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +    <ProjectReference Include="..\Modules\Lombiq.UIKit\Lombiq.UIKit\Lombiq.UIKit.csproj" />
No tool, I did it manually ;) Just because I saw them ordered alphabetically unless a few of them, but did it quickly so not sure there are not some remaining one.

Let me know if it is a rule that you are using, if so I will correct the remaining ones, for example just saw that `..\Modules\Lombiq.HelpfulExtensions...` would need to be before all `..\Modules\Lombiq.Hosting...` ;)

2023-03-13 20:06 UTC, 0liver commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +    <ProjectReference Include="..\Modules\Lombiq.UIKit\Lombiq.UIKit\Lombiq.UIKit.csproj" />
We dreamed about building a tool once that would bring solution files into order, but that's it 😉

I think many of us at Lombiq like to have things in order, so drive-by cleanup is welcome 🙂

2023-03-13 23:58 UTC, jtkech commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
> +    <ProjectReference Include="..\Modules\Lombiq.UIKit\Lombiq.UIKit\Lombiq.UIKit.csproj" />
Okay, done here

2023-03-29 20:30 UTC, jtkech commented
Close in favor of #439

2023-03-30 17:23 UTC, Piedone commented
No, please you do this. Márk just wasn't aware you are already working on it. If something is needed from https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/439 for adding the module to the solution then copy them over.

2023-03-30 20:44 UTC, jtkech commented
Okay, I will look at #439 this week end.

2023-03-31 12:04 UTC, Piedone requested changes

2023-03-31 12:04 UTC, Piedone commented on Lombiq.OSOCE.sln
> -﻿
Keep the UI tests as they were under https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/270/files. The one in the NuGetTests folder as well, but it can be yet commented out, with a comment that it'll be implemented in https://lombiq.atlassian.net/browse/OSOE-56.

2023-03-31 21:27 UTC, jtkech commented
@Piedone 

Okay I integrated what make sense from #439.

Also added under `NugetTest` the package references (but commented out) in the project files, and the new test also commented out. I didn't add a comment in https://lombiq.atlassian.net/browse/OSOE-56 because I don't have any access or I lost it ;)

2023-03-31 21:28 UTC, jtkech commented on Lombiq.OSOCE.sln
> -﻿
Okay, done

2023-04-02 19:20 UTC, Piedone commented
Thank you!

2023-04-02 19:34 UTC, Piedone approved these changes

2023-04-02 19:34 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorAsyncEditorTests.cs
> +#pragma warning disable SA1005
Actually, this is just cleaner to keep under the issue, sorry. I'm moving it and the references to there.

2023-04-02 19:57 UTC, merged