OSOE-593: Update Node.js Extensions to latest release incl. extra logging
Lombiq/Open-Source-Orchard-Core-Extensions pull request #442
Opened 2023-03-30 13:19 UTC by 0liver

[OSOE-593](https://lombiq.atlassian.net/browse/OSOE-593)

[OSOE-593]: https://lombiq.atlassian.net/browse/OSOE-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-04 07:38 UTC, dministro approved these changes

2023-04-12 20:50 UTC, dministro requested changes

2023-04-12 20:50 UTC, dministro commented on src/Utilities/Lombiq.Npm.Targets
I can't find the PR for this change.

2023-04-12 21:15 UTC, 0liver commented on src/Utilities/Lombiq.Npm.Targets
My apologies. Here it is: https://github.com/Lombiq/NPM-Targets/pull/35.

2023-04-13 20:41 UTC, dministro approved these changes

2023-04-14 07:47 UTC, merged