Upgrade to Orchard Core 1.6
Lombiq/Open-Source-Orchard-Core-Extensions pull request #454
Opened 2023-04-25 07:06 UTC by Psichorex

Fixes #378 

OSOE-548

2023-04-28 17:22 UTC, Piedone requested changes

2023-04-28 17:22 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +                ["OrchardCore.Twitter"] = new[] { "Lombiq.UIKit" },
You shouldn't change this. As I told under the issue: on `dev`, the UI test passes. If the UI test breaks with 1.6, then you should fix the underlying functionality, not employ a workaround like this.

2023-04-28 17:22 UTC, Piedone commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Why the downgrade, and the other changes in this file necessary?

2023-04-28 18:03 UTC, Psichorex commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
It was probably unintentional as pnpm-lock.yaml is popping up constantly without me touching it.

2023-04-28 18:13 UTC, Psichorex commented on src/Lombiq.OSOCE.Web/Program.cs
> +                ["OrchardCore.Twitter"] = new[] { "Lombiq.UIKit" },
There is a problem related most probably to Orchard Core I am going to discuss now here in detail so you get a good understanding.

This is the code that the current dev contains:
![image](https://user-images.githubusercontent.com/92299130/235221237-3669d771-c968-4ac5-9a77-0c4bc55c9698.png)

Because the Conditinal Twitter module has 2 conditions the IFeatureEventHandler will run fully 2 times.
This is the first run :
![image](https://user-images.githubusercontent.com/92299130/235221694-0a51982a-1cde-4b41-94a3-d0b85ae04254.png)
Here you can see that the featuresToEnable contains Twitter only and it will call :
`await _shellFeatureManager.EnableFeaturesAsync(featuresToEnable)` 
OrchardCore.Twitter gets enabled here.

Problem roots here :
![image](https://user-images.githubusercontent.com/92299130/235222056-6dcacb97-2ef4-42e6-b435-e7646bfb0c62.png)
Here you see that the `shellDescriptor.Features` contains exactly 59 items.

After Twitter getting enabled and the IFeatureEventHandler runing the second time fully because it hit the second condition feature the shellDescriptor.Features will again contain 59 items. 

So basically it does not indicate that Twitter has been enabled.

So it tries to activate it again and this happens:
![image](https://user-images.githubusercontent.com/92299130/235222415-23876d4d-a27a-4e26-af4e-c9b896245b6e.png)

This was causing the UI Test problems but and this is an important but those test were flaky and they started passing after a certain time.
It was enough for me to take notice that something is fishy that's how I found out that this part is not functioning properly.

2023-04-28 19:26 UTC, 0liver commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Update to pnpm@7, please.

2023-04-28 19:34 UTC, Psichorex commented on src/Lombiq.OSOCE.Web/Program.cs
> +                ["OrchardCore.Twitter"] = new[] { "Lombiq.UIKit" },
Added a workaround that fixes the issue.

2023-04-28 19:39 UTC, Psichorex commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
@0liver It won't actually let me update PNPM. 
Giving npm install -g pnpm@7 will produce some installing like behavior but even after that checking pnpm -v give me back pnpm 6.32.0.

2023-05-01 19:43 UTC, Piedone requested changes

2023-05-01 19:43 UTC, Piedone commented on pnpm-lock.yaml
> -    dev: true
Revert the whitespace change too.

2023-05-01 19:43 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +                ["OrchardCore.Twitter"] = new[] { "Lombiq.UIKit" },
Thanks for taking the time to explain. However, three things to note:

1. Where do you see the test being flaky? Flaky means it sometimes fails, sometimes passes. I checked out the last 10 successful `dev` build (the most recent one was a timeout due to https://github.com/Lombiq/UI-Testing-Toolbox/issues/228) and none of them showed this test being flaky. I.e, it passed on the first time in each run. Or did it flakily pass after 1.6?
2. The goal of this issue is to upgrade the OSOCE solution to OC 1.6. If something used to work under 1.5 but then breaks 1.6 then that's something that needs to be fixed. Why it used to work, and whether the implementation was a good idea at that time might be interesting, but is ultimately beside the point; it needs to keep working. Finding incompatibilities and thus things breaking between OC versions is part and parcel of such an issue.
3. I don't know if you intentionally use the word "workaround" instead of something like "fix". If you're just using these interchangeably without a specific meaning, then no problem; otherwise, I'd like to clarify that in all such cases, we're seeking a permanent, proper fix to a given problem, not just a workaround (which is usually used to mean a temporary fix to get the system into a working order without actually fixing the underlying problem). It might be that for some reason it's infeasible to implement a good fix, and we need to be content with just a workaround, but this is not such a case.

2023-05-12 13:40 UTC, Piedone approved these changes

2023-05-17 13:31 UTC, Piedone approved these changes

2023-05-17 14:42 UTC, Piedone approved these changes

2023-05-18 14:14 UTC, Piedone approved these changes

2023-05-18 20:11 UTC, Piedone approved these changes

2023-05-19 14:54 UTC, Piedone approved these changes

2023-05-21 20:45 UTC, Piedone requested changes
1. Be sure to update **all** Lombiq package references in all projects while doing a release gradually: https://lombiq.atlassian.net/wiki/spaces/DEV/pages/786857987/Managing+releases+of+open-source+projects#An-example-of-releasing-OSOCE-projects A lot of the Helpful Libraries package references our outdated. Search for `PackageReference Include="Lombiq` in the solution, and you shouldn't see any non-alpha version for those packages that you released.
2. Also update the NuGetTest solution to the latest packages. Without that, the new packages are not tested.

2023-06-10 16:27 UTC, Piedone approved these changes

2023-06-10 18:22 UTC, Piedone approved these changes
Just marking the merge from `issue/OSOE-641`.

2023-06-10 18:51 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      print-config-summary: "true"
Remove these before setting the issue to Done.

2023-06-11 17:26 UTC, Piedone approved these changes

2023-06-12 11:45 UTC, Piedone approved these changes

2023-06-19 00:00 UTC, merged