NEST-391: Maintenance to make a role site owner
Lombiq/Open-Source-Orchard-Core-Extensions pull request #480
Opened 2023-05-25 16:37 UTC by barthamark

NEST-391

2023-05-26 14:17 UTC, wAsnk requested changes

2023-05-26 14:17 UTC, wAsnk commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.Hosting.Tenants.Maintenance" Version="4.0.3-alpha.1.nest-391" />
Please also update the other Lombiq.Hosting.Tenants NuGet versions. Thank you. 🍓

2023-05-27 10:37 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.Hosting.Tenants.Maintenance" Version="4.0.3-alpha.1.nest-391" />
You should keep increasing the number after the `4.0.3-alpha` part to simplify updating to a newer version.

2023-05-30 11:25 UTC, barthamark commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.Hosting.Tenants.Maintenance" Version="4.0.3-alpha.1.nest-391" />
It'll become unmanageable with parallel development so I wouldn't increase the number after the `alpha`. The issue number differentiates it already.

2023-05-30 11:27 UTC, barthamark commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.Hosting.Tenants.Maintenance" Version="4.0.3-alpha.1.nest-391" />
Apparently, we are on 4.1.0 in dev already, so it'll change anyway.

2023-05-30 11:48 UTC, 0liver commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.Hosting.Tenants.Maintenance" Version="4.0.3-alpha.1.nest-391" />
> It'll become unmanageable with parallel development so I wouldn't increase the number after the `alpha`. The issue number differentiates it already.

The idea behind this versioning scheme is to be able to simply increment the number behind the `alpha`, no matter on which issue you are currently working. This allows for a very pleasing experience with the NuGet package manager from VS where you can simply update to all latest versions, including pre-release ones.

There is the edge-case, you are correct, that two devs work on the same module in parallel and update the version at the same time or close to each other, but that happens extremely rarely and doesn't add any further harm, so I think we should be able to accept it.

2023-05-30 15:05 UTC, merged