HAST-175: NuGet publishing fixes in Lombiq.GitHub.Actions
Lombiq/Open-Source-Orchard-Core-Extensions pull request #483
Opened 2023-05-26 12:58 UTC by Piedone

[HAST-175](https://lombiq.atlassian.net/browse/HAST-175)

[HAST-175]: https://lombiq.atlassian.net/browse/HAST-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-23 21:06 UTC, DAud-IcI requested changes

2023-06-23 21:06 UTC, sarahelsaig commented on .github/actions/spelling/excludes.txt
> +^\Qsrc/Modules/Lombiq.Hosting.Tenants/Readme.md\E$
Why is the `\Q...\E` necessary here? imo even leaving the dots unescaped should be fine, it's not like we expect any realistic false positives. But at any rate for consistency's sake, let's either wrap every line like here, or none of them.

2023-06-25 21:28 UTC, Piedone commented on .github/actions/spelling/excludes.txt
> +^\Qsrc/Modules/Lombiq.Hosting.Tenants/Readme.md\E$
Yeah, it's probably an overkill though dots are escaped in most of the other lines. I'll wrap them.

2023-06-26 08:02 UTC, 0liver commented on .github/actions/spelling/excludes.txt
> +^\Qsrc/Modules/Lombiq.Hosting.Tenants/Readme.md\E$
I would choose simplicity over such uncommon configuration.

What's the real problem that using `\Q...\E` solves?

2023-06-26 08:17 UTC, 0liver commented on .github/actions/spelling/excludes.txt
> +^\Qsrc/Modules/Lombiq.Hosting.Tenants/Readme.md\E$
Btw, where's the documentation on `\Q...\E`? The only mention I've found was here: https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples%3A-excludes, and it doesn't explain what it does there.

2023-06-26 08:26 UTC, DAud-IcI commented on .github/actions/spelling/excludes.txt
> +^\Qsrc/Modules/Lombiq.Hosting.Tenants/Readme.md\E$
It's a feature in _some_ regex engines, though it doesn't work in .NET regex expressions.
https://www.regular-expressions.info/characters.html#:~:text=Some%20flavors%20also%20support%20the

2023-06-26 08:46 UTC, 0liver commented on .github/actions/spelling/excludes.txt
> +^\Qsrc/Modules/Lombiq.Hosting.Tenants/Readme.md\E$
I didn't know that one, thanks!

2023-07-24 20:22 UTC, DAud-IcI commented
merge conflict here, otherwise approved

2023-07-25 09:28 UTC, merged