OSOE-606 Upgrade to C# 11 in Lombiq.Analyzers
Lombiq/Open-Source-Orchard-Core-Extensions pull request #487
Opened 2023-06-04 18:33 UTC by Piedone

2023-06-05 13:57 UTC, 0liver requested changes

2023-06-05 13:57 UTC, 0liver commented on .github/workflows/build-and-test.yml
> +      dotnet-version: "7.0.x"
Why didn't you change the version in LGHA directly?

2023-06-05 14:00 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      dotnet-version: "7.0.x"
Because that would affect all of our projects at once, with the uncertainties of the concrete .NET version still in place. So, this is better handled under https://lombiq.atlassian.net/browse/SPAL-23, as it's planned there.

2023-06-05 14:59 UTC, 0liver approved these changes

2023-06-05 18:00 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      machine-types: "['ubuntu-22.04-4core']"
See [here](https://teams.microsoft.com/l/message/19:525a1a3656c845ae92c5e2c0d3617cc7@thread.skype/1685988011025?tenantId=959ede5a-38e9-44e6-adc8-85553beb8220&groupId=d6a5d775-6fb9-41dc-a7bb-481d4f884046&parentMessageId=1685988011025&teamName=Lombiq%20Developers&channelName=General&createdTime=1685988011025&allowXTenantAccess=false) for this and the Windows machine type change. I'll revert this once all PRs are approved.

2023-06-05 20:54 UTC, 0liver approved these changes

2023-06-06 11:45 UTC, 0liver approved these changes

2023-06-06 19:52 UTC, 0liver approved these changes

2023-06-06 23:12 UTC, merged