OSOE-56: Open-source Content Editors
Lombiq/Open-Source-Orchard-Core-Extensions pull request #491
Opened 2023-06-07 15:03 UTC by barthamark

[OSOE-56](https://lombiq.atlassian.net/browse/OSOE-56)

[OSOE-56]: https://lombiq.atlassian.net/browse/OSOE-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-07 22:09 UTC, Piedone requested changes

2023-06-07 22:09 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Lombiq.OSOCE.NuGet.Tests.UI.csproj
> +    <PackageReference Include="Lombiq.ContentEditors.Tests.UI" Version="1.0.0-alpha.1.osoe-56" />
Add a test to the NuGetTest solution (there's a draft in the issue).

2023-06-07 22:09 UTC, Piedone commented on Readme.md
> +- [`Lombiq.ContentEditors`](https://github.com/Lombiq/Orchard-Content-Editors): Go to Features in the admin dashboard and enable the `Lombiq Content Editors - Sample` feature.
This recipe doesn't exist.

2023-06-07 22:09 UTC, Piedone commented on Readme.md
> +  - [`Lombiq.ContentEditors`](https://github.com/Lombiq/Orchard-Content-Editors): With the help of this module you can create custom multi-page editors with async loading and saving.
This is missing: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions#contributing-and-support:~:text=For%20this%2C%20you%27ll%20also%20need%20to%20enable%20the%20feature%20in%20Lombiq.OSOCE.Tests.recipe.

2023-06-08 12:26 UTC, barthamark commented on Readme.md
> +- [`Lombiq.ContentEditors`](https://github.com/Lombiq/Orchard-Content-Editors): Go to Features in the admin dashboard and enable the `Lombiq Content Editors - Sample` feature.
Yes, it doesn't. I didn't see it necessary actually. But the title here says Samples and Recipes so I thought I add it here. Do you want me to delete it?

2023-06-08 13:25 UTC, Piedone commented on Readme.md
> +- [`Lombiq.ContentEditors`](https://github.com/Lombiq/Orchard-Content-Editors): Go to Features in the admin dashboard and enable the `Lombiq Content Editors - Sample` feature.
Well, this bullet point references something that doesn't exist. This doesn't make sense. So yes, delete it (if there's no actual need for a recipe).

2023-06-13 14:31 UTC, Piedone requested changes

2023-06-13 14:31 UTC, Piedone commented on Readme.md
> +- [`Lombiq.ContentEditors`](https://github.com/Lombiq/Orchard-Content-Editors): Go to Features in the admin dashboard and enable the `Lombiq Content Editors - Sample` feature.
Still.

2023-06-27 20:40 UTC, Piedone approved these changes

2023-06-28 16:37 UTC, Piedone approved these changes

2023-06-28 17:15 UTC, Piedone commented
The failing Windows build is expected, see https://lombiq.atlassian.net/browse/OSOE-620.

2023-06-28 17:15 UTC, merged