OSOE-647: ⭐ Under Orchard Core 1.6, menu items generated via MainMenuNavigationProvider are prefixed with /Admin in Lombiq.BaseTheme
Lombiq/Open-Source-Orchard-Core-Extensions pull request #503
Opened 2023-06-16 16:31 UTC by DAud-IcI

OSOE-647

2023-06-16 23:09 UTC, Piedone requested changes

2023-06-16 23:09 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    [Theory, Chrome]
Like `BehaviorBaseThemeTests`, the test cases here should rather be in `Lombiq.BaseTheme.Tests.UI`.

2023-06-16 23:09 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +                await context.GoToRelativeUrlAsync("/Admin/Contents/ContentItems/Menu");
Also below, and do something similar for the form action (see `context.AdminUrlPrefix` or `context.GetAbsoluteAdminUri()`.
```suggestion
                await context.GoToAdminRelativeUrlAsync("/Contents/ContentItems/Menu");
```

2023-06-16 23:09 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +                context.ExecuteScript(@"
Comment why this needs to be in JS.

2023-06-16 23:09 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    public Task ContentMenuItemShouldWorkCorrectly(Browser browser) =>
It would be better for all of this except the assertion to come from a recipe instead. Since the point is not testing the admin behavior.

2023-06-17 11:33 UTC, DAud-IcI commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +                await context.GoToRelativeUrlAsync("/Admin/Contents/ContentItems/Menu");
> do something similar for the form action

I can just make the query partial, like `form[action*='SetCurrentTheme/Lombiq.BaseTheme.Samples'] button` because only the theme name matters there.

2023-06-17 12:30 UTC, DAud-IcI commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +                context.ExecuteScript(@"
On second thought this can be achieved via HttpClient just as well...

2023-06-17 13:40 UTC, DAud-IcI commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    public Task ContentMenuItemShouldWorkCorrectly(Browser browser) =>
I can't do that because I get the `ValidationException: Your alias is already in use. "main-menu"` exception during setup. The same happens even if you set it up using the main OSOE recipe. (since the blog recipe is invoked [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blame/issue/OSOE-548/src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json#L66)) I'm not aware of a way to overwrite a content item with a randomized ID,

2023-06-17 13:52 UTC, DAud-IcI commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    [Theory, Chrome]
I disagree because everything in `ContentMenuItemShouldWorkCorrectly` only works if you have executed the Blog recipe so it's not portable/reusable.

In `ThemeWithoutSetupShouldWork`, I was able to turn the dependency feature verification into an extension (`BaseThemeDependencyShouldBeEnabled`). But the last 2 lines of that test are also blog-specific so pointless to extract.

2023-06-17 20:45 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    [Theory, Chrome]
My issue is that we essentially put part of the Base Theme test suite into OSOCE.

UI tests can't be fully portable, but depending on the Blog recipe, what's one of the built-in Orchard ones so one that can be reasonable requested (if you want to run this particular test).

2023-06-17 20:47 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    public Task ContentMenuItemShouldWorkCorrectly(Browser browser) =>
So you can't update an existing menu with a new item based on the menu's alias (and the blog post's AutoRoute)? If not, then nothing to do.

2023-06-17 20:48 UTC, Piedone requested changes
See my comments.

2023-06-17 20:52 UTC, DAud-IcI commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    public Task ContentMenuItemShouldWorkCorrectly(Browser browser) =>
Exactly.

2023-06-18 13:24 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    public Task ContentMenuItemShouldWorkCorrectly(Browser browser) =>
Please do add a comment about this.

2023-06-18 15:12 UTC, DAud-IcI commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +    public Task ContentMenuItemShouldWorkCorrectly(Browser browser) =>
Done. I also made a followup issue about it: https://github.com/Lombiq/Helpful-Libraries/issues/199

2023-06-18 18:53 UTC, Piedone approved these changes

2023-06-18 19:16 UTC, merged