OSOE-603: Upgrade to pnpm@8
Lombiq/Open-Source-Orchard-Core-Extensions pull request #526
Opened 2023-07-17 22:36 UTC by DAud-IcI

OSOE-603

2023-07-21 16:20 UTC, Piedone requested changes

2023-07-21 16:20 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      build-verbosity: normal
Isn't the default suitable?

2023-07-21 16:20 UTC, Piedone commented on package.json
> +    "eslint": "^8.45.0",
And update would be great, but all the other package.jsons are 8.25.0.

2023-07-21 16:50 UTC, DAud-IcI commented on .github/workflows/build-and-test.yml
> +      build-verbosity: normal
It was just diagnostics, I removed most but I guess forgot this one.

2023-07-21 16:53 UTC, DAud-IcI commented on package.json
> +    "eslint": "^8.45.0",
It wasn't intentional, not sure why but sometimes it tries to update it despite the lock. Reverted.

2023-07-21 17:16 UTC, Piedone approved these changes

2023-07-21 17:21 UTC, Piedone requested changes

2023-07-21 17:21 UTC, Piedone commented on pnpm-lock.yaml
A rebuild causes this for me:

![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/1976647/b4c052c0-7d4f-4e48-a6e2-3b232b17e85e)

So something apparently needs to be done with the package.json file.

2023-07-21 17:43 UTC, DAud-IcI commented on pnpm-lock.yaml
That often happens for me, with this or that NE-using project. I usually just revert it.

2023-07-21 18:08 UTC, Piedone commented on pnpm-lock.yaml
We shouldn't have to revert it. This, and only this file, happens on every rebuild for me.

2023-07-21 19:19 UTC, DAud-IcI commented on pnpm-lock.yaml
Yeah, it do be like that. it's not part of this issue, but I will investigate soon.

2023-07-22 12:50 UTC, Piedone commented
Thank you!

--
Zoltán Lehóczky
Co-founder and managing director
Lombiq Technologies Ltd.
https://lombiq.com
[image]<https://lombiq.com/>
Please note that we store your personal data in accordance with our privacy policy<https://lombiq.com/privacy-policy>, but you can anytime choose to withdraw your previous consent by writing to ***@***.***
________________________________
From: Dávid El-Saig ***@***.***>
Sent: Friday, July 21, 2023 9:19:16 PM
To: Lombiq/Open-Source-Orchard-Core-Extensions ***@***.***>
Cc: Zoltán Lehóczky ***@***.***>; Comment ***@***.***>
Subject: Re: [Lombiq/Open-Source-Orchard-Core-Extensions] OSOE-603: ⭐ Upgrade to ***@***.*** (PR #526)


@DAud-IcI commented on this pull request.

________________________________

On pnpm-lock.yaml<https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/526#discussion_r1271006577>:

Yeah, it do be like that. it's not part of this issue, but I will investigate soon.

—
Reply to this email directly, view it on GitHub<https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/526#discussion_r1271006577>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAPCSR236PFQYKRC7THJH7DXRLI3JANCNFSM6AAAAAA2NR7WCE>.
You are receiving this because you commented.Message ID: ***@***.***>

2023-08-14 23:15 UTC, Piedone approved these changes

2023-08-16 19:23 UTC, Piedone approved these changes

2023-08-20 21:40 UTC, merged