OSOE-62: Include Lombiq.BaseTheme
Lombiq/Open-Source-Orchard-Core-Extensions pull request #54
Opened 2022-02-23 05:52 UTC by DAud-IcI

OSOE-62

2022-04-18 22:08 UTC, Piedone requested changes

2022-04-18 22:08 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +// I don't know why this is necessary.
Nevertheless, some comment on why you've added it is necessary.

2022-04-18 22:08 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +      // Using a custom theme that relies on "Lombiq.BaseTheme". Previously we used "TheTheme" because the dafault
```suggestion
      // Using a custom theme that relies on "Lombiq.BaseTheme". Previously we used "TheTheme" because the default
```

2022-04-18 22:08 UTC, Piedone commented on src/Modules/Lombiq.OSOCE.Samples/Startup.cs
> +    }
Why did you add this?

2022-04-18 22:08 UTC, Piedone commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +    <ProjectReference Include="..\Lombiq.DataTables\Lombiq.DataTables.Samples\Lombiq.DataTables.Samples.csproj" />
Why are these necessary?

2022-04-18 22:08 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +        "Lombiq.BaseTheme.Samples",
Wow, this is nice!
![image](https://user-images.githubusercontent.com/1976647/163877356-16dca103-b421-44cd-9c71-317d7aa95f1a.png)

Add a note to the root Readme about adding a menu provider for this too.

2022-04-18 22:08 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/BehaviorThemeTests.cs
> +public class BehaviorThemeTests : UITestBase
```suggestion
public class BehaviorBaseThemeTests : UITestBase
```

2022-04-18 22:08 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +      "site": "Lombiq.BaseTheme.Samples"
`FrontendPagesShoudlBeAccessbile` can be adjusted.

2022-04-18 22:08 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lombiq.BaseTheme", "src\Themes\Lombiq.BaseTheme\Lombiq.BaseTheme\Lombiq.BaseTheme.csproj", "{F482D324-1F7C-4D2A-8124-F456ABE58644}"
Do https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions#:~:text=If%20an%20extension%20is%20added%2C%20removed%20or%20significantly%20updated%20in%20this%20project%2C%20then%20add%2C%20remove%20or%20update%20its%20description%20under%20the%20%22Included%20Projects%22%20section%20of%20this%20Readme.

2022-04-19 00:04 UTC, DAud-IcI commented on src/Modules/Lombiq.OSOCE.Samples/Lombiq.OSOCE.Samples.csproj
> +    <ProjectReference Include="..\Lombiq.DataTables\Lombiq.DataTables.Samples\Lombiq.DataTables.Samples.csproj" />
I forgot to revert these.

2022-04-19 00:56 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Program.cs
> +// I don't know why this is necessary.
It's because otherwise I get this right after setup:
![image](https://user-images.githubusercontent.com/4007293/163898338-e8ae71c0-ba3b-40e9-9688-ec9b72a45d7d.png)
Strangely it only happens when you run Lombiq.OSOCE.Web directly, but not from the UI tests. Could you check if you get the same problem too?

2022-04-19 01:17 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +      "site": "Lombiq.BaseTheme.Samples"
Adjusted. Unfortunately we still have to put up with some BS from the footer widget so only 2 of the 4 rules can be restored.
[FrontendPagesShouldBeAccessible.pdf](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/files/8509000/FrontendPagesShouldBeAccessible.pdf)

2022-04-19 10:44 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +      "site": "Lombiq.BaseTheme.Samples"
We can just fix these, no?

2022-04-19 10:47 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +// I don't know why this is necessary.
I get the same with the TEST recipe (during setup, if the site is already set up then it works without this line). This looks like an issue with OrchardCore.Roles or Users not being properly enabled.

2022-04-19 11:25 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +      "site": "Lombiq.BaseTheme.Samples"
Not without replacing the blog recipe. It should be fixed upstream in OC.

2022-04-19 12:14 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Program.cs
> +// I don't know why this is necessary.
Yeah, I meant that it works with the test recipe in UI tests but not if you manually start it up. Turns out the extra dependency for "OrchardCore.Users" in "Lombiq.Tests.UI.Shortcuts" fixed it for UI testing. It's good now.

2022-04-19 13:22 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +      "site": "Lombiq.BaseTheme.Samples"
OK, so that's about Blog. We did fix some of these (in the upcoming 1.4) I think.

2022-04-19 21:03 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +// I don't know why this is necessary.
This needs to be done for the NuGet solution too.

2022-04-26 15:55 UTC, Piedone commented on Readme.md
> +  - [Lombiq.BaseTheme.Samples](https://github.com/Lombiq/Orchard-Base-Theme/tree/dev/Lombiq.BaseTheme.Samples): A sample theme that demonstrates the features of the [Lombiq.BaseTheme](https://github.
Add a corresponding entry to "Samples and Recipes" too.

2022-04-27 10:58 UTC, DAud-IcI commented on src/Lombiq.OSOCE.Web/Program.cs
> +// I don't know why this is necessary.
On second thought adding them to the setup recipe is a bit fragile. Instead, I have moved the `"OrchardCore.*"` features from the TrainingDemo recipe's feature step into the TrainingDemo's manifest file as dependencies. I think that's more correct, right? Then the OSOCE setup recipe doesn't need them either. I have added a comment about it in the _TrainingDemo.recipe.json_ too. I have checked and there aren't any other such features in any of the other recipes so I think we are in the clear.

This makes it self-contained so I don't think there there is anything NuGet specific to be done.

2022-04-27 11:46 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +// I don't know why this is necessary.
Yeah, in the manifest it's better.

2022-05-05 10:16 UTC, Piedone commented on Readme.md
> +  - The "TEST: Basic Orchard Features" setup recipe automatically sets it up. If not using it, run the "Lombiq Orchard Core Base Theme - Layers and Zones" recipe, and then enable the theme in Admin >
```suggestion
  - The "TEST: Basic Orchard Features" setup recipe automatically sets it up. If not using it, run the "Lombiq Orchard Core Base Theme - Layers and Zones" recipe, and then enable the theme in Admin → Design → Themes.
```

2022-05-05 10:16 UTC, Piedone commented on Readme.md
> +- If the sample project includes MVC actions, create a service that inherits from `MainMenuNavigationProviderBase` and adds front-end main menu items. The top level menu item should have the project'
I'd perhaps link to the GitHub page instead, though during local development this is cool too.

2022-05-05 10:16 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +      "site": "Lombiq.BaseTheme.Samples"
I don't see any changes in `FrontendPagesShouldBeAccessible`.

2022-05-05 10:52 UTC, Piedone requested changes

2022-05-05 10:52 UTC, Piedone commented on NuGetTest/Directory.Build.props
> +    <NuGetBuild>true</NuGetBuild>
This solution shouldn't permanently target this. In fact, it should never, since it is not published to NuGet.

2022-05-05 10:52 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.BaseTheme.Samples" Version="1.0.0-alpha.8" />
Why no floating version here too?

2022-05-05 10:52 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
> +      "site": "Lombiq.BaseTheme.Samples"
Now I do!

2022-05-05 10:52 UTC, Piedone commented on NuGetTest/src/Modules/Lombiq.OSOCE.NuGet.TestModule/Controllers/AnalyzersTestController.cs
> +    // package.
But it's also enforced from the submodule.

2022-05-05 10:52 UTC, Piedone commented on NuGetTest/src/Modules/Lombiq.OSOCE.NuGet.TestModule/Lombiq.OSOCE.NuGet.TestModule.csproj
> +    <PackageReference Include="Lombiq.HelpfulLibraries" Version="4.1.0" />
Why no floating versions here and the other projects too?

2022-05-05 14:14 UTC, DAud-IcI commented on Readme.md
> +- If the sample project includes MVC actions, create a service that inherits from `MainMenuNavigationProviderBase` and adds front-end main menu items. The top level menu item should have the project'
Apparently this doesn't work when clicking from GitHub so it's a no-go. I have replaced it with an absolute URL, though that now points to dev like you said in the other PR so it won't work until the Lombiq.TrainingDemo PR is merged.

2022-05-05 14:15 UTC, DAud-IcI commented on NuGetTest/Directory.Build.props
> +    <NuGetBuild>true</NuGetBuild>
Isn't this solution supposed to simulate a NuGet build environment?

2022-05-05 14:22 UTC, sarahelsaig commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.BaseTheme.Samples" Version="1.0.0-alpha.8" />
doesn't work with pre-release
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#:~:text=floating%20versions%20do%20not%20resolve%20prerelease%20versions%20unless%20opted%20into

2022-05-05 14:28 UTC, sarahelsaig commented on NuGetTest/src/Modules/Lombiq.OSOCE.NuGet.TestModule/Controllers/AnalyzersTestController.cs
> +    // package.
This project should only be verified by the NuGet package of Lombiq.Analyzers. That's why:
- https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/54/files/64602ff8917c799ae8906af78b458968047cbc73..1f6f5366d3a6e803946012ce2e45955b59f15be1#diff-b994a2e9f5cc46380b753ba286d391de4efd18431ae8ab574fe1dd45eb15d62bR3
- https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/issue/OSOE-62/Directory.Build.props#L13

2022-05-05 14:30 UTC, DAud-IcI commented on NuGetTest/src/Modules/Lombiq.OSOCE.NuGet.TestModule/Lombiq.OSOCE.NuGet.TestModule.csproj
> +    <PackageReference Include="Lombiq.HelpfulLibraries" Version="4.1.0" />
From what I understand they are kinda unnecessary in libraries because NuGet automatically does package upgrade in the dependency tree as needed.

2022-05-05 14:58 UTC, Piedone commented on Readme.md
> +- If the sample project includes MVC actions, create a service that inherits from `MainMenuNavigationProviderBase` and adds front-end main menu items. The top level menu item should have the project'
Yeah, an absolute URL is what I meant as well.

2022-05-05 14:59 UTC, Piedone commented on NuGetTest/Directory.Build.props
> +    <NuGetBuild>true</NuGetBuild>
No, it's supposed to be a testbed of using the NuGet packages. `NuGetBuild` is when a NuGet package is being created and published.

2022-05-05 14:59 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.BaseTheme.Samples" Version="1.0.0-alpha.8" />
OK then.

2022-05-05 15:03 UTC, Piedone commented on NuGetTest/src/Modules/Lombiq.OSOCE.NuGet.TestModule/Controllers/AnalyzersTestController.cs
> +    // package.
I see, good.

2022-05-05 15:23 UTC, DAud-IcI commented on NuGetTest/Directory.Build.props
> +    <NuGetBuild>true</NuGetBuild>
Okay, then changed it to NuGetTest and used that in _/Directory.Build.props_ too.

2022-05-05 20:33 UTC, Piedone approved these changes

2022-05-05 22:15 UTC, Piedone approved these changes

2022-05-05 23:19 UTC, merged