OSOE-685: Fix menu styling in Lombiq.BaseTheme
Lombiq/Open-Source-Orchard-Core-Extensions pull request #559
Opened 2023-09-10 20:37 UTC by DAud-IcI

2023-09-12 15:39 UTC, Psichorex requested changes

2023-09-12 15:39 UTC, Psichorex commented on test/Lombiq.OSOCE.Tests.UI/Tests/VisualVerificationTests/VisualVerificationTests.cs
> +    public static readonly Size[] VisualVerificationSizes =
Will we use this anywhere else so that it can't be private?

2023-09-12 15:40 UTC, Psichorex commented
We have a conflict in Lombiq.GHA

2023-09-12 16:27 UTC, Psichorex commented
Do you know anything about the failing Windows build? It can be just drunk and it might go away if we re-run.

2023-09-13 09:06 UTC, DAud-IcI commented
It seems to be fine now.

2023-09-13 18:13 UTC, merged