NEST-423: Adding E-mail quota management module
Lombiq/Open-Source-Orchard-Core-Extensions pull request #564
Opened 2023-09-16 19:05 UTC by wAsnk

2023-09-19 12:59 UTC, DemeSzabolcs requested changes

2023-09-19 12:59 UTC, DemeSzabolcs commented on test/Lombiq.OSOCE.Tests.UI/Lombiq.OSOCE.Tests.UI.csproj
> +    <ProjectReference Include="..\..\src\Modules\Lombiq.Hosting.Tenants\Lombiq.Hosting.Tenants.EmailQuotaManagement.Tests.UI\Lombiq.Hosting.Tenants.EmailQuotaManagement.Tests.UI.csproj" />
~~Please also test the NuGet package here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/tree/dev/NuGetTest~~

Sorry, I see that you will do that after the approve.

2023-09-21 13:04 UTC, DemeSzabolcs approved these changes

2023-09-21 15:58 UTC, DemeSzabolcs requested changes

2023-09-21 15:58 UTC, DemeSzabolcs commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorEmailQuotaTests.cs
> +using Lombiq.Hosting.Tenants.EmailQuotaManagement.Tests.UI.Extensions;
You also need to add the same test to the NuGet solution: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/tree/issue/NEST-423/NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests

2023-09-21 17:14 UTC, wAsnk commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorEmailQuotaTests.cs
> +using Lombiq.Hosting.Tenants.EmailQuotaManagement.Tests.UI.Extensions;
Copy-paste programming at its finest. 😄

2023-09-21 20:19 UTC, DemeSzabolcs approved these changes

2023-09-21 20:57 UTC, merged