NEST-490: Double-logging in Application Insights for the same idle shutdown event
Lombiq/Open-Source-Orchard-Core-Extensions pull request #603
Opened 2023-10-31 13:46 UTC by wAsnk

2023-11-04 00:22 UTC, Piedone requested changes

2023-11-04 00:22 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +    .AddOrchardCoreApplicationInsightsTelemetry(configuration)
This causes the following empty telemetry to be attempted to be sent:

![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/1976647/efe4c370-0d10-474d-ab23-5e818cd85e0e)

This should rather be commented out by default with a comment, but enabled during UI testing but only for `ApplicationInsightsTrackingInOfflineOperationShouldWorkAsync()` (you can e.g. detect the `EnableOfflineOperation` config set there).

2023-11-04 00:22 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
In the appsettings file the `ApplicationInsights` section should rather be in the root, right?

2023-11-05 14:24 UTC, wAsnk commented on src/Lombiq.OSOCE.Web/Program.cs
Yeah it should be so it is unified. But the config would be picked up from here as well.

2023-11-05 14:25 UTC, wAsnk commented on src/Lombiq.OSOCE.Web/Program.cs
> +    .AddOrchardCoreApplicationInsightsTelemetry(configuration)
Hmm you are right it should be restricted somehow, but actually it would be better to add a check within the module, so it is only initiated when it is needed. Then the empty requests won't be sent.

2023-11-05 15:33 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
Please move it to the root, then.

2023-11-05 15:34 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +    .AddOrchardCoreApplicationInsightsTelemetry(configuration)
Even better, yes.

2023-11-06 14:35 UTC, wAsnk commented on src/Lombiq.OSOCE.Web/Program.cs
Yup, forgot to commit it.

2023-11-07 15:04 UTC, Piedone approved these changes

2023-11-07 23:43 UTC, Piedone approved these changes

2023-11-12 19:37 UTC, Piedone approved these changes

2023-11-12 19:59 UTC, merged