Set StopOnFail option to true un xunit.runner.json for Lombiq.OSOCE.Tests.UI
Lombiq/Open-Source-Orchard-Core-Extensions pull request #612
Opened 2023-11-14 11:10 UTC by tteguayco

This configuration file is ignored when running the tests from VisualStudio.

It takes the configuration file into consideration when running the tests via `dotnet test`.

A related issue was opened: https://github.com/xunit/visualstudio.xunit/issues/392

2023-11-14 20:04 UTC, DemeSzabolcs requested changes

2023-11-14 20:04 UTC, DemeSzabolcs commented on test/Lombiq.OSOCE.Tests.UI/xunit.runner.json
> +  "maxParallelThreads": 3,
Based on this code: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/test-dotnet/Set-XUnitMaxParallelThreads.ps1#L21-L34

it will use the `xunit.runner.json`'s value. Which is not good since we are overriding it here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/.github/workflows/build-and-test.yml#L20

2023-11-14 20:05 UTC, DemeSzabolcs commented
@tteguayco Please also create an [OSOCE](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/tree/dev) PR with the submodule changes.

2023-11-15 06:33 UTC, tteguayco commented on test/Lombiq.OSOCE.Tests.UI/xunit.runner.json
> +  "maxParallelThreads": 3,
Should it just be get rid of `maxParallelThreads`?

2023-11-15 06:37 UTC, tteguayco commented
Hey @DemeSzabolcs 

Isn't this the OSOCE PR? Also, it looks like `Lombiq.OSOCE.Tests.UI` where the new files are included, is not a git module.

2023-11-15 11:53 UTC, DemeSzabolcs commented
@tteguayco Oh so sorry. For some reason I thought this was in the UI testing submodule. All good, ignore that comment.

2023-11-15 12:24 UTC, DemeSzabolcs commented on test/Lombiq.OSOCE.Tests.UI/xunit.runner.json
> +  "maxParallelThreads": 3,
I think that would be the simplest, yes.

2023-11-15 13:49 UTC, closed without merging

2023-11-15 13:51 UTC, tteguayco commented on test/Lombiq.OSOCE.Tests.UI/xunit.runner.json
> +  "maxParallelThreads": 3,
Sorry @DemeSzabolcs, I think I mess up with this PR.

I just closed it and open this other one: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/616