Offer security checks in Lombiq.UITestingToolbox
Lombiq/Open-Source-Orchard-Core-Extensions pull request #614
Opened 2023-11-14 17:54 UTC by Piedone

2023-11-29 22:54 UTC, BenedekFarkas requested changes

2023-11-29 22:54 UTC, BenedekFarkas commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/SecurityScanningTests.cs
> +                configuration => configuration.ExcludeUrlWithRegex(".*:[0-9]+\\/.+"),
AFAIR Zap has a feature to get a quick report of a single URL. I'm not sure if that's available from UITT as it is now (I haven't finished the review of https://github.com/Lombiq/UI-Testing-Toolbox/pull/322), but it would be a useful feature to have.

2023-11-29 22:54 UTC, BenedekFarkas commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/SecurityScanningTests.cs
> +                sarifLog => sarifLog.Runs[0].Results.Count.ShouldBeLessThan(6)));
Is it 6 because we expect 5 findings to surface due to running the app locally? If so, please add an explanation and maybe some hints how to approach this.

2023-11-30 01:40 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/SecurityScanningTests.cs
> +                configuration => configuration.ExcludeUrlWithRegex(".*:[0-9]+\\/.+"),
It's ZAPit: https://www.zaproxy.org/blog/2023-10-18-zapit/. That's useful when you use ZAP interactively, in an exploratory phase of pentesting.

However, I don't see its value here: running a limited version of a ZAP scan during UI testing just for a single page is of very little use to ensure that your app is still healthy and recent code changes didn't introduce something bad.

It's also quite an isolated feature that doesn't make use of the same configuration, nor can produce the same kind of reports that a normal scan does, which would need us to add a parallel vertical for just it (to configure and run it, and to assert on its results) too.

Initializing ZAP also takes more time than what would warrant just a single-page scan.

This test here is completely atypical, something that should basically only happen here, so we can make sure the NuGet package works (it could also run a full scan but that would be a waste of time).

2023-11-30 01:42 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/SecurityScanningTests.cs
> +                sarifLog => sarifLog.Runs[0].Results.Count.ShouldBeLessThan(6)));
Yes, but what do you mean by hints on how to approach this?

2023-11-30 10:12 UTC, BenedekFarkas commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/SecurityScanningTests.cs
> +                configuration => configuration.ExcludeUrlWithRegex(".*:[0-9]+\\/.+"),
OK, yeah, I agree that under these conditions it's not worth it and not representative enough of the health of the feature.

2023-11-30 10:18 UTC, BenedekFarkas commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/SecurityScanningTests.cs
> +                sarifLog => sarifLog.Runs[0].Results.Count.ShouldBeLessThan(6)));
Let's say that due to an Orchard or ZAP update this test breaks. Fixing it could be as simple as increasing the number, but might be down to something more complex that needs to be addressed in UITT, so I'd suggest leaving a note here about that, so that it's not glossed over.

2023-12-04 18:31 UTC, BenedekFarkas approved these changes

2023-12-05 17:26 UTC, merged