OSOE-743: Cancel ongoing runs of long-running workflows under a PR when new changes are pushed
Lombiq/Open-Source-Orchard-Core-Extensions pull request #630
Opened 2023-11-28 10:24 UTC by BenedekFarkas

2023-12-02 00:53 UTC, Piedone approved these changes

2023-12-06 14:07 UTC, BenedekFarkas commented on .github/workflows/build-and-test.yml
All the changes in this file are temporary for testing this PR.

2023-12-07 18:53 UTC, Piedone requested changes

2023-12-07 18:53 UTC, Piedone commented on .github/workflows/build-and-test-windows.yml
> +      parent-job-name: "root-solution-larger-runners"
Note my comment here: https://github.com/Lombiq/GitHub-Actions/pull/296#discussion_r1419467047

2023-12-10 14:38 UTC, merged