Updating LGHA.
Lombiq/Open-Source-Orchard-Core-Extensions pull request #637
Opened 2023-12-05 14:37 UTC by Psichorex

2023-12-05 15:18 UTC, Psichorex commented
@Piedone A UI test is failing most probably because the docker now pulls and uses sql-server-2022 but 
https://github.com/Lombiq/UI-Testing-Toolbox/blob/88ec8caf6940e7f1445fe4993701fc0ce5ce5e48/Lombiq.Tests.UI/Services/SqlServerManager.cs#L173
This line receives sql2019 as a container name
`Command: docker cp sql2019:/data/Snapshots/Database.bak /home/runner/actions-runner/_work/Open-Source-Orchard-Core-Extensions/Open-Source-Orchard-Core-Extensions/test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.Samples/bin/Debug/net6.0/Temp/SetupSnapshot/SqlServer-57163436/Database.bak`
Where it is exactly set what is the docker image name that the linux env will use? Because I wasn't able to find it yet.

2023-12-05 16:11 UTC, Piedone commented
I don't know from the top of my head, I'd need to run it with the debugger and figure out from the call stack too.

2023-12-06 19:38 UTC, dministro requested changes
Please merge from dev

2023-12-07 17:22 UTC, dministro approved these changes

2023-12-10 20:56 UTC, dministro requested changes
Next time if you change something Windows related please adjust `build-and-test-windows` workflow accordingly.

The Windows workflow is failing. See: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7160130952/job/19494163261#step:8:95

2023-12-11 11:49 UTC, Psichorex commented
> Next time if you change something Windows related please adjust `build-and-test-windows` workflow accordingly.
> 
> The Windows workflow is failing. See: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7160130952/job/19494163261#step:8:95

@dministro As far as I see it's not failing because of I didn't change `build-and-test-windows` because that only has references for other workflows and if I had to change the references there `verify-gha-refs` should have caught that.

I changed the refs though and it is still failing. 
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/6541cfc1-8836-4f41-b28f-f06280ea98e6)
It's the `Wait-SqlServer` that is failing after according to logs sqlserver2022 being successfully installed.

2023-12-11 13:36 UTC, Psichorex commented
Yes so I switched back to `sql-server-express` here:
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/7657c651-6194-49b8-a668-bf5129c66c92)
And the CI is not failing anymore. Any ideas what could be causing this?

2023-12-11 20:21 UTC, dministro commented
> Yes so I switched back to `sql-server-express` here: ![image](https://private-user-images.githubusercontent.com/92299130/289552118-7657c651-6194-49b8-a668-bf5129c66c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjYzMjYsIm5iZiI6MTcwMjMyNjAyNiwicGF0aCI6Ii85MjI5OTEzMC8yODk1NTIxMTgtNzY1N2M2NTEtNjE5NC00OWI4LWE2NjgtYmY1MTI5YzY2YzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDIwMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNDAyNWMwOTU0NDgxMDYwNDA5NjljYmFjNjZjNGUzMmEzNzYyMmJkOWFmOTRmNDQ2M2U4MmM1ZjViMmUzMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4g4ox0YkgHWqnI30AIroKf01CLVZhzRNYmcOBVEWRnY) And the CI is not failing anymore. Any ideas what could be causing this?

Did you tried to install and run the SqlServer locally using choco?

2023-12-12 13:13 UTC, Psichorex commented
> > Yes so I switched back to `sql-server-express` here: ![image](https://private-user-images.githubusercontent.com/92299130/289552118-7657c651-6194-49b8-a668-bf5129c66c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjYzMjYsIm5iZiI6MTcwMjMyNjAyNiwicGF0aCI6Ii85MjI5OTEzMC8yODk1NTIxMTgtNzY1N2M2NTEtNjE5NC00OWI4LWE2NjgtYmY1MTI5YzY2YzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDIwMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNDAyNWMwOTU0NDgxMDYwNDA5NjljYmFjNjZjNGUzMmEzNzYyMmJkOWFmOTRmNDQ2M2U4MmM1ZjViMmUzMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4g4ox0YkgHWqnI30AIroKf01CLVZhzRNYmcOBVEWRnY) And the CI is not failing anymore. Any ideas what could be causing this?
> 
> Did you tried to install and run the SqlServer locally using choco?

I tried to install with both commands but `sql-server-2022` fail for some reason. That my be a local issue but `sql-server-express` worked for the first time. So at this point again I don't know what exactly causes this to fail because the logs show that sql-server-2022 command did install the instance.

2023-12-15 10:52 UTC, Psichorex commented
@Piedone I can't really determine why the `sql-server-2022` command is failing and why `sql-server-express` is working without anything else being changed. We could revert to `sql-server-express` and maybe extract this into another issue to investigate whether the other command is failing. I didn't find anything in the documentation that would indicate a dependency or anything.

2023-12-15 15:09 UTC, Piedone commented
So do you mean that we'd have SQL Server Express 2022 (it's important that it'll also be v2022) installed instead of SQL Server Developer 2022? I'm OK that, but Jocó?

2023-12-15 17:00 UTC, Psichorex commented
> So do you mean that we'd have SQL Server Express 2022 (it's important that it'll also be v2022) installed instead of SQL Server Developer 2022? I'm OK that, but Jocó?

This command `choco install sql-server-express` is dedicated for SQL SERVER EXPRESS 2022 according to the docs. So it is surely a 2022 version.

2023-12-15 17:34 UTC, Piedone commented
That's because that's the latest version currently. Also use `--version` like they show for 2019 [here](https://community.chocolatey.org/packages/sql-server-express/2019.20200409).

2023-12-17 12:24 UTC, dministro commented
> I can't really determine why the `sql-server-2022` command is failing and why `sql-server-express` is working without anything else being changed. 

@Psichorex Did you tried to use `(local)` as server name without `\SQLEXPRESS` in connection parameters/strings? The `SQLServer Developer Edition` creates an instance with a name something like `MSSQLSERVER` which is the default so you don't have to specify the instance name in the server name. This means the instance with name `SQLEXPRESS` does not exists which can be the root cause of the issue.

> We could revert to `sql-server-express` and maybe extract this into another issue to investigate whether the other command is failing. I didn't find anything in the documentation that would indicate a dependency or anything.

If you already tried to adjust connection parameters in `Wait-SqlServer.ps1` and `Invoke-SolutionTests.ps1` like above and doesn't work, then please create an issue for it and describe what is the problem here exactly what you have tried, etc.

If you have not tried please give it a try.

2023-12-19 11:05 UTC, Psichorex commented
So far I tried these:
`$connectionStringStem = 'Server=.\MSSQLSERVER;Database=LombiqUITestingToolbox_{{id}};Integrated Security=True'`
`$connectionStringStem = 'Server=.\(local);Database=LombiqUITestingToolbox_{{id}};Integrated Security=True'`
And both failed the same way. As for SS2022 Dev as you mentioned the default name should be MSSQLSERVER so if that doesn't I suspect it has to do with something else.

2023-12-19 18:36 UTC, Psichorex commented
> > I can't really determine why the `sql-server-2022` command is failing and why `sql-server-express` is working without anything else being changed.
> 
> @Psichorex Did you tried to use `(local)` or `.` as server name without `\SQLEXPRESS` in connection parameters/strings? IfI remember well the `-S` command line parameter default value is `.` for `sqlcmd` so you can simple remove it from the parameter list. The `SQLServer Developer Edition` creates an instance with a name something like `MSSQLSERVER` which is the default so you don't have to specify the instance name in the server name. This means the instance with name `SQLEXPRESS` does not exists which can be the root cause of the issue.
> 
> > We could revert to `sql-server-express` and maybe extract this into another issue to investigate whether the other command is failing. I didn't find anything in the documentation that would indicate a dependency or anything.
> 
> If you already tried to adjust connection parameters in `Wait-SqlServer.ps1` and `Invoke-SolutionTests.ps1` like above and doesn't work, then please create an issue for it and describe what is the problem here exactly what you have tried, etc.
> 
> If you have not tried please give it a try.

I tried like every combination, you can see that in the last commits but non of them seem to be working. So I am reverting for sql-express with version and separate this issue.

2023-12-19 18:51 UTC, dministro commented
Please try `Server=.;` in Windows connection string same like the Linux one. No `Server=.\.;`, `\.` looks weird and can be the root cause of failing tests [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7261854686/job/19783865013#step:10:2744), please read the log message!

![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/15349881/01f3ead8-8149-4470-8f45-1a7856caf645)
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/15349881/c54adc5b-cfb3-4d5c-86bd-013e0385d195)

2023-12-19 19:25 UTC, dministro requested changes

2023-12-19 19:25 UTC, dministro commented on tools/Lombiq.Analyzers.PowerShell
Why was this changed?

2023-12-20 12:43 UTC, Psichorex commented on tools/Lombiq.Analyzers.PowerShell
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/095c5087-1b70-45e6-b49d-ca703117422e)

There is nothing to compare so this is probably a bug. This repo is no branch in my Git Extensions so I didn't touch it.

2023-12-22 09:38 UTC, dministro commented on tools/Lombiq.Analyzers.PowerShell
Then, please insert the link - where you reported/found this bug - here. Or revert.

2023-12-23 13:47 UTC, Psichorex commented on tools/Lombiq.Analyzers.PowerShell
@dministro The dev checkout fall behind on my branch most probably due to a pnpm-lock file preventing the updated checkout. I checked out the latest dev in the submodule and the file change disappeared.

2023-12-30 17:10 UTC, dministro approved these changes

2023-12-31 11:11 UTC, merged