OSOE-188: YAML Linting
Lombiq/Open-Source-Orchard-Core-Extensions pull request #647
Opened 2023-12-16 07:07 UTC by tteguayco

Enabling linting of YAML files from:
* GitHub Actions
* Local development

2023-12-27 17:29 UTC, Piedone commented on .trunk/configs/.yamllint.yaml
Can't we have this shared in LGHA?

2023-12-27 17:29 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      search-path: '.github'
This doesn't include submodules, right? We need to check those too.

2023-12-27 17:29 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      machine-types: "['ubuntu-22.04']"
Let's have this as the default there instead. Or rather, we don't need this to be configurable, can be like in the simpler workflows, e.g. https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/publish-nuget.yml#L64.

2023-12-28 11:39 UTC, tteguayco commented on .trunk/configs/.yamllint.yaml
Yes, we can. I've pushed a new change in `.trunk/trunk.yaml` that uses the `yamllint` rules file (`.yamllint.yaml`) from LGHA on OSOCE.

We can override any of the `yamllint` definitions as needed. Default definitions can be found [here](https://github.com/trunk-io/plugins/blob/main/linters/yamllint/plugin.yaml).

2023-12-28 13:38 UTC, tteguayco commented on .github/workflows/build-and-test.yml
> +      search-path: '.github'
Updated to lookup yaml files recursively. I opened this PR [here](https://github.com/Lombiq/PowerShell-Analyzers/pull/38) for Lombiq.Analyzers.PowerShell too, since the linter compains for one of its files:

2023-12-28 14:58 UTC, Piedone commented on .trunk/configs/.yamllint.yaml
Great!

2023-12-28 14:58 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      search-path: '.github'
Thanks!

2024-01-05 16:57 UTC, DemeSzabolcs requested changes

2024-01-05 16:57 UTC, DemeSzabolcs commented on .github/YAMLLinting.md
> +YAML files for GitHub Actions can be linted using `yamllint`. Please refer to [this documentation in Lombiq.Github.Actions](/tools/Lombiq.GitHub.Actions/Docs/Workflows/Productivity/YamlLinting.md) to
The link is not working, I believe because Lombiq.GitHub.Actions is used as a submodule, so you have to reference it directly.

2024-01-05 16:57 UTC, DemeSzabolcs commented on .trunk/trunk.yaml
> +        - yamllint@1.33.0
Add a newline at the end of this file.

2024-01-05 17:10 UTC, DemeSzabolcs commented on .trunk/trunk.yaml
> +        - run: yamllint -c ./tools/Lombiq.GitHub.Actions/.trunk/configs/.yamllint.yaml -f parsable ${target}
Could you please explain to me why we need this command here but not in Lombiq.GitHubActions? https://github.com/Lombiq/GitHub-Actions/pull/302/files#diff-45a5a35dd7ad9a52d0fd3540f6c0d16a763575de51cc9a0a6c6f6a9f1da62ecdR20

2024-01-08 06:55 UTC, tteguayco commented on .trunk/trunk.yaml
> +        - run: yamllint -c ./tools/Lombiq.GitHub.Actions/.trunk/configs/.yamllint.yaml -f parsable ${target}
`.trunk/configs/.yamllint.yaml` is the default path, so the one used for LGHA.

Since for OSOCE we want to use the same yamllint rules file located in LGHA as asked [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/647#discussion_r1437167309), we do so via this line.

2024-01-08 14:09 UTC, tteguayco commented on .github/YAMLLinting.md
> +YAML files for GitHub Actions can be linted using `yamllint`. Please refer to [this documentation in Lombiq.Github.Actions](/tools/Lombiq.GitHub.Actions/Docs/Workflows/Productivity/YamlLinting.md) to
Would it work with this link?
```
https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-188/Docs/Workflows/Productivity/YamlLinting.md
```

If so, I think we should replace `OSOE-188` by `dev` once this work is merged.

2024-01-09 09:54 UTC, tteguayco commented
Hi @DemeSzabolcs ,

Any idea why the pipeline run is red? It looks like it's complaining about a file that hasn't been touched as part of this PR.

2024-01-09 16:21 UTC, DemeSzabolcs commented
Hello @tteguayco,

It seems like the problem is here: https://github.com/Lombiq/GitHub-Actions/pull/302/files#diff-2c84a15674c9719659b4113e6b1a691c83185924812140d454315e836b5b5b9eR21

You can read the summary here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7448559535/attempts/1?pr=647

Though I don't see the exact mentioned problem. I think Lombiq.GitHubActions is not updated to the latest OSOCE-188 branch in this PR, thus it's not on this commit yet: 
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/80963259/7e98f853-335a-43b2-b2e0-b0e17838328d)

2024-01-16 13:18 UTC, tteguayco commented on .github/YAMLLinting.md
> +YAML files for GitHub Actions can be linted using `yamllint`. Please refer to [this documentation in Lombiq.Github.Actions](/tools/Lombiq.GitHub.Actions/Docs/Workflows/Productivity/YamlLinting.md) to
Does it work like this, @DemeSzabolcs?

2024-01-16 13:38 UTC, tteguayco commented on .github/workflows/build-and-test.yml
> +      search-path: .
Yeah, it will be changed to `@dev.`

2024-01-17 19:26 UTC, DemeSzabolcs commented on .github/YAMLLinting.md
> +YAML files for GitHub Actions can be linted using `yamllint`. Please refer to [this documentation in Lombiq.Github.Actions](/tools/Lombiq.GitHub.Actions/Docs/Workflows/Productivity/YamlLinting.md) to
I will replace it before the merge.

2024-01-17 19:27 UTC, DemeSzabolcs approved these changes

2024-01-26 20:41 UTC, merged