LMBQ-276: Improving WithEditor
Lombiq/Open-Source-Orchard-Core-Extensions pull request #653
Opened 2023-12-21 16:15 UTC by Psichorex

LMBQ-276

2023-12-23 16:32 UTC, MZole requested changes

2023-12-23 16:32 UTC, MZole commented on src/Libraries/Lombiq.HelpfulLibraries
There are a couple of places where this new Enum could be used already, please use it where we can, so others can find this easier and start using this as well.

2023-12-26 13:41 UTC, Psichorex commented on src/Libraries/Lombiq.HelpfulLibraries
Addressed.

2023-12-27 17:54 UTC, MZole requested changes

2023-12-27 17:54 UTC, MZole commented on src/Modules/Lombiq.TrainingDemo
Open a PR for this, please.

2023-12-27 17:54 UTC, MZole commented on src/Libraries/Lombiq.HelpfulLibraries
There should be also an example in HE `SiteTextMigrations`.

2023-12-29 00:49 UTC, MZole approved these changes

2023-12-29 16:54 UTC, MZole approved these changes

2023-12-30 22:05 UTC, merged