Security and ZAP improvements
Lombiq/Open-Source-Orchard-Core-Extensions pull request #657
Opened 2023-12-27 23:36 UTC by sarahelsaig

2023-12-28 19:14 UTC, Piedone requested changes
Please also configure the recommended security settings in `Program` here too. Then, the UITT samples may need to be adapted too.

2023-12-29 20:43 UTC, Piedone commented
Sorry about CodeRabbit, didn't mean to enable it for all PRs.

2023-12-29 20:49 UTC, sarahelsaig commented
![maxresdefault](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/4007293/823d4f17-851a-4f9c-af2c-ea09aa8dbb06)

2023-12-29 21:02 UTC, Piedone commented
:D

@coderabbitai pause

2024-01-11 22:06 UTC, Piedone requested changes

2024-01-11 22:06 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      timeout-minutes: 30
The runtime of the workflows didn't change, why are these timeout changes necessary?

2024-01-12 00:57 UTC, sarahelsaig commented on .github/workflows/build-and-test.yml
> +      timeout-minutes: 30
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/4007293/64e64048-4817-4030-a0d6-4ed6c50ad9a9)

```suggestion
      timeout-minutes: 20
```

2024-01-14 20:20 UTC, Piedone requested changes

2024-01-14 20:20 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Program.cs
> +                    FeatureIds.Base,
This isn't a really unique class name, so why move the namespace specifier to an import statement?

2024-01-14 21:40 UTC, sarahelsaig commented on src/Lombiq.OSOCE.Web/Program.cs
> +                    FeatureIds.Base,
It happens automatically when you organize the usings with Rider/ReSharper. To prevent future incidents I'll use a namespace alias.

2024-01-14 23:01 UTC, Piedone approved these changes

2024-01-15 15:05 UTC, merged