OSOE-73  List of projects in the root Readme
Lombiq/Open-Source-Orchard-Core-Extensions pull request #66
Opened 2022-03-08 16:16 UTC by mihalybecsei

OSOE-73

2022-03-08 17:48 UTC, Piedone requested changes

2022-03-08 17:48 UTC, Piedone commented on Readme.md
> +- The list of included projects are added at "Included Projects in Lombiq's Open-Source Orchard Core Extensions" section of this readme.
Formulate this in the imperative mood like the others, asking the developer to keep that section updated.

2022-03-08 17:48 UTC, Piedone commented on Readme.md
> +## Included Projects in Lombiq's Open-Source Orchard Core Extensions
Move this above "Samples and Recipes".

2022-03-08 17:48 UTC, Piedone commented on Readme.md
> +#### [Lombiq.HelpfulLibraries](https://github.com/Lombiq/Helpful-Libraries/tree/dev)
As asked in the issue, use a hierarchical list, not titles (this needs to be a lot more compact).

2022-03-08 17:48 UTC, Piedone commented on Readme.md
> +When adding this project to the solution it will initialize a *node_modules* folder two levels up in the folder hierarchy assuming that it will be a common root folder for all the other *package.json
Don't add instructions like this. All the text for each of the projects should be just a quick overview, a single paragraph. This is most possible the first paragraph of each Readme.

2022-03-08 17:48 UTC, Piedone commented on Readme.md
> +#### [Lombiq.OSOCE.Tests.UI](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/tree/dev/test/Lombiq.OSOCE.Tests.UI)
This is not a submodule and thus necessary to add.

2022-03-08 17:48 UTC, Piedone commented on Readme.md
> +### test
```suggestion
### Testing
```

2022-03-08 17:48 UTC, Piedone commented on Readme.md
> +### tools
```suggestion
### Tools
```

2022-03-08 23:37 UTC, Piedone commented on Readme.md
> +- The list of included projects are added at "Included Projects in Lombiq's Open-Source Orchard Core Extensions" section of this readme.
This is not properly addressed.

2022-03-08 23:43 UTC, Piedone requested changes

2022-03-08 23:43 UTC, Piedone commented on Readme.md
> +* Librarires
Use bullet points consistently, `-` everywhere.

2022-03-08 23:43 UTC, Piedone commented on Readme.md
> +## Included Projects in Lombiq's Open-Source Orchard Core Extensions
```suggestion
## Included Projects
```

2022-03-08 23:43 UTC, Piedone commented on Readme.md
> +`AddRestEaseHttpClient` Adds a typed HTTP client to the service collection using RestEase.
```suggestion
  - [Lombiq.HelpfulLibraries.RestEase](https://github.com/Lombiq/Helpful-Libraries/tree/dev/Lombiq.HelpfulLibraries.RestEase): Adds a typed HTTP client to the service collection using RestEase.
```

2022-03-09 13:54 UTC, Piedone commented on Readme.md
> +## Included Projects in Lombiq's Open-Source Orchard Core Extensions
You can commit such suggestions directly from GitHub, which makes it easier to apply them, as well as to review them (since then the convos can be auto-resolved).

2022-03-09 13:56 UTC, Piedone commented on Readme.md
> +## Included Projects in Lombiq's Open-Source Orchard Core Extensions
Especially since then you don't need to eyeball the suggested changes so you won't make mistakes while applying them, as it happened under https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/66#discussion_r822167886.

2022-03-09 13:56 UTC, Piedone commented on Readme.md
> +`AddRestEaseHttpClient` Adds a typed HTTP client to the service collection using RestEase.
There's still an unneeded line break.

2022-03-09 13:57 UTC, Piedone commented on Readme.md
> +- The list of included projects are added at "Included Projects in Lombiq's Open-Source Orchard Core Extensions" section of this readme.
Still not properly addressed.

2022-03-09 13:58 UTC, Piedone requested changes
See follow-up comments under two open convos.

2022-03-09 14:11 UTC, mihalybecsei commented on Readme.md
> +`AddRestEaseHttpClient` Adds a typed HTTP client to the service collection using RestEase.
I kept it just to be consistent with the rest of the added list. Am I correct, that it's something to fix for every link?

2022-03-09 15:18 UTC, Piedone commented on Readme.md
> +`AddRestEaseHttpClient` Adds a typed HTTP client to the service collection using RestEase.
If other list items have an unnecessary line break between the project name and the description then the others need to be fixed too.

2022-03-10 19:28 UTC, Piedone commented on Readme.md
> +- The list of included projects are added at "Included Projects in Lombiq's Open-Source Orchard Core Extensions" section of this readme.
Still not. As I said, "Formulate this in the imperative mood like the others, asking the developer to keep that section updated." The current "See "Included Projects" section of this readme for an overview of this project's modules." text doesn't ask the developer to keep the section updated (BTW it's "Readme"). This shouldn't be a gentle pointer for more info but rather something that you have to do, like all the other points in this section.

2022-03-10 19:30 UTC, Piedone requested changes
See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/66#discussion_r824083613

2022-03-10 20:03 UTC, mihalybecsei commented on Readme.md
> +- The list of included projects are added at "Included Projects in Lombiq's Open-Source Orchard Core Extensions" section of this readme.
I'm ashamed to admit, but I absolutely glanced over the purpose of the section, and used it as a note of the addition. I will correct it asap.

2022-03-10 20:21 UTC, merged