OSOE-751: Upgrade to Orchard Core 1.8
Lombiq/Open-Source-Orchard-Core-Extensions pull request #673
Opened 2024-01-18 10:46 UTC by Psichorex

OSOE-751

2024-01-29 12:02 UTC, Psichorex commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorUIKitShowcaseTests.cs
> +                        !error.ContainsOrdinalIgnoreCase("Redundant role \"button\" on <button>"));
Reason: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/638#issuecomment-1913566145

2024-01-31 14:14 UTC, Psichorex commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorPrivacyTests.cs
> +                        .Where(error => !error.ContainsOrdinalIgnoreCase("Prefer to use the native <button> element"));
Invalid HTML coming from Orchard Core so we have to remove the log.

2024-02-01 00:38 UTC, Piedone requested changes

2024-02-01 00:38 UTC, Piedone commented on src/Modules/Lombiq.HelpfulExtensions
This is missing for a lot of projects: https://github.com/OrchardCMS/OrchardCore/pull/14806

2024-02-01 00:38 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorPrivacyTests.cs
> +                        .Where(error => !error.ContainsOrdinalIgnoreCase("Prefer to use the native <button> element"));
Please open an issue about this and link it here.

2024-02-01 00:38 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorUIKitShowcaseTests.cs
> +                        !error.ContainsOrdinalIgnoreCase("Redundant role \"button\" on <button>"));
Please open an issue about this and link it here.

2024-02-01 00:38 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BlogBaseThemeTests.cs
> +                await context.EnableFeatureDirectlyAsync("Lombiq.HelpfulExtensions.ResourceManagement");
The decorator doesn't do anything with jQuery anymore.

2024-02-01 10:43 UTC, Psichorex commented
https://github.com/OrchardCMS/OrchardCore/issues/15222

2024-02-01 14:20 UTC, Piedone commented
Always add such issues links for workarounds in the code. And keep to https://lombiq.atlassian.net/wiki/spaces/OCORE/overview (I added it to our GitHub project now).

2024-02-01 14:59 UTC, Psichorex commented on src/Modules/Lombiq.HelpfulExtensions
Do we need this on all `<label>` ? Or just in the Base Theme and DataTables where bootstrap is present?

2024-02-01 15:05 UTC, Piedone commented on src/Modules/Lombiq.HelpfulExtensions
All admin labels and all labels on the frontend where BS is used, but in practice this means all labels.

2024-02-04 20:57 UTC, Piedone requested changes

2024-02-04 20:57 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
Upgrade all Microsoft.* packages that are related to a .NET version too. E.g. Microsoft.AspNetCore.Mvc.Testing [has a version for each .NET version](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing/), using the same version number as .NET. Such affected packages all do this.

2024-02-05 23:32 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
These remain:

![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/1976647/0825ac52-de03-4de0-92ab-00c8156db169)

2024-02-05 23:35 UTC, Piedone requested changes
See https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/673#discussion_r1479051780

2024-02-06 07:02 UTC, Psichorex commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
I thought only those needed to be upgraded that were specifically 7.0.0 and their latest is 8.0.0

2024-02-06 19:46 UTC, Piedone approved these changes

2024-02-13 14:31 UTC, Psichorex commented
https://github.com/Lombiq/NodeJs-Extensions/actions/runs/7887385794
This happens when trying to publish to NuGet.
As far as I am concerned collection literals are not a preview feature. I didn't find a corresponding part of the https://lombiq.atlassian.net/wiki/spaces/DEV/pages/786857987/Managing+releases+of+open-source+projects whether what to do if a .NET upgrade happens for instance.
Do you have any idea or suggestions how to overcome this?

2024-02-13 14:33 UTC, Piedone commented
NE targets `netstandard2.0` and should keep doing that for compatibility with .NET Framework projects. You can't use new C# features there.

2024-02-13 14:38 UTC, Psichorex commented
> NE targets `netstandard2.0` and should keep doing that for compatibility with .NET Framework projects. You can't use new C# features there.

That's what I was going to ask this moment. Whether NE actually brings the langVersion from the global setting. 
BUT this error is not present locally. Which means if I don't use collection literals it will induce warnings in the solution. 
So shall we supress these warnings of manipulate that rule?

2024-02-13 15:08 UTC, Piedone commented
You can also specify `<langVersion>` just in the csproj of NE, with a comment on why that's necessary, to avoid the warnings.

2024-02-13 17:23 UTC, Psichorex commented
The default `<LangVersion>` for netstandard2.0 is C# 7.3. But that also doesn't include file scoped namespaces. So what language version shall we use there? Btw namespaces were introduced in C# 10 which requires .NET 6 so I don't even understand how is that usable in a netstandard2.0 project and the CI didn't warn us before about that one.

2024-02-13 17:48 UTC, Piedone commented
Please use what works with netstandard2.0. But I don't think you need to do a release here, since only the sample is updated, and this project doesn't depend on OC.

2024-02-14 13:49 UTC, Psichorex commented
> Please use what works with netstandard2.0. But I don't think you need to do a release here, since only the sample is updated, and this project doesn't depend on OC.

I adjusted the syntaxes used in `Lombiq.NodeJs.Extensions` you can see the changes in the the PR:https://github.com/Lombiq/NodeJs-Extensions/pull/91/files#diff-9cf2858bf3bd132496ec78748544fe8bb1e628b8244b6e65be188fa6f774b5de
But as you said in this case I won't actually do a release here because only the `.Tests` project is modified by the .NET upgrade and it is OC independent.

2024-02-14 14:30 UTC, Piedone commented
Thanks!

2024-02-14 18:23 UTC, Psichorex commented
CI Tests are failing due to this:
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/5eed46ab-6b55-4561-911d-f98c2e5964f2)

I will increase the timeout now but I have a feeling that this shouldn't be increased.
Does .NET 8 have maybe anything to do with increased timeout demands? We need them both on windows and ubuntu now on the larger runners. I am not an expert in this field I haven't yet looked into timeout values and why we need them. All I know is that you have mentioned it should be less than `720000` on larger runners.

2024-02-14 18:31 UTC, Piedone commented
That timeout is already large and shouldn't be increased without adding any further tests. Most possibly a test is flaky or downright failing.

2024-02-14 18:48 UTC, Psichorex commented
> That timeout is already large and shouldn't be increased without adding any further tests. Most possibly a test is flaky or downright failing.

Maybe related: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/694 but here nothing was touched that should cause such a case. It was derived from latest stable dev and only a PS1 script was changed.

2024-02-14 19:12 UTC, Psichorex commented
Also this: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7905683913?pr=673
I see that this was recently fixed but it seems that the fix doesn't cover all cases. Correspoding issue is OSOE-771https://lombiq.atlassian.net/jira/software/c/projects/OSOE/boards/36?selectedIssue=OSOE-771

2024-02-14 19:14 UTC, Piedone commented
So, it's indeed a failing test. You need to fix that (looks like an incompatibility that 1.8 brought) and revert the timeout values.

2024-02-14 19:15 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -        !(logEntry.Message.ContainsOrdinalIgnoreCase("/OrchardCore.Resources/Scripts/jquery.js?v=") &&
This should be more specific than that, since this'd ignore all jQuery exceptions.

2024-02-14 19:22 UTC, Psichorex commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -        !(logEntry.Message.ContainsOrdinalIgnoreCase("/OrchardCore.Resources/Scripts/jquery.js?v=") &&
I just merged this code into my branch and my CI started failing. 
I deleted `3138:6 Uncaught` because my CI dropped `3137:6 Uncaught` so it didn't do anything.

2024-02-14 19:34 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -        !(logEntry.Message.ContainsOrdinalIgnoreCase("/OrchardCore.Resources/Scripts/jquery.js?v=") &&
What's the full error message currently and why? Investigate it.

2024-02-14 19:52 UTC, Psichorex commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -        !(logEntry.Message.ContainsOrdinalIgnoreCase("/OrchardCore.Resources/Scripts/jquery.js?v=") &&
The error message is the same for what you have added this log filter in OSOE-771. The only difference is that filter is not filtering enough on my branch and it failed. I probably also have some problems with the `dotnet-dump tool` it seems that it also has a .NET version tied versioning so I updated that aswell. Now I am waiting for the CI.

2024-02-14 19:53 UTC, Psichorex commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -        !(logEntry.Message.ContainsOrdinalIgnoreCase("/OrchardCore.Resources/Scripts/jquery.js?v=") &&
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/5b74c820-6160-46b4-8916-825a28c1661d)
This was the cause of the failure by the way. Which in my opinion should have been removed by the filter.

2024-02-14 19:55 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -        !(logEntry.Message.ContainsOrdinalIgnoreCase("/OrchardCore.Resources/Scripts/jquery.js?v=") &&
This is the same error message as under OC 1.7, the string you removed is right there at the top.

I trust you to handle this from this point, so I'll only get back on the next review.

2024-02-15 16:47 UTC, Psichorex commented
Do you know how to increare the test case timeout? 
https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7914125012/attempts/1#ra3eb2a264s18
Walkthorugh tests are timing out and I am not getting a proper error why is it actually failing.
For me locally the test passes at the first run.

2024-02-15 17:17 UTC, Piedone commented
This is a different timeout, some browser command doesn't complete, i. e. the test completes but fails. See the stack trace in the error message and download the failure dump.

2024-02-15 18:12 UTC, Psichorex commented
> This is a different timeout, some browser command doesn't complete, i. e. the test completes but fails. See the stack trace in the error message and download the failure dump.

The part that always fails is somewhere at the `Deployment plan` section.
I now went thorugh the logs and found the following:
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/ed9459bb-5495-4b35-872b-1821ad3bb8a4)
This part is recursively appearing until the test times out.
And by the screenshot it uploads it seems that the popup modal is appearing in such a way that it is covering the select button of the OC modal's card element thus I can't click on it gets stuck?
![64](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/59ca7ada-27a3-4458-a888-b7147bce9ec6)

2024-02-15 19:36 UTC, Piedone commented
Then, apparently that UI changed in 1.8 and you have to change the selector the Walkthroughs module uses to display the tooltip not to hide it.

2024-02-16 10:37 UTC, Psichorex commented
> Then, apparently that UI changed in 1.8 and you have to change the selector the Walkthroughs module uses to display the tooltip not to hide it.

The main problem is that he javascript that the module uses to render that tooltip is fine. Locally it is working as it should be. 
See:

`javascript`:
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/ccb5ac39-4e7d-447e-b596-52db2ef8ef33)
Local `data-popper-placement="top"`:
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/a71dfea8-0c98-4a0d-bc2e-64531465ecc6)
### CI LOGS
`data-popper-placement="bottom"`
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/01c40103-4a29-43b5-99ad-c91af6a25259)
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/82d7d8f8-3081-48c3-8bbc-079b19495bf0)

At this point I have no clue why does the CI env change the render position from top to bottom as the script clearly says it should be top. 
I checked the button element on both CI and Local and they are exactly the same.
Local:
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/8ba92a4d-2b9e-4a78-80c7-ba30c650723e)
CI:
![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/92299130/8fff5e09-175a-4e3e-936c-c8e3add58c0c)

2024-02-16 12:13 UTC, Psichorex commented
I changed it from top to right so that window size won't really affect it and it works now.

2024-02-20 14:13 UTC, Piedone requested changes

2024-02-20 14:13 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +  </ItemGroup>
This should be done in the Directory.Build.props file, not every project.

2024-02-20 14:13 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Helpers/AssertBrowserLogHelpers.cs
> +    public static readonly Func<HtmlValidationResult, Task> AssertHtmlErrorsAreEmpty = async errors =>
None of them assert the log is empty, use a more descriptive name.

2024-02-20 14:13 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorChartJsTests.cs
I don't see the reason to do these formatting changes is any of the test classes.

2024-02-20 14:13 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> +            });
Why rearrange this? Note that the custom message in the assertion (second parameter of `ShouldNotContain()`) is now also removed, making debugging harder. Same for this test in the root solution.

2024-02-20 14:13 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> +                        !logEntry.Message.ContainsOrdinalIgnoreCase("/OrchardCore.Resources/Scripts/jquery.js?v=") &&
As I said under https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/673#discussion_r1489947345, this is not specific enough. This would ignore all jQuery errors. Same for this test in the root solution.

2024-02-20 16:43 UTC, Psichorex commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> +            });
Because the previous version of this code didn't work for me. But I will re-test this.

2024-02-20 16:46 UTC, Psichorex commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +  </ItemGroup>
My bad. I used the NuGet manager and it added it into everywhere after upgrading.

2024-02-20 16:52 UTC, Psichorex commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorChartJsTests.cs
These are most probably CTRL + K + D changes.

2024-02-20 17:15 UTC, Psichorex commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> +            });
Okay so the problem was that `3138:6` is too specific and is subject to change. So using only `Uncaught` will solve this.

2024-02-20 22:13 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorChartJsTests.cs
It's not happening for me, and they shouldn't anyway. Please revert all of them.

2024-02-21 14:31 UTC, Piedone approved these changes

2024-02-21 19:19 UTC, merged