OSOE-60: OSOCE .NET 6 and Orchard Core 1.3 upgrade
Lombiq/Open-Source-Orchard-Core-Extensions pull request #68
Opened 2022-03-10 21:54 UTC by Piedone

OSOE-60

2022-03-12 09:22 UTC, DAud-IcI requested changes

2022-03-12 09:22 UTC, DAud-IcI commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Program.cs
> +    .AuthorizeApiRequestsIfEnabled(configuration));
Indent these 2 lines because they are inside the parameter of the line above.

2022-03-15 23:00 UTC, sarahelsaig approved these changes

2022-03-17 10:52 UTC, DAud-IcI commented on NuGetTest/src/Modules/Lombiq.OSOCE.NuGet.TestModule/Lombiq.OSOCE.NuGet.TestModule.csproj
> +    <LangVersion>10.0</LangVersion>
It might be worth checking if this is still needed after the _"Build.Framework [in CI](https://ci.lombiq.com/admin/editProject.html?projectId=OrchardExtensions_OSOCE&tab=projectParams) should be net6.0 instead of netcoreapp3.1."_ step.

2022-03-17 13:17 UTC, Piedone commented on NuGetTest/src/Modules/Lombiq.OSOCE.NuGet.TestModule/Lombiq.OSOCE.NuGet.TestModule.csproj
> +    <LangVersion>10.0</LangVersion>
Unfortunately it is (otherwise the whole build would fail), and I really have no idea why.

2022-03-17 20:54 UTC, Piedone commented on NuGetTest/src/Modules/Lombiq.OSOCE.NuGet.TestModule/Lombiq.OSOCE.NuGet.TestModule.csproj
> +    <LangVersion>10.0</LangVersion>
Hmm, interestingly enough, this can be removed now. I've used the `Build.Framework` change temporarily before as well, so it's not that. I've also added the updated Analyzers package to the project (with a prerelease version) so it's not that either. I don't know... Anyway, it works now.

2022-03-17 21:01 UTC, merged