Fix setup-sql-server GitHub Windows Larger Runner incompatibility in Lombiq.GitHub.Actions
Lombiq/Open-Source-Orchard-Core-Extensions pull request #694
Opened 2024-02-06 09:18 UTC by Psichorex

OSOE-796

2024-02-06 19:49 UTC, Piedone requested changes

2024-02-06 19:49 UTC, Piedone commented on .github/workflows/build-and-test-windows.yml
>        # Should be windows-2022-8core but temporarily isn't due to this bug: https://github.com/Lombiq/GitHub-Actions/issues/320.
The comment is outdated and `dotnet-test-process-timeout` is not reverted.

2024-02-06 20:30 UTC, Psichorex commented on .github/workflows/build-and-test-windows.yml
>        # Should be windows-2022-8core but temporarily isn't due to this bug: https://github.com/Lombiq/GitHub-Actions/issues/320.
It failed me once saying it exceeded 360000 so thats why I left that

2024-02-06 20:34 UTC, Piedone commented on .github/workflows/build-and-test-windows.yml
>        # Should be windows-2022-8core but temporarily isn't due to this bug: https://github.com/Lombiq/GitHub-Actions/issues/320.
The point of using a larger runner is not to have that. It should be faster. Perhaps not that, but then you need to tune the number.

2024-02-08 12:28 UTC, Psichorex commented
UI Tests are flaky here so I am investigating what could be causing this. 
https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7820218881?pr=694

2024-02-08 15:24 UTC, Piedone commented
That's more of this issue, unfortunately: https://github.com/Lombiq/GitHub-Actions/blob/8a0d9bf1a0025857fb42f5903f516db8401e4166/.github/actions/test-dotnet/action.yml#L121 See https://github.com/actions/upload-artifact/issues/240. Not because of your changes.

2024-02-14 18:37 UTC, Psichorex commented on .github/workflows/build-and-test-windows.yml
>        # Should be windows-2022-8core but temporarily isn't due to this bug: https://github.com/Lombiq/GitHub-Actions/issues/320.
I tried up to `640000` and it still failed. It probably should be way faster if tuning is needed so I am guessing the tuning shouldn't be from `720000` -> `700000`. Other than this I addressed everything.

2024-02-14 21:39 UTC, Piedone commented on .github/workflows/build-and-test-windows.yml
>        # Should be windows-2022-8core but temporarily isn't due to this bug: https://github.com/Lombiq/GitHub-Actions/issues/320.
It works though: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7907374782

2024-02-14 21:43 UTC, merged