Create full UI test suite in Lombiq.Walkthroughs
Lombiq/Open-Source-Orchard-Core-Extensions pull request #699
Opened 2024-02-09 01:26 UTC by Piedone

2024-02-12 02:15 UTC, DemeSzabolcs requested changes

2024-02-12 02:15 UTC, DemeSzabolcs commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -            // Could be removed if https://github.com/shepherd-pro/shepherd/issues/2555 is fixed.
I guess this was removed by accident.

2024-02-12 13:15 UTC, Piedone commented on NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -            // Could be removed if https://github.com/shepherd-pro/shepherd/issues/2555 is fixed.
Yep.

2024-02-13 16:05 UTC, DemeSzabolcs approved these changes

2024-02-13 17:52 UTC, merged