Upgrade to latest OC preview to test System.Text.Json
Lombiq/Open-Source-Orchard-Core-Extensions pull request #712
Opened 2024-02-24 15:53 UTC by sarahelsaig

2024-05-08 18:04 UTC, dministro requested changes
Is `task/system-text-json-migration` the correct target branch?

As I see under other repositories, the answer is yes.

2024-05-08 18:04 UTC, dministro commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/spelling.yml@issue/OSOE-795
There is no PR for the branch `issue/OSOE-795` under LGHA

2024-05-08 18:04 UTC, dministro commented on .github/workflows/build-and-test.yml
> +      timeout-minutes: 50
Why this increased timeout is needed?

2024-05-08 18:04 UTC, dministro commented on tools/Lombiq.GitHub.Actions
There is no PR for the branch `issue/OSOE-795` under LGHA

2024-05-08 18:04 UTC, dministro commented on src/Modules/Lombiq.Hosting.Azure.ApplicationInsights
There is no PR for the branch `issue/OSOE-795`

2024-05-10 10:51 UTC, sarahelsaig commented on .github/workflows/build-and-test.yml
> +    uses: Lombiq/GitHub-Actions/.github/workflows/spelling.yml@issue/OSOE-795
Right, and PR for Orchard-Azure-Application-Insights was also missing. I've created both.

2024-05-10 10:53 UTC, sarahelsaig commented on .github/workflows/build-and-test.yml
> +      timeout-minutes: 50
I think it was accidental.

2024-05-14 19:15 UTC, dministro approved these changes

2024-05-16 20:53 UTC, dministro approved these changes

2024-05-16 20:53 UTC, merged