OSOE-83: Publish NodeJs.Extensions to NuGet
Lombiq/Open-Source-Orchard-Core-Extensions pull request #75
Opened 2022-03-22 22:55 UTC by 0liver

OSOE-83

2022-03-31 17:57 UTC, Piedone requested changes

2022-03-31 17:57 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.NodeJs.Extensions.Samples.NuGet", "src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.Samples.NuGet\Lombiq.NodeJs.Extensions.S
This needs to rather be referenced from the NuGet solution.

2022-03-31 18:40 UTC, 0liver commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.NodeJs.Extensions.Samples.NuGet", "src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.Samples.NuGet\Lombiq.NodeJs.Extensions.S
Where should I put it?
![image](https://user-images.githubusercontent.com/164360/161126574-7fdd7c79-2e19-4ef2-bf1f-b5f34f92acc8.png)

It's not really a module.

2022-03-31 18:46 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.NodeJs.Extensions.Samples.NuGet", "src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.Samples.NuGet\Lombiq.NodeJs.Extensions.S
Match the structure in the root solution.

2022-04-12 21:25 UTC, 0liver commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.NodeJs.Extensions.Samples.NuGet", "src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.Samples.NuGet\Lombiq.NodeJs.Extensions.S
Do you expect anything else to happen here with that sample module?

Also, I'm a bit confounded by the fact that an error in the SCSS throws a build error when I build the solution, but when I hit F5 it still runs. Is that normal?

2022-04-12 21:31 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.NodeJs.Extensions.Samples.NuGet", "src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.Samples.NuGet\Lombiq.NodeJs.Extensions.S
What do you mean by anything else? The NuGet solution is to test if our projects still work when in NuGet form, that's the goal here too.

Perhaps it runs with the latest successful build actually? Such build errors shouldn't be different than those produced by the C# compiler.

2022-04-12 21:51 UTC, 0liver commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.NodeJs.Extensions.Samples.NuGet", "src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.Samples.NuGet\Lombiq.NodeJs.Extensions.S
Well, the `Samples.NuGet` project doesn't do much else than reference the NE NuGet package and build its assets during the build. If that's enough, good.

For the build: I guess, I'll have to add a project reference to `Samples.NuGet` in `NuGet.Web` 😉

2022-04-12 22:13 UTC, Piedone commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.NodeJs.Extensions.Samples.NuGet", "src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.Samples.NuGet\Lombiq.NodeJs.Extensions.S
Yes. This is just about building assets.

2022-04-19 09:24 UTC, 0liver commented on Lombiq.OSOCE.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lombiq.NodeJs.Extensions.Samples.NuGet", "src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.Samples.NuGet\Lombiq.NodeJs.Extensions.S
I've got the run failure in case of npm build errors covered, now.

2022-04-19 21:16 UTC, Piedone approved these changes

2022-04-20 15:20 UTC, Piedone approved these changes

2022-04-21 23:25 UTC, Piedone approved these changes

2022-04-22 17:08 UTC, Piedone approved these changes

2022-04-22 17:12 UTC, merged

2022-04-22 19:13 UTC, 0liver commented on Directory.Build.props
> +
Ups!

2022-04-24 19:47 UTC, Piedone commented on Directory.Build.props
> +
No worries.