OSOE-835: Add test for BlockMediaThemeTemplateDirectAccessMiddleware
Lombiq/Open-Source-Orchard-Core-Extensions pull request #759
Opened 2024-05-13 08:42 UTC by AydinE

See also:
- https://github.com/Lombiq/UI-Testing-Toolbox/pull/366
- https://github.com/Lombiq/Hosting-Media-Theme/pull/61

2024-05-13 11:12 UTC, AydinE commented
@DemeSzabolcs This one should also be ready for review

Although I've now had to do this:
https://github.com/Lombiq/Hosting-Media-Theme/compare/9c09c62a2ee5f2c6ef8e8d38012393c8d32a37b3...8c51ac10a2ac6f305cd15192fa9915a0c056159d#diff-70396c083e69274cf8b94003d816588010c018e52d68ed019c305613cddff7e8R27
Instead of navigating to the page because of the middleware 
See comment: https://github.com/Lombiq/Hosting-Media-Theme/pull/61/files#diff-9b916a14ce0b71c574fd1ac93dc2750c5623eb731caa7209640a82a5c94f2363R44

Because the middleware cuts off the request you are not actually redirected to a proper 404 catch page, rather the response returns a 404 and you see the chrome/browser 404 page.

2024-05-14 21:01 UTC, DemeSzabolcs commented
FYI: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/9085727218/job/24969728561?pr=759#step:6:178

This should be fixed by merging from dev in UI Testing Toolbox.

2024-05-14 21:36 UTC, DemeSzabolcs requested changes

2024-05-14 21:36 UTC, DemeSzabolcs commented on test/Lombiq.OSOCE.Tests.UI/Tests/ThemeTests/BehaviorMediaThemeTests.cs
> +    public Task MediaThemeTemplateAccessShouldBeBlocked() =>
Also add this test to the NuGet project: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/NuGetTest/test/Lombiq.OSOCE.NuGet.Tests.UI/Tests/ThemeTests/BehaviorMediaThemeTests.cs

2024-05-16 11:30 UTC, closed without merging