Add VS Code launch files
Lombiq/Open-Source-Orchard-Core-Extensions pull request #775
Opened 2024-05-21 14:32 UTC by sarahelsaig

2024-05-21 19:06 UTC, Piedone requested changes
These would be needed for the NuGetTest solution too.

2024-05-21 19:06 UTC, Piedone commented on .vscode/launch.json
> +            "launchSettingsProfile": "Lombiq.OSOCE.Web"
Should this launch the app in a browser too? Because it doesn't for me. I'm also not sure what actually started, since while the debugger comes online, neither of the output windows show the web server running.

2024-05-22 20:27 UTC, sarahelsaig commented on .vscode/launch.json
> +            "launchSettingsProfile": "Lombiq.OSOCE.Web"
It's because Code is looking for this console out line to identify that the server is ready:
[`"pattern": "\\bNow listening on:\\s+(https?://\\S+)"`](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/775/files#diff-bd5430ee7c51dc892a67b3f2829d1f5b6d223f0fd48b82322cfd45baf9f5e945R18)

Lombiq.OSOCE doesn't output this message for the console. Why?

2024-05-22 21:42 UTC, sarahelsaig commented on .vscode/launch.json
> +            "launchSettingsProfile": "Lombiq.OSOCE.Web"
Copied the setting over from NLog.config of Lombiq.TrainingDemo, that did the trick.

2024-05-23 14:52 UTC, Piedone approved these changes

2024-05-23 14:52 UTC, Piedone commented on .gitignore
> +!.vscode/settings.json
I got a new empty vscode/settings.json file here that I committed BTW.

2024-05-23 15:45 UTC, merged