OSOE-598: Add entra authentication for live metrics
Lombiq/Open-Source-Orchard-Core-Extensions pull request #777
Opened 2024-05-22 09:18 UTC by AydinE

Also see: https://github.com/Lombiq/Orchard-Azure-Application-Insights/pull/85

2024-05-22 09:30 UTC, AydinE commented
Hey @DemeSzabolcs ,

I have tested this on an Azure App Service app. Let me know if there are any edge cases / situations that need to be tested that I might not be aware of.

I've also marked the Api Key as deprecated and updated the Readme let me know if you'd like to see any changes there.

2024-05-22 20:10 UTC, Piedone approved these changes

2024-05-23 21:08 UTC, Piedone requested changes

2024-05-23 21:08 UTC, Piedone commented on src/Lombiq.OSOCE.Web/appsettings.json
> +      "EnableLocalDevelopment": false,
For OSOCE, this can be always enabled. Also, remove `QuickPulseTelemetryModuleAuthenticationApiKey`.

2024-06-04 19:59 UTC, Piedone approved these changes

2024-06-05 22:08 UTC, Piedone approved these changes

2024-06-10 19:46 UTC, Piedone approved these changes

2024-06-14 00:04 UTC, merged