NEST-536: Update OC
Lombiq/Open-Source-Orchard-Core-Extensions pull request #829
Opened 2024-07-29 21:29 UTC by sarahelsaig

2024-08-20 21:33 UTC, Piedone requested changes
OK apart from the build failing.

2024-08-21 15:32 UTC, Piedone approved these changes

2024-08-21 22:05 UTC, Piedone requested changes
The OC version needs to be updated here too. And don't forget the submodules.

2024-08-23 17:13 UTC, Piedone requested changes

2024-08-23 17:13 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Views/Settings-Cache.Edit.cshtml
These shouldn't be needed due to https://github.com/OrchardCMS/OrchardCore/pull/16607 being merged and thus in `2.0.0-preview-18315`.

2024-08-23 17:17 UTC, sarahelsaig commented on src/Lombiq.OSOCE.Web/Views/Settings-Cache.Edit.cshtml
Ah, I forgot to delete them! More specifically, I forgot because they had no effect.

2024-08-23 17:20 UTC, Piedone approved these changes

2024-08-23 17:21 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Views/Settings-Cache.Edit.cshtml
More specifically, you forgot that you forgot.

2024-08-23 17:31 UTC, sarahelsaig commented on src/Lombiq.OSOCE.Web/Views/Settings-Cache.Edit.cshtml
https://github.com/user-attachments/assets/807c0542-e897-4efb-8918-081fa61e0649

2024-08-23 17:32 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Views/Settings-Cache.Edit.cshtml
This always cracks me up :D.

2024-08-23 17:52 UTC, Piedone approved these changes

2024-08-23 21:59 UTC, merged