OSOE-893: "Settings_Wrapper__General" should be changed to "Settings_Wrapper__Reload"
Lombiq/Open-Source-Orchard-Core-Extensions pull request #835
Opened 2024-08-06 23:40 UTC by sarahelsaig

2024-08-07 15:01 UTC, MikeAlhayek commented
https://github.com/OrchardCMS/OrchardCore/pull/16532

2024-08-08 20:44 UTC, Piedone requested changes

2024-08-08 20:44 UTC, Piedone commented on NuGetTest/src/Lombiq.OSOCE.NuGet.Web/Lombiq.OSOCE.NuGet.Web.csproj
> +    <PackageReference Include="Lombiq.AuditTrailExtensions" Version="6.0.2-alpha.1.osoe-893" />
18300 has another driver change: https://github.com/OrchardCMS/OrchardCore/pull/16530

2024-08-08 20:44 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
>          "Host": "localhost"
These are now provided by `ConfigureHostingDefaults`.

2024-08-08 21:50 UTC, sarahelsaig commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
>          "Host": "localhost"
Are you sure this works? When I remove these lines I get this error:
![7](https://github.com/user-attachments/assets/ae1b239d-7be4-4c02-8b16-aa4e425aa719)

2024-08-08 22:11 UTC, sarahelsaig commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
>          "Host": "localhost"
And without `DefaultSender` it just says "connection refused".
![image](https://github.com/user-attachments/assets/609cd9ae-f3c8-4edb-b632-fe8faa5cc781)

2024-08-08 23:33 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Recipes/Lombiq.OSOCE.Tests.recipe.json
>          "Host": "localhost"
The config was incomplete, needed `IsEnabled` too.

2024-08-09 00:58 UTC, Piedone approved these changes

2024-08-09 10:15 UTC, merged