OSOE-818: Upgrade to Orchard Core 2.0
Lombiq/Open-Source-Orchard-Core-Extensions pull request #853
Opened 2024-09-22 21:08 UTC by sarahelsaig

2024-09-23 23:52 UTC, Piedone requested changes

2024-09-23 23:52 UTC, Piedone commented on NuGet.config
> -    <add key="OrchardCorePreview" value="https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json" />
Why remove this?

2024-09-23 23:52 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
Use [`AddNavigationProvider`](https://github.com/OrchardCMS/OrchardCore/blob/80ff8b867a286544ab135c0a1301034bf5146303/src/OrchardCore/OrchardCore.Navigation.Core/ServiceCollectionExtensions.cs#L24) everywhere.

2024-09-23 23:52 UTC, Piedone commented on test/Lombiq.OSOCE.Tests.UI/Tests/ModuleTests/BehaviorWalkthroughsTests.cs
> -            // Could be removed if https://github.com/shepherd-pro/shepherd/issues/2555 is fixed.
This can be done in NuGetTest too.

2024-09-23 23:52 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
Sealing would be good: https://docs.orchardcore.net/en/latest/releases/2.0.0/#sealing-types

2024-09-23 23:52 UTC, Piedone commented on src/Lombiq.OSOCE.Web/Lombiq.OSOCE.Web.csproj
Use `AddPermissionProvider`, see https://docs.orchardcore.net/en/latest/releases/2.0.0/#miscellaneous.

2024-09-24 08:31 UTC, sarahelsaig commented on NuGet.config
> -    <add key="OrchardCorePreview" value="https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json" />
Good question. Restored.

2024-09-24 18:53 UTC, Piedone approved these changes

2024-09-26 16:29 UTC, merged