Migrating tests, Lombiq.UITestingToolbox and Lombiq.Tests to xUnit v3
Lombiq/Open-Source-Orchard-Core-Extensions pull request #909
Opened 2024-12-21 22:36 UTC by Piedone

2025-01-16 22:04 UTC, dministro requested changes
Merge from dev please.

2025-01-22 04:35 UTC, Piedone commented on .github/workflows/build-and-test.yml
> +      blame-hang-timeout: 600000
See https://github.com/Lombiq/UI-Testing-Toolbox/issues/228#issuecomment-2605946303

2025-02-11 21:43 UTC, dministro requested changes
Merge from dev please.

2025-02-13 22:02 UTC, dministro approved these changes

2025-02-13 22:42 UTC, merged